### ISSUE TITLE
Error en las Regiones Académicas

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#100]
Las RA están bien definidas y no existe la RA llamada "Otra". Hay que eliminarla y que no aparezca por defecto en el sistema.

**Comment by ybenitezf** [comment]
las provincias perteneces a una RA, por ese vinculo necesito asociar la provincia a una región académica, como fue necesario introducir "Otra" en comunas, municipios y provincias lo mismo pasa con la RA.
