### ISSUE TITLE
Problemas al exportar lista de candidatos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#101]
La lista de candidatos, cuando se exporta a excel sale desconfigurada, es decir, se solapan el número de identidad con el nombre. Creo que el nombre de la UO a la que pertenece se lleva mucho espacio, valoremos agregarle a la UO un campo llamado "siglas" para solo poner las siglas y así ahorrar espacio. Hay de definirle un mayor tamaño al número de identidad para que no se solape con el nombre.

**Comment by ybenitezf** [comment]
tu diras el PDF, porque es lo unico que he puesto a exportar del listado de candidatos.

A mi me sale bien, mandame un ejemplo del listado donde se solapen los nombres.

**Comment by eadomenech** [comment]
El 25/8/15, Yoel Benítez Fonseca notifications@github.com escribió:

> tu diras el PDF, porque es lo unico que he puesto a exportar del listado de
> candidatos.
> 
> A mi me sale bien, mandame un ejemplo del listado donde se solapen los
> nombres.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/101#issuecomment-134610186

Aquí te adjunto como me sale a mi.

## 

Saludos,
  Ernesto.

**Comment by eadomenech** [comment]
Te lo mandé al correo de gmail.
