### ISSUE TITLE
Reorganizar configuración de las carreras

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#11]
La gestión de las carreras que está implementada debe pasar a Miselanias (Cambiar Miselanias por General) y crear una sección de configuración de carreras en Escuela pero que solo sea asignar los cursos que se imparten en la escuela. En esta última se dará la opción de escoger alguna o algunas de las carreras existentes (almacenadas).

**Comment by ybenitezf** [comment]
en la parte de carreras en la Escuela ¿es para hacer la asociación
esta carrera se imparte aquí?, es decir tendríamos 2 secciones una
para la configuración general de las carreras y otra con las carreras
que se imparten en una escuela determinada.

2015-03-24 16:21 GMT-04:00, Ernesto Avila Domenech notifications@github.com:

> Assigned #11 to @ybenitezf.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/11#event-263958756

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
Esto me va a tomar más tiempo del que pensaba, web2py no es muy bueno menejando las relaciones mucho a mucho, en este caso si utilizo el control que he venido usando hasta ahora (SQLFORM.grid) me deja entrar duplicado. Así que voy a tener que meterle mano a pulmon.

**Comment by eadomenech** [comment]
pues mira, si es así debes hacer un componente pues aquí lo que más hay es relaciones de mucho a mucho

**Comment by ybenitezf** [comment]
No, Ya di con la expresión que debe resolverme el problema, una consulta un poco enredada:

``` python
db(db.career_ihe.career_id == None).select(db.career.ALL,db.career_ihe.ALL,left=db.career_ihe.on(db.career.id==db.career_ihe.career_id))
```
