### ISSUE TITLE
Emolumentos (Pagos realizados por los estudiantes a la UO)

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#118]
Un emolumento es una entrega monetaria que se realiza por parte de los estudiantes a la UO por determinados motivos. Viene siendo como un impuesto.
Un emolumento posee un nombre, un valor y un campo "activo". El valor representa la cantidad que se debe entregar para tener pago el emolumento. Por ejemplo, un estudiante que quiera inscribirse para realizar los exámenes de acceso para una determinada carrera en un año académico, debe abonar a la UO 2000 kz. El campo "activo" significará si el tipo de emolumento está activo o no.  

Los emolumentos aprobados en el 2015 y que utilizaremos en el sistema son los siguientes:

**Inscripción a Examen de Acceso** (Nombre: "Inscrição ao Exame de Acesso"; Valor: 2000 kz; Activo: Estará "True" mientras, y solo mientas, exista un evento de tipo "Inscrição", de lo contrario estará "False")
**Matrícula y Confirmación de Matrícula** (Nombre: "Matrícula e confirmação de matrícula"; Valor: 2000 kz; Activo: Estará "True" mientras, y solo mientas, exista un evento de tipo "Matrícula", de lo contrario estará "False")
**Confirmación de matrícula después del plazo establecido** (Nombre: "Confirmação da matrícula apos o prazo legal"; Valor: 10000 kz; Activo: Estará "True" mientras no exista un evento de tipo "Matrícula" activo)

Los tipos de emolumentos antes mencionados estarán desde un inicio en el sistema y no se podrá adicionar uno nuevo ni se podrá eliminar uno ya existente, solo se podrá modificar el campo "Valor" y el campo "Activo".  
Es posible que en un futuro tengamos que utilizar otros tipos de emolumentos. Se irán agregando a medida que los vayamos necesitando para otros procesos.

**Comment by ybenitezf** [comment]
Por favor si puedes pon las cosas en español, cuando sea necesario que algún texto aparezca específicamente en PT pon la traducción al lado en español entre paréntesis.

**Comment by eadomenech** [comment]
Loco todavía no he terminado, si ahora es que empiezo. Aún no te he asignado esta historia.

**Comment by ybenitezf** [comment]
aquí estas mezclando 2 cosas, una cosa es los tipos de pago que se puedan realizar y la otra es cuando se pueden realizar los tipos de pago, de momento voy a asumir que aquí y en el #203 estamos hablando de la definición de los tipos de pago. El cuando esta activo y cuando no depende por lo que veo de los eventos en concreto.

**Comment by eadomenech** [comment]
El 203 es la funcionalidad q da respuesta o aterriza el 118 q es la 
historia como tal

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 26 de noviembre de 2015 21:18:06 Yoel Benítez Fonseca 
notifications@github.com escribio:
