### ISSUE TITLE
Problema al actualizar las plazas máximas a otorgar para una determinada carrera

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#127]
En las plazas a otorgar, al modificar el número máximo de plazas a otorgar y dar clic en el botón Guardar, no se actualiza este campo. Al intentar modificar por segunda vez es que se actualiza dicho campo. 

Esto ocurre con los 3 campos (Plazas mínimas, plazas máximas y media necesaria).

**Comment by ybenitezf** [comment]
El error no se repite aquí:
1. Voy donde estan los planes:

![paso1](https://cloud.githubusercontent.com/assets/8646381/10138036/6c3cfef0-65ca-11e5-9648-e745ccb39e08.png)
1. escojo la carrera:

![paso2](https://cloud.githubusercontent.com/assets/8646381/10138044/77db33b2-65ca-11e5-93c0-3c076dd6d708.png)
1. Introduzco los datos y le doy guardar:

![paso3](https://cloud.githubusercontent.com/assets/8646381/10138050/83312870-65ca-11e5-8fc5-b17b30a787eb.png)

Y los datos se guardan a la primara.
