### ISSUE TITLE
Problema con la posición del logotipo de la institución en los pdf exportados

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#128]
El logotipo en los pdf que se exportan no se encuentra correctamente centrado. En correspondencia con el nombre de la universidad se observa que no se encuentra centrado.

**Comment by ybenitezf** [comment]
El problema viene de la librería, supongo más adelante podemos probar a usar alguna otra librería pero de momento esto me parece que es perder el tiempo.

Si estas de acuerdo vamos a cerrar esto.

**Comment by ybenitezf** [comment]
Necesito confirmación

**Comment by eadomenech** [comment]
La imagen no esta centrada Esto me dijiste era problema de la libreria q utilizas y q luego verias si utilizar otra.

**Comment by ybenitezf** [comment]
vamos  a cerrarlo entonces y después abrimos otro.

**Comment by eadomenech** [comment]
Closed.
