### ISSUE TITLE
Limitar el número de caracteres utilizados para el nombre completo de cada persona

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#129]
Al realizar una candidatura se limitará a 35 el número de caracteres a utilizar entre el nombre y los dos apellidos de las personas candidatas. Esto se hará para evitar que se sobreponga el nombre completo en el campo siguiente a la hora de exportase a .pdf.
![nombre sobrepuesto](https://cloud.githubusercontent.com/assets/11457046/9878533/2073f578-5bbb-11e5-8aa1-e1b1096e59d3.jpg)

**Comment by ybenitezf** [comment]
Y cual es la distribución que vamos a usar ? 15 el nombre y 10 para cada apellido ?

**Comment by eadomenech** [comment]
El primer apellido no sera obligado ponerlo Es decir podrá quedar vacío 
SERAN 35 ENTRE entre el nombre 1apellido y 2apellido No habrá límite para 
cada campo individual Sera 35 entre los 3

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 22 de septiembre de 2015 12:48:23 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Loco, a ver, no tengo forma de validar el nombre completo de esa
forma, lo que si puedo hacer es poner limites en la entrada por cada
uno de los campos, por eso te pretunté como repartir las cantidades
entre cada uno de los campos.

Además el campo nombre_completo en el modelo de persona es un campo
calculado, lo que puedo hacer es que cuando se calcule nombre
_completo no se le sume el primer apellido ya que no es obligatorio
¿resolvemos con eso?

El 22/9/15, Ernesto Avila Domenech notifications@github.com escribió:

> El primer apellido no sera obligado ponerlo Es decir podrá quedar vacío
> SERAN 35 ENTRE entre el nombre 1apellido y 2apellido No habrá límite para
> cada campo individual Sera 35 entre los 3
> 
> Enviado con Aquamail para Android
> http://www.aqua-mail.com
> 
> El 22 de septiembre de 2015 12:48:23 Yoel Benítez Fonseca
> notifications@github.com escribio:
> 
> > Y cual es la distribución que vamos a usar ? 15 el nombre y 10 para cada
> > apellido ?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/yotech/agis/issues/129#issuecomment-142263104
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/129#issuecomment-142278418

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
http://redevil.cubava.cu/
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
Creo que lo mejor sería lo siguiente:
1. En los reportes donde aparece le nombre de una persona siempre se utiliza el campo `nombre_completo`
2. Como `nombre_completo` es un campo virtual que se calcula a partir del nombre y los apellidos se podría hacer que el valor calculado sea `nombre` + `apellido1[0]` + `apellido2`, es decir el nombre más la primera letra del primer apellido más el segúndo apellido completo.

Por ejemplo:
- `nombre = "Yoel"`
- `apellido1="Benítez"`
- `apellido2="Fonseca"`

Podría dar como resultado: `Yoel B. Fonseca`

**Comment by ybenitezf** [comment]
necesito confirmación para seguir

**Comment by eadomenech** [comment]
Confirmado.
Limita al nombre y al 2do apellido a 15 cada uno.

2015-09-22 15:11 GMT+01:00, Yoel Benítez Fonseca notifications@github.com:

> necesito confirmación para seguir
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/129#issuecomment-142300321

## 

Saludos,
  Ernesto.
