### ISSUE TITLE
Gestionar Candidatos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#14]
El sistema debe poder adicionar, modificar y eliminar a los candidatos a ingresar a la Enseñanza Superior, en este caso a la Unidad Orgánica que se creó con anterioridad. Los datos necesarios de los candidatos son los siguientes: Prefijo (Señor o Señora), Usuario de acceso al sistema, Contraseña de acceso al sistema, Nombre completo (65 caracteres), Fecha de nacimiento (10 dígitos), Género con su código (1 dígito) correspondiente (Masculino:1 ; Femenino:2) , Estado civil (1 dígito; Casado:1; Soltero:2; Divorciado:3; Otro:4), Tipo de documento de identidad, Número de Documento de identidad, Fecha de emisión del Documento de identidad, Entidad que emitió el Documento de identidad, Nombre del padre, Nombre de la madre, Natural de (Municipio), Nacionalidad (se seleccionará uno de todos los países existentes), Habilitación (esto es el grado anterior logrado 11no, 12º ect), Procedencia Escolar de Enseñanza Media (1 dígito), Escuela de procedencia, Curso de Procedencia (20 caracteres), Año de conclusión, Estatus (Civil, Militaro o Policía), Condición (Estudiante trabajador o No trabajador), Nombre del trabajo (20 caracteres), Profesión, Provincia, Necesidad de educación especial, Estado (Activo e Inactivo), Procesos que posee (Certificado original, Cópia de documento, Documento de trabajo, Documento Militar, Internato), Dirección particular incluyendo comuna, Teléfono, Curso a lo que se candidata (pueden ser hasta 2 de los que se imparten en la UO y deben elegirse en orden de prioridad), Forma de pago (TPA, Novo bordereaux) en ambos casos se tiene la cantidad y en el caso específico del bordereaux tiene un número, Número de expediente (4 dígitos) corresponde al orden de inserción de este candidato, email, Nombre del curso de procedencia en la enseñaza media (20 caracteres), Nota de examen de acceso (en base a 20), Admitido (1:Si; 0:No), Matriculados por primera ves (1:Si; 0:No), Regimen.

**Comment by ybenitezf** [comment]
En la #7 - gestion de regimenes - me dicies que lo asocie a las UO ¿no
es mejor dejarlo como una asociación a los candidatos ?

2015-03-25 12:51 GMT-04:00, Ernesto Avila Domenech notifications@github.com:

> Assigned #14 to @ybenitezf.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/14#event-264941380

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
¿cuales son los " Tipo de documento de identidad" ? ¿cuales son los posibles valores para eso, o lo pongo como un edit para que pongan lo que quieran ?

**Comment by eadomenech** [comment]
Mira los valores que tiene el SIGA. Toy aun en la univ haciendo la
estadisticas q hay que entregar. te escribo cuando este listo.

2015-03-30 13:18 GMT+01:00 Yoel Benítez Fonseca notifications@github.com:

> ¿cuales son los " Tipo de documento de identidad" ? ¿cuales son los
> posibles valores para eso, o lo pongo como un edit para que pongan lo que
> quieran ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yotech/agis/issues/14#issuecomment-87654526.

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
Por desgracia no siempre estoy en la PC donde pudo ver la BD del SIGA,
ahora mismo donde estoy no tengo acceso a eso,no importa después veo
como es eso.

El 30/3/15, Ernesto Avila Domenech notifications@github.com escribió:

> Mira los valores que tiene el SIGA. Toy aun en la univ haciendo la
> estadisticas q hay que entregar. te escribo cuando este listo.
> 
> 2015-03-30 13:18 GMT+01:00 Yoel Benítez Fonseca notifications@github.com:
> 
> > ¿cuales son los " Tipo de documento de identidad" ? ¿cuales son los
> > posibles valores para eso, o lo pongo como un edit para que pongan lo que
> > quieran ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/yotech/agis/issues/14#issuecomment-87654526.
> 
> ## 
> 
> Saludos,
>   Ernesto.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/14#issuecomment-87659861

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
"Usuario de acceso al sistema, Contraseña de acceso al sistema" esto significa que los candidatos van a tener acceso al sistema ?

**Comment by eadomenech** [comment]
Los Tipos de documentos de identidad pueden ser gestionados. Por defecto el sistema debe traer los siguientes: Billete de Identidad, Pasaporte, Carta de Condición y Carta de Residencia.

**Comment by eadomenech** [comment]
Como bien dices el régimen se asocia a los candidatos. Ellos eligen en qué régimen estudiar y este se le asigna.

**Comment by eadomenech** [comment]
Los candidatos no tendrán usuario ni contraseña. Sí tendrán e-mail para poderles enviar si es admitido o no por e-mail aunque este campo no será obligatorio, no dudo que hayan unos cuantos sin correo electrónico. Tienes que tener en cuenta que los admitidos tendrán que hacer la matrícula luego y no tendrán que escribir otra vez los datos. Solo se adicionarán los campos usuario y contraseña. Quizás haya que adicionales otros campos pero eso lo veremos en el proceso de matrícula.

**Comment by ybenitezf** [comment]
Lo del usurio y contraseña es para saber, como ya te podras imaginar web2py tiene sus propias tablas para la autenticación que incluyen esos valores.. asi que sería hacer referencia a los mismos, depués en algún momento me tendrás que decir a que cosas tendrán acceso ellos como estudiantes.

**Comment by ybenitezf** [comment]
Para la gestión de los candidatos se tienen que introducir los siguientes datos sobre el candidato:

_Personales_:
- **Prefijo** (*): Los prefijos son un texto que acompaña al nombre, por ejemplo: `Señor` o `Señora`, dar alusuario la opción de que escoja - no es necesario guardar en la base de datos los vamores completos, se pueden usar las abrebiaturas: `Sr` o `Sra`.
- **Nombre y Apellidos** (*): El nombre completo del candidato, guardar nombre y cada apellido por separado debido a que es posible que sea necesario solo usar parte de este en los reportes.
- **Fecha de nacimiento** (*): Mostrar un control que permita escoger la fecha de nacimiento.
- **Natural** (*): Seleccionar el municipio donde nació de los que están registrados en el sistema.
- **Genero** (*) : `Femenino` o `Masculino`,  usar internamente los códigos `2` y `1` respectivamente y permitir que el usuario escoja uno de los dos.
- **Estado civil** (*): Los posibles valores `Casado`(1),`Soltero`(2),`Divorciado`(3) y `Otro`(4), permitir escoger uno de los anteriores aunque internamente solo se guarde su códificación.
- **No. de Identidad** (*): El número del documento de identidad. Como se manejan varios tipos de documentos de identidad no se pueden poner restricciones en cuanto al formato y longitud del mismo, pero es requerido. Dos personas no podrán tener un mismo No. de Identidad.
- **Tipo de documento de identidad(DI)** (*): Escoger dentro de los que se han registrado en el sistema. Por defecto mostrar como primera opción `Billete de Identidad` que es el más común.
- **Entidad que emite el DI** (*): Nombre de la entidad que emite el documento de identidad.
- **Nombre de la madre** (*)
- **Nombre del padre** (*)
- **Nacionalidad**
- **Estado** (*): `Civil`, `Militar` o `Policía`, escoger uno de estos, el más común es `Civil`.

_Laborales_:
- **Condición** (*): escoger entre trabajador o no trabajador, es posible que sea mejor plantearlo en forma de pregunta: ¿es trabajador?
- **Profesión**: en caso de que sea trabajador especificar la profesión.
- **Nombre del trabajo**: Nombre del trabajo al que pertenece.

_Datos de contacto_:
- **Municipio** (*): Seleccionar el municipio de residencia de los que están registrados en el sistema.
- **Comuna** (*): Escoger de las que se encuentran registradas para el municipio.
- **Dirección** (*):
- **Teléfono**: Número de telefono del candidato.
- **e-mail**: Dirección de correo del candidato, no es requirida por es posible que el mismo no tenga correo electronico, en caso de tener el mismo se usara para mandar notificaciones al candidato.

_Procedencia_:
- **Habilitación**: nivel alcanzado por el candidato en el nivel anterior, por ejemplo: 11no, 9no, etc. El valor más común es 12.
- **Escuela de procedencia** (*): Escoger de las escuelas de enseñanza media registradas en el sistema.
- **Tipo de enseñanza media de procedencia** (*): Escoger el tipo de enseñanza media de procedencia de donde viene el candidato.
- **Carrera de procedencia** (*): Nombre de la carrera de la que procede el candidato, restringir a 20 caracteres.
- **Año de conclusión**: Año en que termino la escuela media o carrera de procedencia.

_Institución_:
- **Unidad Organica**: La unidad organica a la que pertenecerá el candidato en el futuro, dar la posibilidad de escoger de las que esten registradas en la base de datos, cuando se presente el formulario mostrar por defecto la primera que se encuentre en la base de datos.
- **Necesita educación especial**: en el caso de de que se marque la necesidad de educación especial se deben seleccionar además las discapacidades del candidato.
- **Estado Interno** (*): `activo` o `inactivo`. Por defecto activo. Este atributo será interno. Se utilizará para en caso de eliminar al candidato, no se elimine físicamente de la base de datos.
- **Documentos**: `Certificado original` (1), `Cópia de documento` (2), `Documento de trabajo` (3), `Documento Militar` (4), `Internato` (5), escoger 0 o más de estos.
- **Carrera a la que se candidata**: Se cogen 2, con prioridades de las que se estudian en la UO.
- **Número de expediente de candidatura**: Un número que se va incrementando por 1 por cada uno de los candidatos que se insertan en el sistema. Posee 4 dígitos.
- **Estado**: Será el estado en que se encuentre el candidato. Los estados podrán ser: Inscripto con deuda, Inscripto, Inscripto no admitido e Inscripto admitido.
- **Régimen**: Escoger de los posibles regímenes en la UO a cual se candidata.
- **Notas de exámenes de acceso**: Los candidatos tendrán que realizar un número determinado de exámenes; la materia de los mismo está en dependencia de las carreras por las que estén optando. Estos campos solo estarán disponibles para su modificación cuando se esté en el evento correspondiente a la calificación de exámenes de acceso del año en que se esté. 

Se debe permitir las operaciones crear, actualizar, borrar y listar sobre los datos de los candidatos.

De la información anterior todo lo marcado con (*) es de carácter obligatoria.

**Comment by eadomenech** [comment]
En la gestión de los candidatos vamos a dividir el tipo de escuela de enseñaza media, con la escuela en si. Es decir, se agregará un campo en la gestión de candidatos que sea Tipo de escuela de presedencia. Este campo iria antes de Escuela de presedencia. Una vez esté este campo, en el campo de escuela de presedencia solo apacerán las escuelas que tengan este tipo. En caso de que el tipo sea "Estudios realizados en el extranjero" se desabilitará el campo Escuela de presedencia.

**Comment by eadomenech** [comment]
A la hora de adicionar un candidato faltan los campos correspondiente a las  2 carreras por la que opta el candidato.

**Comment by eadomenech** [comment]
Yoel Benitez Fonseca: si estas por ahi contestame una pregunta a ver si tiene sentido para ti, te explico: vamos a tener 3 tablas: persona-estudiante-candidatura (https://github.com/yotech/agis/issues/14), estoy tratando de ver que cosas van en cada cual, las de persona soy faciles de dicernir, el problema esta en las cosas que van para estudiante y cuales van para candidatura: por ejemplo ¿tiene sentido poner habilitación, escuela de procedencia, tip de enseñanza de procedencia, carrera de procedencia, año de conclusion en estudiante en ves de en candidatura ? la logica es la siguiente, si el candidato no es escogido el primer año el siguiente va a seguir proviniendo de donde mismo y si en algún momento se conbierte en estudiante, esos datos se van a mantener sin alterar independientemente del # de candidaturas que haga el estudiante

**Comment by eadomenech** [comment]
Yoel Benitez Fonseca: otra: ¿puede ser que hagas la candidatura en otra unidad organica y como estudiante (ya despues de matricular) vayas a matricular en una unidad organica diferente ?

**Comment by eadomenech** [comment]
Si. Hay un tipo de confirmación de matrícula que se llama Matrícula con Histórico, que s eutiliza para caso de traslados y similares.

**Comment by ybenitezf** [comment]
¿el proceso de candidatura esa asociado a un año academico? te pregunto pq si cada estudiante puede tener varios procesos de candidatura se supone que solo se presente una ves por año ¿no? entonce con quien lo asocio ¿con año academico?

**Comment by eadomenech** [comment]
Si, con año academico

El 18/6/15, Yoel Benítez Fonseca notifications@github.com escribió:

> ¿el proceso de candidatura esa asociado a un año academico? te pregunto pq
> si cada estudiante puede tener varios procesos de candidatura se supone que
> solo se presente una ves por año ¿no? entonce con quien lo asocio ¿con año
> academico?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/14#issuecomment-113225904

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
![proceso_candidatura](https://cloud.githubusercontent.com/assets/8646381/8256635/641ca336-1676-11e5-97fa-56a9a871d30d.png)
Esta es la idea que tengo para el proceso de candidatura, y así pienso implementarla, pero primero mirala y dime que piensas o preguntame sino entiendes para no hacer cosas por gusto.

**Comment by ybenitezf** [comment]
Estoy cerrando este issue, creo que ya esta resuelto, por lo menos darle de alta de un candidato.
