### ISSUE TITLE
Consultar por carrera solicitada

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#147]
En el listado de los candidados se podrá consultar teniendo en cuenta la carrera solicitada en 1ª opción y también teniendo en cuenta la carrera solicitada en 2ª opción. Es decir, utilizando el grid deberán aparecer los campos carrera en 1ª opción y carrera en 2ª opción. 
Se necesita conocer el listado de los candidatos que optan por una carrera determinada

**Comment by ybenitezf** [comment]
Confirmame una cosa, tu sabes que ahí tenemos una relación muchos a muchos entre carreras y candidaturas, si se hace una consulta por ejemplo haciendo un join de candidaturas contra la tabla de la relación vamos a acabar con duplicados en el listado de candidatos ¿no?

**Comment by eadomenech** [comment]
Agregandole un atributo opción (1ra o 2da) a la relación 
carrera-candidatura y hacer q el gris comience predefinido con opción 1 
para q no se repita.
Con eso no logramos hacer lo q están pidiendo?

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 29 de septiembre de 2015 13:49:13 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Fijate en los modelos:

`candidatura(id, ...)`
`carrera(id, ...)`

Y la relación que hay entre esas dos que representa las carreras que quiere el estudiante:

`candidatura_carrera(candidatura_id, carrera_id, prioridad)`

Hay más tablas implicadas claro esta pero estas son las que importan aquí.

El comentario lo puse solo para confirmar que con SQL solamente ahí no podemos resolver, lo que implica que el GRID no nos sirve debido a que aparecerán duplicados.

Mi propuesta es la siguiente: poner en donde se muestran las carreras de las UO un enlace en cada carrera para que se puedan ver/consultar/etc los candidatos de esta carrera, no se si con eso resolvemos, la diferencia es que ya de antemano tendría fijada la carrera sobre la que voy a buscar y no tendría duplicados.

**Comment by eadomenech** [comment]
Tú propuesta puede ser pero con alguna variación Te explico No hay q ir a 
las carreras de cada UO Eso pertenece a candidatura y debe estar en 
candidatura Lo q propongo es hacer lo q dices pero en la parte de dar los 
resultados por carrera Es decir Ahí mismo en Candidatos, en el menú de la 
izquierda agregaremos al menos 2 campos Uno sería resultados generales 
(luego te explico q pondremos ahi) y otro resultado x carrera. Con este 
último tendremos el listado de los candidatos q optan en esa carrera 
Evidentemente tendrá con estado No admitido pero eso no importa En caso de 
que quieran sólo la lista q exporten eso a Excel y le quiten las columnas 
diferentes al nombre completo.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 29 de septiembre de 2015 15:49:19 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Esa era la otra propuesta que te iba a hacer, poner en alguna sección independiente ese reporte que quieres, entonces sería así:
1. Se selecciona Docentes-Candidatos en el menú.
2. En el menú lateral aparecerá "Resultados por carreras".
3. Se muestran las carreras de la UO para seleccionar una.
4. Se presenta el reporte en un GRID (**OJO especificar que debe aparecer en el reporte**)

**Comment by eadomenech** [comment]
Ok Eso es un issue q todavía no lo he puesto Lo q pasa es q con ese issue 
se resuelve el pedido Adjunto una foto de mi borrador Luego cuando suba el 
issue lo pondré separado y con una mejor calidad

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 29 de septiembre de 2015 16:06:05 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
No entendí, si es que vas a reescribir este issue no crees uno nuevo, simplemente arregla este, editar arriba en la descripción original.

**Comment by ybenitezf** [comment]
¿por fin esto como quedo?

**Comment by eadomenech** [comment]
Esta opción es posible realizarla con el issue #152. Closed.
