### ISSUE TITLE
Listar candidatos por carrera

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#152]
Se deberá listar a los estudiantes por carrera. Se tendrá en cuenta las 2 posibles opciones por la que opta el candidato. 
Si el candidato opta por 2 carreras aparecerá en el listado de cada una de estas dos carreras, pudiendo estar Admitido a los sumo en 1 de ellas.
1. Se selecciona Docentes-Candidatos en el menú.
2. En el menú lateral aparecerá "Resultados por carreras".
3. Se muestran las carreras de la UO para seleccionar una.
4. Se presenta el reporte en un GRID con los campos (Nº de Inscripción; Nombre completo; Nombre de asignatura examinada 1; Nombre de asignatura examinada 2; ...; Nombre de asignatura examinada N; Media de las notas alcanzadas; Estado (Admitido; No Admitido))

N es el número de asignaturas a examinar para poder optar a la carrera.
Si un estudiante debe examinar la asignatura X para poder optar la carrera Y y no se presenta, se le asignará automáticamente la nota 0 en dicha asignatura. Para la media se tendrá en cuenta esta nota.
Se podrá realizar consultas utilizando el GRID. 
![cxcarrera](https://cloud.githubusercontent.com/assets/11457046/10215290/284ce566-6818-11e5-91bc-6a9ef22a262a.png)

Nota: Este issue da solución al issue #147

**Comment by ybenitezf** [comment]
Que bien, vas cogiendo la idea, lol

2015-10-01 3:43 GMT-04:00, Ernesto Avila Domenech notifications@github.com:

> Assigned #152 to @ybenitezf.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/152#event-423935815

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
http://redevil.cubava.cu/
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
¿quien tiene acceso a esto? es solo para el admin ? o los profesores podrán verlo también o todos los usuarios, o los candidatos y profesores que tengan que ver ?

**Comment by eadomenech** [comment]
En este tema de roles tú tienes más experiencia q yo Supongo q haya q crear 
un rol admin de examen de acceso harán estos lo q tengan acceso

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 5 de octubre de 2015 20:37:11 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
¿un rol solo para eso? no, creo que mejor lo dejamos de momento para el admin y ya veremos, si después descubrimos algún rol al que le podamos endilgar esa responsabilidad.

**Comment by ybenitezf** [comment]
¿este reporte es para enviarlo al ministerio?  te pregunto para saber si vale la pena ponerle toda la gangaría del nombre de la escuela, logo y unidad organica.

**Comment by eadomenech** [comment]
No es para el ministerio pero lleva la gangaria

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 12 de octubre de 2015 16:27:28 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by eadomenech** [comment]
El listado debe aparecer por defecto organizado según las medias. De mayor a menor.

**Comment by ybenitezf** [comment]
aquí tengo un par de problemas a la hora de mostrar el listado:
1. Lo que me dijiste de que algunos candidatos salen repetidos tiene sentido, no es que sean aceptados en 2 carreras al mismo tiempo, sino que la vista resultados por carrera te muestra todos los candidatos que hayan solicitado la carrrera en cualquiera de sus opciones, ahora supon que A solicito C1 y C2, y no fue aceptado en C1 sino en C2, cuando se haga la consulta de resultado por carrera de C1 entonces A va a aparecer en el listado aunque no haya sido admitido en C1. ¿tiene eso sentido para ti?
2. No puedo ordenarlos por la media usando un GRID, o mejor dicho si los quiero ordenados por la media no puedo utilizar un GRID por el sencillo hecho de que tengo sus notas (que también hay que mostrar) regadas por varios registro de otra tabla, en resumen que no hay forma de hacer una consulta que implique todos los datos sin obtener datos repetidos eso si quiero mostrar todas las notas. En resumen que hay que hacerlo a mano todo, desde la busqueda, el paginado, etc.

**Comment by eadomenech** [comment]
Tengo claro q el candidato debe salir en las dos listas Eso o es el 
problema Dee hecho tiene q ser así Lo q veo mal es q sale como admitido en 
las 2 y ese admitido corresponde con la carrera q se está mostrando Por 
tanto si un est opta x A y B y queda admitido en A entonces en la lista de 
la carrera B debe aparecer pero como No Admitido
En cuanto a ordenar x la media hay, suba soluciquon aunqupqe fea pero es 
efexctiva y es crear un Campo a una tabla q sea media Puede ser en 
calndidatura Es verdad q redundamos datos pero con eso logramos lo q 
queremos y podemos seguir avanzando Si crees q sería malo hacer eso 
entonces los ordenamos x nombre y esperamos a ver q dice el cliente

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 23 de octubre de 2015 16:06:57 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by eadomenech** [comment]
En ningun caso haremos eso a palo No tenemos tiempo como para eso Hay q 
avanzar Si es mucho problema pues lo ordenamos x nombre y listo Seguimos 
avanzando

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 23 de octubre de 2015 16:06:57 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Siempre hemos hablado de los estados de la candidatura, que de momento pueden ser `INSCRITO_CON_DEUDAS`, `INSCRITO`, `NO_ADMITIDO` y `ADMITIDO`, pero **no es respecto a una carrera**, es decir cuando lo admito o no, cambia el `esta_candidatura` y en la tabla `asignacion_carrera` se le pone en que carrera es admitido, si es que lo es.

Ahora tu necesitas una vista donde se vean los resultados para una carrera concreta, y como te explique antes, puede pasar que un candidato aparezca en el listado aunque no haya sido admitido para esa carrera.

Obligatoriamente tengo que hacerlo todo a mano para cumplir con los requisitos.

**Comment by eadomenech** [comment]
No creo Si válidas q sea admitido y tenga asignada esa carrera lo pones 
admitido en el grid De lo contrario lo pones No Admitido para esa carrera 
aunque este como estado Admitido

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 23 de octubre de 2015 16:41:21 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Otro dato más que no vendría de la consulta del GRID, entiendes !? además que en realidad la candidatura si estaría admitida lo que no en esa carrera.

**Comment by eadomenech** [comment]
Yoe prefiero poner otro campo en alguna tabla aunque sea redundante que 
consumir un tiempo valioso reprogramando eso En un futuro cuando tengamos 
todo listo podremos pensar en optimizarlo si es q el cliente continúa Te 
propongo hacer lo q ellos piden aunque sepamos q estamos redundando

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 23 de octubre de 2015 16:52:32 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Subí varios cambios al repo, **OJO**:
1.  En la vista resultados por carrera lo único que pude rehusar - y menos mal para no tener que hacerlo a palo - fue el formulario de búsqueda.
2. El orden esta fijo a la media, de mayor a menor, como el listado no puede utilizar el grid por todos los problemas que ya discutimos no se da la posibilidad de re-ordenar los resultados por otro parámetro.
3. Por el mismo motivo que no se pudo utilizar el grid, la forma de exportar es diferente que en las demás vistas aunque el resultado es el mismo.

**Comment by eadomenech** [comment]
Lo veo bien así como está.
Lo que no veo bien es que aparecen carreras por la que no se ha optado.

El 23/10/15, Yoel Benítez Fonseca notifications@github.com escribió:

> Subí varios cambios al repo, **OJO**:
> 1.  En la vista resultados por carrera lo único que pude rehusar - y menos
>    mal para no tener que hacerlo a palo - fue el formulario de búsqueda.
> 2. El orden esta fijo a la media, de mayor a menor, como el listado no puede
>    utilizar el grid por todos los problemas que ya discutimos no se da la
>    posibilidad de re-ordenar los resultados por otro parámetro.
> 3. Por el mismo motivo que no se pudo utilizar el grid, la forma de exportar
>    es diferente que en las demás vistas aunque el resultado es el mismo.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/152#issuecomment-150683836

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
son las carreras que tiene definida la unidad organica, que no hayan
optado por ellas no significa que no lo puedan hacer....

El 24/10/15, Ernesto Avila Domenech notifications@github.com escribió:

> Lo veo bien así como está.
> Lo que no veo bien es que aparecen carreras por la que no se ha optado.
> 
> El 23/10/15, Yoel Benítez Fonseca notifications@github.com escribió:
> 
> > Subí varios cambios al repo, **OJO**:
> > 1.  En la vista resultados por carrera lo único que pude rehusar - y
> >    menos
> >    mal para no tener que hacerlo a palo - fue el formulario de búsqueda.
> > 2. El orden esta fijo a la media, de mayor a menor, como el listado no
> >    puede
> >    utilizar el grid por todos los problemas que ya discutimos no se da la
> >    posibilidad de re-ordenar los resultados por otro parámetro.
> > 3. Por el mismo motivo que no se pudo utilizar el grid, la forma de
> >    exportar
> >    es diferente que en las demás vistas aunque el resultado es el mismo.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/yotech/agis/issues/152#issuecomment-150683836
> 
> ## 
> 
> Saludos,
>   Ernesto.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/152#issuecomment-150817868

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
http://redevil.cubava.cu/
Tel.: (53 32)284701
