### ISSUE TITLE
Corregir nombre del botón Terminar

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#164]
Al modificar los datos de un candidato, al final, aparecen dos botones con el mismo texto "Siguiente". Me imagino que uno de ellos debe decir Terminar.

**Comment by ybenitezf** [comment]
Oye, eso no me así en ninguna parte, mira lo SC:

pantalla1:
![screenshot from 2015-11-02 09 44 12](https://cloud.githubusercontent.com/assets/8646381/10884445/20294c20-8146-11e5-8f97-aa4758cd0881.png)

pantalla2:
![screenshot from 2015-11-02 09 44 19](https://cloud.githubusercontent.com/assets/8646381/10884458/28683c52-8146-11e5-8bf1-67c81480b121.png)

pantalla3:
![screenshot from 2015-11-02 09 44 23](https://cloud.githubusercontent.com/assets/8646381/10884465/325e5548-8146-11e5-9da4-bab16eae6987.png)

no veo que me aparezca ningún botón con el texto repetido.

**Comment by ybenitezf** [comment]
revisa que es posible que sea que en la traducción pusiste "Saltar" y "Siguiente" como "Siguiente", debe ser eso, si eso prueba por ti mismo a cambiar el lenguaje del navegador.

**Comment by eadomenech** [comment]
Corregido. Era problema de la traducción. Closed!
