### ISSUE TITLE
Establecer regla para el documento de identidad

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#173]
Tanto en la inscripción como en la matrícula se debe tener en cuenta el país de nacimiento para lo siguiente:
**1:** Si el estudiante posee como país de origen a Angola, solo se le permitirá como documento de identidad el "Billete de identidade".
**2:** Si el estudiante posee como país de origen un país distinto a "Angola", solo se le permitirá como documento de identidad el "Passaporte".

**Comment by ybenitezf** [comment]
ver #180
