### ISSUE TITLE
Registrar pago de tipo "Matrícula e confirmação de matrícula"

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#176]
A esta funcionalidad se podrá acceder desde Contabilidad->Registrar Pago de Matrícula.
Para realizar un pago de tipo "Matrícula e confirmação de matrícula", se procede de la siguiente manera:

**1:** Al dar clic en "Registrar pago de Matrícula", no se dará la opción de seleccionar un evento de tipo "Matrícula", puesto que si este existe solo existirá uno activo, pues el sistema no permitirá que existan 2 eventos de este tipo de forma activa. En caso de que no exista ningún evento de tipo "Matrícula" se comunicará al usuario. En caso de que haya uno activo se pasará a este de forma directa y se mostrará de la forma siguiente:
![registra pago de matricula](https://cloud.githubusercontent.com/assets/11457046/11420087/fff04c8a-942b-11e5-88eb-faadd783a367.png)

**2:** En el formulario anterior aparecerá mediante un grid los datos Número de identidad, Nombre completo y Estado en la UO (ver issue #57 ). También aparecerá a la derecha, de cada estudiante con estado "SIN MATRICULAR CON DEUDA", un botón "Pagar deuda".
**3:** A la derecha de cada estudiante con estado "SIN MATRICULAR CON DEUDA" aparecerá un botón para acceder al formulario de pago ya implementado.
![formulario de pago de matricula](https://cloud.githubusercontent.com/assets/11457046/11420481/a0e679f0-942e-11e5-82b7-90833e93d8d3.png)

**4:** Se exportará a pdf de forma similar como se exporta en el pago de la Inscripción.

**Comment by ybenitezf** [comment]
Recuerda que me dejaste una historia sin desarrollar, la de los emolumentos esos y si mal no me equivoco tiene que ver con esto de los pagos, si implemento esto ¿después no se verá afectada esta parte?
