### ISSUE TITLE
Modificar formulario Iniciar Candidatura

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#180]
En el formulario Iniciar Candidatura se realizarán algunas modificaciones donde se debe tener en cuenta lo siguiente:
**1:** Luego de campo "Género" se adicionará un campo llamado "País de origen". En este campo se deberá seleccionar uno de los países existente en el sistema.
**2:** En caso de seleccionar el país "ANGOLA" aparecerá el campo "Lugar de nacimiento" donde se seleccionará la comuna donde nació el estudiante que se candidata. 
**3:** En caso de seleccionar como país de origen un país diferente a "ANGOLA", el campo "Lugar de nacimiento no aparecerá" y aparecerá la pregunta "Posee nacionalidad angolana?".
**4:** Si el candidato posee como país de origen a ANGOLA o posee nacionalidad angolana entonces el sistema pondrá como tipo de documento de identidad a "BILHETE DE IDENTIDADE" y no se podrá modificar. 
**5:** Si el candidato posee como país de origen un país distinto a ANGOLA y no posee nacionalidad angolana entonces el sistema pondrá como tipo de documento de identidad a "PASSAPORTE" y no se podrá modificar.
**6:** Luego de campo "Estado político" se adicionará un campo llamado "País de residencia". En este campo se deberá seleccionar uno de los países existente en el sistema. Por defecto aparecerá "ANGOLA"
**7:** Los campos "Provincia", "Municipio" y "Comuna" pertenecientes a la residencia, se deshabilitarían en caso de seleccionarse como país de residencia a un país distinto a "ANGOLA".

Notas:
**1-**El punto 1 donde se habla del campo "País de origen", es el campo que actualmente tiene como nombre "Nacionalidad". En este caso habría que subirlo y colocarlo luego del "Género". 
**2-**Los puntos 4 y 5 son lo mismo que el issue #173 
**3-**Evaluar quitar los campos "Provincia", "Municipio" y "Comuna" pertenecientes a la residencia y poner solo un campo similar a "Lugar de nacimiento" pues este pertenece a un municipio y este a su vez pertenece a una provincia; por lo que conociendo la comuna podríamos conocer también el municipio y la provincia. Es solo evaluar, si lleva mucho tiempo lo dejamos así para poder seguir avanzando.

**Comment by ybenitezf** [comment]
Supongo que todo esto será valido para todas las personas, es decir,
para los profesores también ?

El 12/11/15, Ernesto Avila Domenech notifications@github.com escribió:

> En el formulario Iniciar Candidatura se realizarán algunas modificaciones
> donde se debe tener en cuenta lo siguiente:
> *_1: *_Luego de campo "Género" se adicionará un campo llamado "País de
> origen". En este campo se deberá seleccionar uno de los países existente en
> el sistema.
> *_2: *_En caso de seleccionar el país "ANGOLA" aparecerá el campo "Lugar de
> nacimiento" donde se seleccionará la comuna donde nació el estudiante que se
> candidata.
> *_3: *_En caso de seleccionar como país de origen un país diferente a
> "ANGOLA", el campo "Lugar de nacimiento no aparecerá" y aparecerá la
> pregunta "Posee nacionalidad angolana?".
> *_4: *_Si el candidato posee como país de origen a ANGOLA o posee
> nacionalidad angolana entonces el sistema pondrá como tipo de documento de
> identidad a "BILHETE DE IDENTIDADE" y no se podrá modificar.
> *_5: *_Si el candidato posee como país de origen un país distinto a ANGOLA y
> no posee nacionalidad angolana entonces el sistema pondrá como tipo de
> documento de identidad a "PASSAPORTE" y no se podrá modificar.
> *_6: *_Luego de campo "Estado político" se adicionará un campo llamado "País
> de residencia". En este campo se deberá seleccionar uno de los países
> existente en el sistema. Por defecto aparecerá "ANGOLA"
> *_7: *_Los campos "Provincia", "Municipio" y "Comuna" pertenecientes a la
> residencia, se deshabilitarían en caso de seleccionarse como país de
> residencia a un país distinto a "ANGOLA".
> 
> Notas:
> **1-**El punto 1 donde se habla del campo "País de origen", es el campo que
> actualmente tiene como nombre "Nacionalidad". En este caso habría que
> subirlo y colocarlo luego del "Género".
> **2-**Los puntos 4 y 5 son lo mismo que el issue #173
> **3-**Evaluar quitar los campos "Provincia", "Municipio" y "Comuna"
> pertenecientes a la residencia y poner solo un campo similar a "Lugar de
> nacimiento" pues este pertenece a un municipio y este a su vez pertenece a
> una provincia; por lo que conociendo la comuna podríamos conocer también el
> municipio y la provincia. Es solo evaluar, si lleva mucho tiempo lo dejamos
> así para poder seguir avanzando.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/180

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
http://redevil.cubava.cu/
Tel.: (53 32)284701

**Comment by eadomenech** [comment]
Esto te lo había contestado x email pero la respuesta no la veo aquí. Así que vuelvo a responder.
Si, esto es para todas las personas.
