### ISSUE TITLE
Adicionar campo "Teléfono alternativo" a las personas

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#183]
Una persona podrá tener más de un número telefónico, por lo que se deberá adicionar un campo llamado "Teléfono alternativo" a las personas. Dicho campo no será obligatorio para la creación de la persona en el sistema.

**Comment by ybenitezf** [comment]
¿con un solo teléfono alternativo basta? no hará falta la posibilidad de agregar más de dos teléfonos ?

**Comment by eadomenech** [comment]
A medida q se agregue uno q de la posibilidad de acondicionar otro

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 21 de noviembre de 2015 16:23:02 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
y otro? y otro ? ...

**Comment by ybenitezf** [comment]
me voy con la fácil, 2 números de teléfono

**Comment by eadomenech** [comment]
Ok
