### ISSUE TITLE
Rectificar código generado de la UO

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#188]
En el noveno dígito del código generado por el sistema a la UO debe aparecer 0 pues es una Unidad Orgánica. Actualmente aparece 1 y no es correcto pues no es Sede central.

**Comment by ybenitezf** [comment]
No, entendí, a ver se pone 1 para sede central y 0 para unidad orgánica no ? actualmente esta así:

``` python
NIVELES = {
    '0': 'SEDE CENTRAL',
    '1': 'UNIDADE ORGÂNICA',
}
```

**Comment by ybenitezf** [comment]
¿puedes contestar la pregunta mano?

**Comment by eadomenech** [comment]
``` python
NIVELES = {
    '1': 'SEDE CENTRAL',
    '0': 'UNIDADE ORGÂNICA',
}
```

Así es como debe ser

**Comment by ybenitezf** [comment]
ok, error mio parece que los puse invertidos en algún momento.
