### ISSUE TITLE
Cambiar periodo de los examenes de acceso

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#191]
El periodo NO será "Mañana", "Tarde" o "Noche". Será un intervalo de tiempo, es decir, Hora-Hora. Por ejemplo: 09:00-11:00. Otro ejemplo: 14:00-16:30.

**Comment by ybenitezf** [comment]
Discúlpame ¿esto es sugerencia de los jefes? Es que no le veo sentido al periodo de tiempo H-H, supongo allá será igual que aquí y una ves que inicie el examen no se dejaran entrar a los estudiantes, de todas formas no importa creo que con especificar la fecha y hora del examen debería ser suficiente en vez de usar una estructura Hora-Hora.

Te propongo lo siguiente:

El modelo (tabla) de examen incluye los campos `fecha: date` y `periodo`, ¿no sería mejor cambiar estos a `fecha: datetime` (fecha y hora de inicio) y en ves de periodo incluir uno que sea duración? o sencillamente dejarlo con fecha y hora de inicio ya que al final importa poco a que hora se termina.

**Comment by eadomenech** [comment]
Yo le veo lógica a lo que propones y estoy de acuerdo contigo. Pero en
la cultura de ellos está lo que están proponiendo de Hora-Hora. Acá
para todas las reuniones, eventos, etc. lo hace y escriben así. En fin
para avanzar sin ningún inconveniente te propongo hacer lo que ellos
están pidiendo aunque pensemos que no tiene lógica.
Esto es si no hay mayores complicaciones para ponerlo así. En caso de
que haya que realizar otras cosas para lograr esto pondríamos hora de
inicio y hora fin.

El 23/11/15, Yoel Benítez Fonseca notifications@github.com escribió:

> Discúlpame ¿esto es sugerencia de los jefes? Es que no le veo sentido al
> periodo de tiempo H-H, supongo allá será igual que aquí y una ves que inicie
> el examen no se dejaran entrar a los estudiantes, de todas formas no importa
> creo que con especificar la fecha y hora del examen debería ser suficiente
> en vez de usar una estructura Hora-Hora.
> 
> Te propongo lo siguiente:
> 
> El modelo (tabla) de examen incluye los campos `fecha: date` y
> `periodo`, ¿no sería mejor cambiar estos a `fecha: datetime` (fecha
> y hora de inicio) y en ves de periodo incluir uno que sea duración? o
> sencillamente dejarlo con fecha y hora de inicio ya que al final importa
> poco a que hora se termina.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/191#issuecomment-158975760

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
OK
