### ISSUE TITLE
Modificar formulario de Examen de Acceso

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#197]
Una vez dado clic en "Examen de Acceso" aparecerá, en caso de existir y estar activo, un evento de tipo Inscripción. En el mismo aparecerá a la derecha 2 botones llamados "Acceder" y "Asignar carrera y obtener resultados". En la figura el 1 corresponde al "Acceder" y el 2 a "Asignar carrera y obtener resultados". Evidentemente los iconos de estos botones no son el 1 y 2, estos números son solo para identificar.  
![ea1](https://cloud.githubusercontent.com/assets/11457046/11348865/541d98da-9229-11e5-99bb-d03e9faf8226.png)

Al dar clic en el botón "Acceder" se irá al formulario ya realizado donde aparecen las disciplinas necesaria a realizar. Esto se mantendría como está implementado en la actualidad.
![examenes](https://cloud.githubusercontent.com/assets/11457046/11348966/c9047c7c-9229-11e5-9735-ba5309a67db2.png)

Al dar clic en el botón "Asignar carrera y obtener resultados", se dará la opción de seleccionar una de las carreras activas en la UO y que posea como número máximo de plazas un número mayor que 0 en al menos uno de los régimenes de la UO. 
![carreras](https://cloud.githubusercontent.com/assets/11457046/11348990/fc11a270-9229-11e5-9a45-1ec912f60358.png)

Si la carrera seleccionada posee como número máximo de plazas un número mayor que 0 en más de un régimen entonces se dará la posibilidad de seleccionar uno de estos régimenes.
![regimenes](https://cloud.githubusercontent.com/assets/11457046/11349039/53d5c982-922a-11e5-85b0-f8d0e8f1698e.png)

Al tener la carrera y el régimen que se desean mostrar sus resultados, se hará la asignación de las carreras y se mostrarán los resultados para esta carrera y regimen de la forma implementada en la actualidad. 
![resultados1](https://cloud.githubusercontent.com/assets/11457046/11349139/d92e79da-922a-11e5-9bcc-d7a90d407414.png)

Nota: En las imágenes tomadas al sistema se debe tener en cuenta que en menú de la izquierda lo que debe estar señalado es la opción "Examen de Acceso" y NO "Resultados por curso".

**Comment by ybenitezf** [comment]
No entiendo bien lo que quieres lograr con esto.

**Comment by ybenitezf** [comment]
Oye esto no creo que sea buena idea, contéstame. Estas agrupando (empaquetando, sobrecargando) 2 funcionalidades en 1, además ¿"Asignar carrera y obtener resultados"?

**Comment by ybenitezf** [comment]
creo que aquí es mejor agregar un boton/enlace a la vista donde aparecen los examenes con el rotulo "Asignar carrera y obtener resultados" en ves de modificar eso en el selector de eventos, es más sencillo y no es necesario modificar el código actual, es la solución más rápida y eficiente.

**Comment by eadomenech** [comment]
Ok La pruebo cuando llegue a casa

**Comment by ybenitezf** [comment]
si, cuando lo haga supongo.
