### ISSUE TITLE
Gestionar las Procedencias Escolar de Enseñanza Media

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#20]
El sistema debe poder adicionar, modificar y eliminar las Procedencias Escolar de Enseñanza Media. Una Procedencia Escolar de Enseñanza Media tienen un nombre y un código (1 dígito).

**Comment by ybenitezf** [comment]
¿no sería mejor agregar un nuevo menu para las cosas de los candidatos? por ejemplo MENU->Estudiantado->Candidatos ? y poner las cosas de #14, #19 y #20 en ese contexto ?
Fijate que yo me estoy guiando por tu diseño, no podemos repetir el regero que tenian en SIGA

**Comment by eadomenech** [comment]
Tienes toda la razón. Creo que es necesario hacer como especie de un mapa de navegación para que te guíes. Por el momento agrega un campo "Estudiantado" y dentro de este "Candidatos". Yo me pondré a pensar en un posible mapa de navegación y te lo haré llegar lo más rápido posible para que me des tu criterio.

**Comment by ybenitezf** [comment]
Ok, otra cosa que no he echo por falta de tiempo y problemas con la mierda de PC que tengo aqui es hacer un digrama ER o conceptual de la BD y ver que cosas se pueden limpiar o mejorar o modelar de una manera diferente de forma que no acavmos en desastre.
