### ISSUE TITLE
Duplicidad de eventos tipo Inscripção y Matrícula

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#202]
En un mismo año académico no pueden existir 2 eventos de tipo "Inscrição". Lo mismo ocurre con el tipo "Matrícula".

**Comment by ybenitezf** [comment]
Será como sigue - al final es lo que siempre te dije:
1. Cuando se creé un año académico automáticamente se crearan para este los eventos de inscripción y matricula correspondientes.
2. Cuando se pasa al manejo de eventos solo se podrán editar los que están creados y a estos solo se les podrá fijar las fechas de inicio o de fin, además del estado.

**Comment by eadomenech** [comment]
Perfecto. Esa idea nunca me la dijiste. Lo veo bien. Estas escapao

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 27 de noviembre de 2015 16:17:20 Yoel Benítez Fonseca 
notifications@github.com escribio:
