### ISSUE TITLE
Modificar formulario "Registrar pago de Inscripción"

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#204]
El formulario "Registrar pago de Inscripción" se modificará teniendo en cuenta lo siguiente:

**1:** Al dar clic en "Registra pago de Inscripción", no se dará la opción de seleccionar un evento de tipo "Inscrição", puesto que si este existe solo existirá uno activo el pues el sistema no permitirá que existan 2 eventos de este tipo de forma activa. En caso de que no exista ningún evento de tipo "Inscrição" se comunicará al usuario. En caso de que haya uno activo se pasará a este de forma directa y se mostrará de la forma siguiente:
![registra pago de inscripcion](https://cloud.githubusercontent.com/assets/11457046/11402602/05d3cafc-9399-11e5-80c2-d98246ea5110.png)
**2:** Los datos mostrados son los correspondientes al Nº de identidad (Bilhete o Pasaporte), Nombre completo y Estado. El estado podrán ser ("Con deuda": en caso de que no haya pago la inscripción correspondiente al año académico correspondiente al año académico del evento donde se está; "Inscripto": Si ya pagó la inscripción)
**3:** A la derecha de cada estudiante con estado "Con deuda" aparecerá un botón para acceder al formulario de pago ya implementado.
![formulario de pago de inscripcion](https://cloud.githubusercontent.com/assets/11457046/11402968/9fe38578-939a-11e5-8023-efa8d1b2138e.png)
**4:** Se exportará a pdf de la siguiente forma:
![resultados de pagos de inscripcion exportado a pdf](https://cloud.githubusercontent.com/assets/11457046/11402985/b57bf1d6-939a-11e5-95b2-eb6efe0952e1.png)
**5:** Se exportará a xls de la misma forma que en pdf pero no se pondrá el logotipo.

Nota:
**1:** Por el momento solo tendremos un IES y una UO, lo que lo puse de forma genérica.
**2:** Ojo que 46 x 2000 no es igual a 935000. eso se debe que existió como mínimo un estudiante que pagó más de los 2000 kz establecidos. Esto no provoca ningún cambio en el sistema pero si se debe contabilizar en ese reporte. Es decir, se debe mostrar la cantidad exacta que se colocó en la cuenta de la escuela.

**Comment by ybenitezf** [comment]
Entonces ¿tendré que permitir que tecleen la cantidad exacta recaudada en cada pago? de otra forma no podría dar ese total, además ¿en e listado tendré que mostrar lo que en verdad pago cada uno no lo estipulado en el tipo de pago o voy a tener que estar calculando la diferencia entre esos 2 valores para cada candidatura antes de ponerla en el reporte?

**Comment by eadomenech** [comment]
La cantidad real abonada como bien dices hay q escribirla.
Pondrías a la derecha la cantidad real q abonó cada estudiante.
El reporte sera la suma total.
Cuando se escriba la cantidad q abonó debe comprobarse q es mayor o igual q 
lo exigido. En el caso de la inscripción como bien sabes es 2000 pero eso 
puede variar.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 27 de noviembre de 2015 16:24:07 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Cuando se van a mostrar los pagos en el listado, puede ser que por ejemplo para el pago de inscripción el estudiantes haga 2 pagos en diferentes momentos: por ejemplo 2 pagos de 1000 para completar los 2000 que se requieren ¿muestro cada pago de forma individual o el total pagado por cada estudiante?

**Comment by eadomenech** [comment]
No, eso no será permitido. El estudiante tiene que pagar como mínimo
lo exigido, en este caso de inscripción 2000 kz. Ahh, lo que puede ser
es que el estudiante pague más y así será registrado.
No nos vamos a complicar con eso. Si el estudiante paga más de lo que
debe pagar será tomado como un regalo a la universidad.
No vamos a estar dejando la diferencia para el otro pago ni nada de eso.

El 27/11/15, Yoel Benítez Fonseca notifications@github.com escribió:

> Cuando se van a mostrar los pagos en el listado, puede ser que por ejemplo
> para el pago de inscripción el estudiantes haga 2 pagos en diferentes
> momentos: por ejemplo 2 pagos de 1000 para completar los 2000 que se
> requieren ¿muestro cada pago de forma individual o el total pagado por cada
> estudiante?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/204#issuecomment-160216241

## 

Saludos,
  Ernesto.
