### ISSUE TITLE
Adicionar campo "Código asignado por el IES" a las carreras

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#218]
El IES (Instituto de Educación Superior) asigna un código a cada carrera que se imparte en sus unidades orgánicas. Este código son números de dos dígitos, ejemplo (02).
Hay que tener en cuenta que aunque una carrera se imparta en distintas Unidades Orgánicas pertenecientes al mismo IES tendrá el mismo código, ya que el código lo da el IES y no cada UO. 
Lo que propongo aquí es hacer en la configuración del IES lo mismo que hacemos en Carreras de la UO, lo que en este caso por cada carrera que se agregue se tendría que asignar el código de dos dígitos. Luego en Carreras de la UO se escogería pero de las carreras que tiene el IES y no de todas las que tiene el ministerio.

**Comment by ybenitezf** [comment]
claro eso será parte de descripción de carrera en la escuela, no de la instancia particular de la carrera dentro de la UO... mira que joden con los codigitos y todavía no he visto una parte donde los usemos además de en la entrada de los datos.

**Comment by eadomenech** [comment]
jajaja, ya pronto los empezarás a ver en los números mecanográficos de
los estudiantes.

El 15/12/15, Yoel Benítez Fonseca notifications@github.com escribió:

> claro eso será parte de descripción de carrera en la escuela, no de la
> instancia particular de la carrera dentro de la UO... mira que joden con los
> codigitos y todavía no he visto una parte donde los usemos además de en la
> entrada de los datos.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/218#issuecomment-164843475

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
Aquí hay un problema que no tuvimos en cuenta, como la APP importa las descripciones de las carreras desde un csv la primera ves que se ejecuta ¿qué códigos les pone?, tu los tienes?

**Comment by ybenitezf** [comment]
@eadomenech: Creo q no entendiste el issue. En la configuracion del IES, luego del logo, se adicionaran carreras al estilovq hacemos en la actualidad en Cursos de la UO, ahi existira un campo q sea codigo asignado por el IES a la carrera. Luego en Carreras de la UO se seleccionara pero en vez de aparecer todos las carreras del ministerio, solo se podra escoger de las carreras q tiene el IES

**Comment by ybenitezf** [comment]
Esto lo cerré por ahora pero es posible que las consecuencias del cambio se vean en otras partes.
