### ISSUE TITLE
Separar proceso de Matrícula

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#219]
En la actualidad un año académico posee un proceso de inscripción y uno de matrícula, es decir, al crear un año académico, automáticamente se crean los procesos de Inscripción y Matrícula correspondientes a ese año académico.
Lo que realmente se debe hacer es crear 3 procesos, Inscripción, Confirmación de Matrícula y Matrícula.
*_Inscripción: *_ Es el proceso que ya hemos realizado.
*_Confirmación de Matrícula: *_ Es el proceso donde los estudiantes continuantes confirman sus datos, carrera y nivel académico. También se les comunica el grupo al que pertenecen.
*_Matrícula: *_ Es el proceso en el cual los estudiantes admitidos en el proceso de inscripción hacen la matricula en la UO.

**Comment by ybenitezf** [comment]
¿confirmación de matricula también es un evento? tiene una fecha de inicio y fin ?

**Comment by eadomenech** [comment]
En un principio tenía la idea que tanto confirmación de matrícula como la matrícula de los iniciantes era el mismo proceso y ocurría al mismo tiempo. Luego de la reunión que tuve ayer me explicaron que no ocurre así. 
La confirmación de matrícula es un evento distinto al de Matrícula, ambos hacen lo mismo, solo que la confirmación es para los continuantes y la Matrícula es para los iniciantes.

Si, tanto confirmación como Matrícula tienen una fecha de inicio y una fin y pueden solaparse, es decir, puede que en algún momento determinado estén ocurriendo las dos.

**Comment by ybenitezf** [comment]
OK, pero la pregunta es ¿podemos unir nosotros el proceso de confirmación y matricula en una sola cosa? aunque pare ellos sean dos diferentes?

**Comment by eadomenech** [comment]
No. En un principio tenía esa idea pero ocurre lo siguiente:
1- El rango de fechas para cada uno de esos eventos es diferente, por
ejemplo, para el año académico que viene (2016) la universidad orientó
realizar la confirmación entre el 18 de enero al 30 de febrero y la
Matrícula la orientó entre las fechas 27 de febrero y 5 de marzo.
2- La confirmación solo involucra a los continuantes.
3- La matrícula solo involucra a los admitidos en el proceso de
inscripción correspondiente a este año.
4- Existen estadísticas a entregar para cada uno de estos eventos y
también existen estadísticas a entregar que involucran a los 2
eventos.

El 16/12/15, Yoel Benítez Fonseca notifications@github.com escribió:

> OK, pero la pregunta es ¿podemos unir nosotros el proceso de confirmación y
> matricula en una sola cosa? aunque pare ellos sean dos diferentes?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/219#issuecomment-165126440

## 

Saludos,
  Ernesto.
