### ISSUE TITLE
Corrección del valor por el cual se organizan los estudiantes inscriptos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#220]
En la actualidad el sistema calcula la media de los exámenes de acceso y mediante este número se organizan dichos estudiantes para poder asignar las carreras.
Esto debe cambiar de la siguiente forma:
**1:** Cada examen tendrá un por ciento de importancia para cada carrera, este no debe ser mayor que 100.
**2:** La nota adquirida en cada examen se multiplicaría por el por ciento de importancia.
**3:** La suma de los valores obtenidos en el punto 2 sería la "Nota Final" del estudiante para optar por una carrera determinada.

Propongo plasmarlo en el sistema de la siguiente manera:
![importancia de los examenes](https://cloud.githubusercontent.com/assets/11457046/11815464/27898566-a34c-11e5-995a-e295b136243a.png)

**Comment by ybenitezf** [comment]
Loco, esto va a meter un churre de **4 pares** en lo que tenemos hecho.

**Comment by ybenitezf** [comment]
Pregunta: ¿ese valor de importancia afectará la media obtenida para el candidato o solo será un valor que manejaremos internamente para la asignación de las carreras? Lo que quiero decir es que si los valores de las medias a mostrar en los reportes será lo que mostramos actualmente o el valor que obtenemos al introducir el % de importancia de las asignaturas en el calcula de la media.
