### ISSUE TITLE
Problemas con el Sobrenombre o 1er apellido

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#222]
Cuando se realiza una inscripción se permite introducir más de 15 caracteres en el sobrenombre o 1er apellido y luego si se va a modificar o actualizar a esta persona no se permite, mostrando el sistema que este campo debe poseer menos de 15 caracteres.

**Comment by ybenitezf** [comment]
¿de verdad te parece esto algo en lo que perder el tiempo? ... joder..

**Comment by eadomenech** [comment]
Esto puede parecer pérdida de tiempo pero no lo creo. Mi razón es la siguiente, en el proceso de confirmación de matrícula se confirmarán los datos de cada estudiante y me imagino que reutilicemos este código o llamemos a esta función como tal y es ahí donde dará el bateo. No creo te lleve mucho tiempo resolver este inconveniente.

**Comment by ybenitezf** [comment]
¿confirmar los datos de cada estudiante? Dejame ver que crees tu que significa eso

**Comment by eadomenech** [comment]
Literalmente, se confirman los datos de cada estudiante. Unos se confirman y otros se actualizan según hayan cambiando, como la dirección o el teléfono.
