### ISSUE TITLE
Gestionar Escuelas pertenecientes a la Enseñanza Media

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#23]
Para la gestión de las Escuelas pertenecientes a la Enseñanza Media se tienen que introducir los siguientes datos:
- **Código** (*): Será un número de 4 dígito.  
- **Nombre** (*): Nombre completo de la escuela. 
- **Provincia** (*): Provincia donde se encuentra ubicada. El usuario podrá elegir dento de las provincias que posee el sistema. Por defecto debe estar en la provincia donde se encuentra ubicada la UO. 
- **Municipio** (*): Seleccionar el municipio donde se encuentra ubicada la escuela. Es usuario podrá seleccionar un municipio de los que posee el sistema. Por defecto estará en el municipio donde se encuentre la UO. En caso de marcar con anterioridad la provincia, solo se mostrarán los municipios pertenecientes a esta.

**Comment by ybenitezf** [comment]
Aquí se te olvido que además las escuelas tienen un tipo que es el que se gestiona en el otro issue
