### ISSUE TITLE
Arreglos para el proceso de candidatura

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#243]
**1:** El número de expediente debe tener tamaño 4 y no 5.
**2:** En la actualidad, el sistema no permite modificar los datos de un candidato determinado.
**3:** El sistema debe dar la oportunidad de ir al paso anterior al estar realizando una candidatura.
**4:** Al seleccionar que el candidato hizo estudios medio en el extranjero, el sistema no debe obligar a seleccionar un campo como Escuela de Ensino Medio.

**Comment by ybenitezf** [comment]
Quedamos en que vamos a usar el no. de inscripción como el no, de expediente ? si el de inscripción es de 5 el de expediente también debe serlo, o no podrán ser iguales.

En el punto 2, soy consciente, falta la parte de editar, no esta implementado de momento.

Punto 3, se puede vivir sin eso, ese formulario es monumental y muy complicado, de momento se puede quedar así.

el punto 4, esta claro, eso se arregla.

**Comment by eadomenech** [comment]
Papo, está claro que tienen que ser iguales pero quedamos y debe tener 4, no 5. Los dos, ambos inclusives tendrán 4.

**Comment by ybenitezf** [comment]
ok, en cuanto al no. de inscripción.
