### ISSUE TITLE
Gestió de Fucionarios

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#247]
Existen personas en la UO que poseen determinada responsabilidad. Dichos funcionarios podrán tener permiso para determinadas acciones como es el caso de los procesos de Inscripción, Confirmación de Matrícula y Matrícula, así como el registro de los pagos correspondientes.
Los funcionarios se dividen en 2 tipos, los docentes (profesores que actualmente gestionamos) y los administrativos. 

Los funcionarios docentes poseen además de los datos de una persona los siguientes:
**Grado:** Pueden ser "Bacharelato", "Licenciatura", "Mestrado" o "Doutoramento".
**Vículo:** Pueden ser "Efectivo", "Colaborador" u "Outro".
**Categoria Docente:** Pueden ser "Assistente Estagiario", "Professor Assistente", "Professor Auxilhar", "Professor Associado", "Professor Titular" u "Outra".
**Data de entrada:** Es la data de entrada a la institución.
**Departamento:** Departamento al que pertenece.
**Estado:** El docente podrá estar activo o no.

Los funcionarios administrativos poseen además de los datos de una persona los siguientes:
**Grado:** Pueden ser "Bacharelato", "Licenciatura", "Mestrado" o "Doutoramento".
**Vículo:** Pueden ser "Efectivo", "Colaborador" u "Outro".
**Data de entrada:** Es la data de entrada a la institución.
**Departamento:** Departamento al que pertenece.
**Estado:** El docente podrá estar activo o no.

Los funcionarios administrativos no pueden ser asignados a disciplinas.
Un estudiante puede ser un funcionario administrativo.

**Comment by ybenitezf** [comment]
¿así que la única diferencia entre el funcionario y el profesor es que los profesores van a tener una categoría docente?

**Comment by eadomenech** [comment]
Los funcionarios administrativos no pueden ser asignados a disciplinas.
Un estudiante puede ser un funcionario administrativo.
