### ISSUE TITLE
Confirmación de Matrícula

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#249]
Teniendo en cuenta el issue #57  y para dar respuesta al issue #219, se describe lo que se propone para la Confirmación de Matrícula.
Aparecerá en un grid los campos # Mecanográfico, # de Identidad, Nombre y Estado. El Estado será una de las clasificaciones explicadas en el issue #57 ( Sin matricular con deuda, Sin matricular, Matriculado con deuda o Matriculado). 
Además, a la derecha de cada estudiante aparecerán 2 botones, uno para registrar el pago correspondiente a la confirmación de la matrícula y el otro para confirmar los datos correspondientes a este estudiante.
Para cada estudiante, estará inhabilitado el acceso a la confirmación de los datos mientras no registre el pago correspondiente a la confirmación de la matrícula. Una vez que se registre el pago de un estudiante se podrá acceder a la confirmación de sus datos y dar por terminada la confirmación de la matrícula.
![cm1](https://cloud.githubusercontent.com/assets/11457046/12486968/5a568cec-c065-11e5-958c-4df4d94a5846.png)
Si la carrera seleccionada posee especialidades (en nuestro caso Pedagogia) y el Nivel Académico a confirmar es 3º, 4º o Finalista, entonces se tendrá que seleccionar dicha especialidad de las existentes en esta carrera.
![cm2](https://cloud.githubusercontent.com/assets/11457046/12487095/ffa45076-c065-11e5-8ad2-70baba3cf0eb.png)
Si la Situación Académica es "1ª Matrìcula-Novo", "Aprovado em toda-ano anterior", "Transferencia", "Estagio" o "Preparação de tessis" se dará por terminada la confirmación de matrícula quedando el estudiante Matriculado.
En caso que la Situación Académica fuese "Aprovado com Cadeiras em atraso" se listarán las disciplinas correspondientes al Nivel Académico anterior al que se está confirmando para que se seleccionen cuales de ellas son las que se van a arrastrar.
En caso que la Situación Académica fuese "Repetentes" se listarán las disciplinas correspondientes al Nivel Académico que se está confirmando para seleccionar de ellas las que se van a repetir.
Se permitirá exportar a PDF y XLS. Los campos a exportar serán # Mecanográfico, Nombre, Estado y Situación académica. En el caso de XLS no se pondrá el logo de la universidad.
Sólo aparecerán en el grid para la confirmación de matrícula los estudiantes continúantes, es decir, los que tengan como "Situación académica" un valor distinto a "1ª Matrícula-Novo" y "Reprovado".
Al acceder al botón de registro de pago de la confirmación de matrícula, aparecerá un formulario de registro de pago muy similar al que se hizo en el registro del pago de Inscripción. La única diferencia es que es que cambia el concepto de pago.
Al acceder al botón para confirmar los datos y dar por terminada la confirmación de la matrícula, se confirmarán los datos personales, laborales, etc del estudiante.

**Comment by eadomenech** [comment]
Para este issue sera necesario crear 3 roles. Uno llamado administrador docente, confirmador de matricula y cobrador de matricula.
Para el pago de la confirmacion de la matricula solo tendra acceso el cobrador de matricula.
Para confirmar los datos tendra acceso los roles administrador ddocente y confirmador de matricula, con la siguiente diferencia:
-El confirmador de matricula podra actualizar todos los campos excepto Carrera, Plano academico y Regimen.
-El administrador docente podra modificar todos los campos.

**Comment by ybenitezf** [comment]
En el caso de un estudiante que sea repitende o tenga arrastres la seleción de las materias que se deben repetir o arrastrar quien lo hace ¿el administrador docente o el confirmador de matricula?

**Comment by ybenitezf** [comment]
> Si la carrera seleccionada posee especialidades (en nuestro caso Pedagogia) y el Nivel Académico a confirmar es 3º, 4º o Finalista, entonces se tendrá que seleccionar dicha especialidad de las existentes en esta carrera.

**Pregunta** ¿qué pasa con 5to y 6to?

**Comment by ybenitezf** [comment]
ybenitezf [11:18 AM] 
lo que quiero saber papo es si la compraración la puedo hacer con `nivel > 3ro y carrera.tiene_especialidades() entonces seleccinar_especialidad`

eadomenech [11:20 AM] 
si
