### ISSUE TITLE
Adicionar Especialidad a las carreras

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#250]
Las carreras podrán tener especialidades. En el caso de la UO a la que pertenezco solo tiene especialidades la carrera de Ensino de Pedagogia. Los estudiantes cuando van a confirmar el tercer año, seleccionan la especialidad que harán. Este proceso de selección se realiza en la confirmaciń de la matrícula.
Esto no creo que varíe mucho el código ya implementado, lo que si creo que complica la cosa en los Planes Académicos, aunque se pudiera ver como dos planes distintos aunque los dos primeros años sean iguales.

**Comment by ybenitezf** [comment]
¿Qué es exactamente una especialidad? ¿Qué información se recoge sobre las especialidades?
