### ISSUE TITLE
No pueden existir 2 eventos del mismo tipo como activo

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#254]
Solo puede estar activo un evento de cada tipo. Si existen 2 años académicos con sus respectivos eventos de Inscripción solo podrá estar activo el más reciente.

**Comment by ybenitezf** [comment]
recuerda que aparte de que este marcado como activo o no el evento este solo "esta activo" si la fecha actual se encuentra en el rango de inicio y fin del evento, es decir que aunque este marcado como activo si las fechas no coinciden no esta activo.
