### ISSUE TITLE
Gestionar Campus

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#26]
Para la gestión de los Campus se tienen que introducir los siguientes datos sobre el candidato:
- **Abreviatura** (*): Abreviatura.
- **Nombre** (*): Nombre.
- **Localización** (*): Dirección donde se encuentre el Campus.
- **Disponibilidad** (*): El usuario podrá seleccionar una de las siguientes opciones "Disponible" y "No Disponible".

**Comment by ybenitezf** [comment]
¿los campus no estan o pertenecen a una unidad organica? ¿eso no te da la localización?

**Comment by ybenitezf** [comment]
¿tienes ejemplos para las abreviaturas de estos?

**Comment by eadomenech** [comment]
No necesariamente es así. Acá en algunas escuelas de secundaria se imparten clases. Por ejemplo yo estoy en el Edificio principal y como a 5 cuadras hay una escuela llamada 11 de Noviembre q se dan clases al 1er y 3er año de Ingenieria Civil en las noches. Eso sería un campus y su abreviatura sería 11N. Como a 3 cuadras hay una escuela llamada Ex II Nivel donde se dan clases de Administración y Gestión. Ese sería otro campus con abreviatura IIºN. Esa abreviatura se utiliza para darle luego el nombre a las aulas, por ejemplo la 1 de la 11 de Noviembre se llamaria 11N_01. Y luego a los est se les ubica en las aulas por este nombre 11N_01.

**Comment by ybenitezf** [comment]
entonces en la dirección que escriban lo que sea.

El 23 de abril de 2015, 12:09, Ernesto Avila Domenech <
notifications@github.com> escribió:

> No necesariamente es así. Acá en algunas escuelas de secundaria se
> imparten clases. Por ejemplo yo estoy en el Edificio principal y como a 5
> cuadras hay una escuela llamada 11 de Noviembre q se dan clases al 1er y
> 3er año de Ingenieria Civil en las noches. Eso sería un campus y su
> abreviatura sería 11N. Como a 3 cuadras hay una escuela llamada Ex II Nivel
> donde se dan clases de Administración y Gestión. Ese sería otro campus con
> abreviatura IIºN. Esa abreviatura se utiliza para darle luego el nombre a
> las aulas, por ejemplo la 1 de la 11 de Noviembre se llamaria 11N_01. Y
> luego a los est se les ubica en las aulas por este nombre 11N_01.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yotech/agis/issues/26#issuecomment-95635912.

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
migralo a la nueva forma de gestión
