### ISSUE TITLE
El campo 1 apellido no debe ser obligatorio

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#261]
El campo del 1er apellido no debe ser obligatorio. A la hora de adicionar una persona no hay problema, pero al intentar editarlo o en Seguridad intentar cambiar la contraseña (que a los efectos es editar) no permite cambiar la contraseña señalando que es obligatorio el campo del 1er apellido.

**Comment by eadomenech** [comment]
NO. Aquí el problema es otro. A la hora de adicionar una persona se tienen los campos Nombre, Primer apellido y Segundo apellido; y en Seguridad aparece el campo Apellido. Creo que es ahí donde está el problema.

**Comment by ybenitezf** [comment]
Mira, una cosa son los registros en auth, para crearle un usuario a alguien solo debes ponerle el email en los datos de persona y automaticamente se crea el usuario con los datos de la persona, a la parte de seguridad solo es necesario ir para ponerle la contraseña y/o los grupos a los que pertenecen

**Comment by eadomenech** [comment]
Si, eso fue lo que hice. Pero al cambiar la contraseña, el sistema dice que el campo Apellido es obligatorio y lo tiene vacío.

**Comment by ybenitezf** [comment]
ummm

**Comment by eadomenech** [comment]
Al parecer el problema está en la creación automática del usuario al crear la persona con email.
