### ISSUE TITLE
Problema referente a la situación académica en la confirmación 

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#281]
En el proceso de confirmación de matrícula, si se selecciona la situación académica "Preparação de tessis" y se termina la confirmación, luego se puede apreciar en el evento Epoca Normal que el estudiante posee como "1ª Matrícula-Novo". Lo mismo sucede si en el proceso de confirmación se selecciona otros campos.
Me parece que tiene que ver con el cargar los datos existente en la bd con respecto a este campo.

**Comment by ybenitezf** [comment]
Si puede ser, pero mira una cosa: todos los estudiantes se importaron con situación académica `Aprovado em toda-ano anterior`, exactamente como quedamos notros que lo haríamos. Si después de la confirmación te aparecen con otros valores es porque los que están matriculando se lo cambian y les ponen los que le da la gana.

De todas formas voy a ver como es eso

**Comment by ybenitezf** [comment]
culpa mía, es verdad el problema esta en estaba definición en la tabla `matricula`:

``` python
Field('situacion', 'string', length=1),
```

el parámetro `length` debe ser `2` ya que algunos códigos son mayores que `10`, ahora subo el fix.
