### ISSUE TITLE
Gestionar IES

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#3]
HU: 0002

El sistema debe poder adicionar, modificar y eliminar los IES. Los Institutos de la Enseñanza Superior en Angola pertenecen a una de las Regiones Académicas existentes. Poseen una clasificación con su respectivo código. Universidades (10), Institutos Superiores (20), Institutos Superior Técnicos (21), Institutos Superior Politécnicos (22), Escolas Superior (30), Escolas Superior Técnicas (31), Escola Superior Politécnicas (32), Academias (40) y Centros de Investigação Científica (70). Además tienen una naturaleza, con su respectivo codificación; la misma consiste en Pública (1), Privada (2) y Público-Privada (3). También poseen un código de registro del IES, que está compuesto por todos los códigos antes mencionados y otros 3 en dependencia del registro. Por ejemplo, si la Universidade Kimpa Vita fuese la octava IES a ser registrada en el Ministerio entonces su código seria 07101008 siendo 07 el código de la respectiva Región Académica, 10 o código de clasificación de la IES que en este caso es una Universidad, 1 la naturaleza de la IES en este caso pública y 008 el número secuencial indicando que fuela octava IES a ser registada en el Ministerior. También poseen un logotipo (imagen), la cual se utilizará para todos los documentos generados del sistema. El sistema no generará o asignará código alguno a los IES, los códigos de los IES ya están definidos por el Ministerio. El sistema solo los gestionará

**Comment by eadomenech** [comment]
Los IES también poseen un nombre. Por ejemplo el IES al que pertenezco tiene como nombre Lueji An'konde

**Comment by ybenitezf** [comment]
Si, me imagine eso, cuando termine con la idea que tengo sobre como
implementar la gestión de los IES (#3) te voy a subir los cambios para
que los pruebes, de todas formas en esta parte no hay que complicar
muchos las cosas porque por lo que me parece estos datos se cambian
pocas veces.

El 20/3/15, Ernesto Avila Domenech notifications@github.com escribió:

> Los IES también poseen un nombre. Por ejemplo el IES al que pertenezco tiene
> como nombre Lueji An'konde
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/3#issuecomment-84139468

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
Voy a cerrar este Issue, creo que ya esta completo, el código se calcula de forma automática. Pruebalo.
