### ISSUE TITLE
Problema al Gestionar las Instituciones de Enseñanza Superior

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#31]
Al gestionar las Instituciones de Enseñanza Superior aparece directamente como que se va a adicionar una y no debe ser así. Debe aparecer las IES q existes en la BD y por supuesto permitir adicionar una nueva, modificar y eliminar.
En caso de que el adicionar esté como está ahora, se debe modificar pues no funciona de una manera correcta. En el campo "Name" aparece por defecto "Change this" y si se da adicionar adiciona una nueva IES con el nombre "Change this". Lo mismo ocurre con el campo "Registration Code".

**Comment by ybenitezf** [comment]
No entendiste el cambio, la idea es como se tiene una solo IES por defecto se inicializa con el nombre "Change this" - es solo un texto que le puse. Y no hay adicionar nueva IES, cada vez que se entra el formulario lo que te permite es modificar la que existe en la BD no una nueva. Lo mismo pasa con unidad organica
