### ISSUE TITLE
Modificar listado de candidatos por carrera

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#311]
En la actualidad se lista colocando doble al candidato. Este listado debe modificarse de tal forma que aparezca el candidato solo una vez. Tendría los campos Nº Ins., Nombre completo, Regimen, Carrera en 1ª opción y Carrera en 2ª opción.

**Comment by ybenitezf** [comment]
Pues no la verdad es que no, parece que no entiendes bien el sentido   de esa vista, la idea que es uses los filtros para obtener el listado de candidatos para una carrera, si filtras por carrera veras que los duplicados desaparecen.
