### ISSUE TITLE
Modificar formulario de pago 

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#313]
A la hora de realizar un pago, se dará la posibilidad de hacerlo en varios pagos. Por ejemplo, puede pasar lo siguiente: un estudiante realiza un pago de 4000 al banco y le entregan el correspondiente comprobante, al ir a la universidad a registrar el pago le informan que ya cerró el periodo de confirmación establecido y que ahora debe pagar 10000. Luego el estudiante va otra ves al banco y abona 6000 y le entregan el comprobante. En definitiva el estudiante tendrá 2 comprobantes, uno de 4000 y otro de 6000, en su totalidad serán los 10000 necesarios para confirmar luego del plazo establecido.
Para ello, se deberá realizar una modificación al formulario de pago. Propongo hacerlo de la siguiente manera.
![pago1](https://cloud.githubusercontent.com/assets/11457046/13379993/78a0d1dc-de36-11e5-845f-70c68f83c42e.png)
El formulario será el mismo, solo que se adicionará un botón con el signo "+" al lado izquierdo del campo "Forma de pago". Al dar clic en ese botón aparecerá debajo otros campos (excepto el campo "Código de recibo") similares para poder registrar un pago que ha realizado dividido.
Al dar clic en el botón "Guardar" se comprobará que la suma de los valores de los campos "Valor" sea mayor o igual que la cantidad necesaria para dar por registrado el pago.
Nota importante: 
**1:** La imagen que se adjunta realmente tiene sus problemitas. Al dar clic en el "+" deberá aparecer también un nuevo campo "Forma de pago" (q en la imagen o está, esto es para darle la posibilidad al estudiante de pagar una parte por Banco y otra por la tarjeta).
**2:** El campo "Código de recibo" solo aparecerá una ves (al final), pues independientemente que el estudiante haga pagos separados él lo registrará de una ves y la escuela le entregará un y solo un comprobante de que pagó los 10000.
**3:** Está claro que los botones "+" y "-" deben estar mucho mejor diseñados que como están en la imagen, jajajaja, de veras que no s eme ocurrió otra cosa.

**Comment by ybenitezf** [comment]
Esto solo es para el caso del evento `CONFIRMAÇÃO APÓS O PRAZO` supongo que es donde único se puede dar el caso ¿no?
