### ISSUE TITLE
Filtro por Estado en los resultados por carrera

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#318]
Al presentar un reporte de los resultados en una carrera determinada, y hacer un filtro por Estado, se presentan estudiantes que realmente no están admitidos en esta carrera.
Por ejemplo, si se va a los resultados de la carrera ENSINO DE GEOGRAFIA y se hace un filtro para obtener los estudiantes Admitidos en esta carrera, se presentarán estudiantes que realmente no están admitidos en esta carrera.
El problema vienen dado que el grid busca por el campo Estado. Realmente todos los estudiantes que se presentan están admitidos, mas no todos son admitidos en la carrera en la que se está. 
Si se hace esta consulta es para obtener solo los estudiantes admitidos en la carrera en que se está.

**Comment by ybenitezf** [comment]
Error mio, el filtro de `ESTADO` ahí no se puede aplicar, solo hay que quitarlo de la lista de posibles filtros, otra cosa eso no es un `grid`, parece pero no es.

**Comment by ybenitezf** [comment]
que no va.. que no se puede filtrar joder.
