### ISSUE TITLE
No se está actualizando la N.F. en el campo estudiante.media_acceso

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#326]
El campo media_acceso perteneciente a la tabla estudiante debe actualizarse cada ves que la N.F sea modificada. Es decir, cada ves que se altere alguna nota de un candidato, que altere el valor de la NF perteneciente a la carrera donde ha sido admitido,  se alterará el valor del campo estudiante.media_acceso.
Se tomará como media_acceso a la NF alcanzada en la carrera donde el candidato ha sido admitido.

**Comment by ybenitezf** [comment]
Creo que estas mal interpretando una cosa, el campo `estudiante.media_acceso` es, según la descripción que me diste en matricula y confirmación de matricula la media o nota final con que el estudiante matricula en una carrera ¿me equivoco?

Además eso que quieres hacer no tiene ningún sentido, la N.F se calcula a partir de las notas y se calcula solo durante el proceso de asignación de carreras, si el estudiante es admitido entonces en la tabla `asignacion_carrera` el campo `media` tendrá la NF que se le calculo al estudiante en el proceso de asignación.

**Comment by eadomenech** [comment]
No te equivocas en lo que dices y tienes toda la razón. Ese valor solo se actualiza cuando el estudiante hace la matrícula. Es decir, en el proceso de inscripción cuando el estudiante reclama y demás, la nota final puede variar todo lo que quiera, pero cuando ya está admitido y el estudiante hace la matrícula como tal entonces se toma la NF correspondiente a la carrera que se está matriculando y ese valor es asignado al campo media_acceso en la tabla estudiante. 
Pero lo que está pasando realmente es que al estudiante realizar la matrícula no se está colocando el valor de la NF en e campo media_acceso. Todos en la BD están como None.

**Comment by ybenitezf** [comment]
Ok, eso tiene más sentido.

**Comment by eadomenech** [comment]
Gracias por entenderme al 2º intento, generalmente necesito 6 intentos para lograrlo.
