### ISSUE TITLE
Propina

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#336]
Se define _Propina_ a la cantidad de kwanzas que debe abonar cada estudiante a la institución mensualmente. El pago de la _Propina_ contiene los mismos campos que los otros tipos de pago. (Nombre, Cantidad y Activo). Por defecto el Nombre será "Propina", Cantidad = 15000 y estará Activo. El pago de la propina estará ligado al evento Epoca Normal y podrá ser pagado en cualquier momento.

Para el registro de los pagos de las propinas se tienen en cuenta los siguientes campos:
1.  Persona que realiza el pago.
2. Tipo de pago (Propina)
3. Forma de pago (similar  a la de los demás pagos ya implementados)
4. Número de transacción
5. Transacción
6. Cantidad abonada
7. Código de recibo
8. Fecha de recibo

Si un estudiante paga el último mes de actividades del año y sobra dinero del dinero transferido a la institución, este se tomará como que el estudiante lo ha donado a la institución, no contando para ningún proceso en el futuro.

Existen estudiantes, que por el tipo de bolsa que tengan, están exentos de un por ciento del pago de la propina. 
Los estudiantes que estudian en el periodo Regular están exentos de pagos de propina.

El proceso de pago de propina es de forma siguiente:
**1:** El estudiante paga la cantidad que quiera y las veces que quiera en el Banco. Por cada uno de esos pagos se le entrega un comprobante para poder registrar ese pago en la Universidad.
**2:** Se registra cada pago realizado por los estudiantes. Cada uno por separado y sin esperar a que llegue a completar un mes ni nada por el estilo, sencillamente se registra cada pago con los campos que actualmente utilizamos Nº Transferencia, Transferencia, Fecha, etc. Todos estos pagos con el evento correspondiente q en este caso es Epoca Normal 2016.
**3:** Al registrar cada pago se hace el cálculo siguiente notificando en detalles el estado del estudiante.
**3.1:** Se ordenan los pagos realizados según la fecha en que se hicieron. Los más antiguos primeros.
**3.2:** El sistema intentará realizar el pago de la propina del 1er mes (Marzo). Para ello tomará el valor de los pagos que tengan como fecha menor a 11 de Abril. Si la suma es mayor o igual se da por pago el mes de marzo y se notifica que no hay multa. El sistema intentará pagar entonces el 2do mes (Abril), para ellos tomará todos los valores de los pagos con fecha hasta el 10 de mayo y le restará lo ya consumido en los meses anteriores (en este caso lo del mes de Marzo), si el monto resultante es mayor o igual que lo q se debe pagar por el mes de abril se da por pago la propina del mes de abril se notifica q no hay multa, en caso contrario se toman todos los valores de los pagos en su totalidad descontando lo ya consumido en los meses pagados anteriormente y se comprueba q ese monto sea mayor o igual q la propina + la multa del mes que se quiera pagar (en este Abril), si es así se da por pago y se notifica la multa impuesta, en caso contrario no procede el pago y queda en deuda la propina del mes de Abril. Intentará pagar el 3er mes ....

Ejemplo:
**1:** Supongamos que el pago de la propina de un mes es de 15000 y la multa es del 10%.
**2:** El estudiante E va a la escuela y registra un pago P1 de 10000 kz.
**3:** Acabando de registrar ese pago el sistema se ordenan los pagos, como solo hay uno (P1) no hay que hacer nada.
**4:** El sistema intentará realizar el pago de la propina del 1er mes (Marzo). Para ello tomará el valor de los pagos que tengan como fecha menor a 11 de Abril (El P1 se hizo el 14-03). La suma no es mayor o igual q 15000 por lo que se toman todos los valores de los pagos en su totalidad descontando lo ya consumido en los meses pagados anteriormente (lo mismo, como solo hay un pago y no se ha pago meses anteriores seria lo mismo) y se comprueba q ese monto sea mayor o igual q la propina + la multa del mes que se quiera pagar (15000+1500=16500), como no procede el pago queda en deuda la propina del mes de Marzo.
**5:** El estudiante registra otro pago de 5000 kz con fecha 20-03.
**6:** El sistema intentará realizar el pago de la propina del 1er mes (Marzo). Para ello tomará el valor de los pagos que tengan como fecha menor a 11 de Abril (Se toman los pagos P1 y P2, ambos se hicieron antes del 11 de Abril). La suma es mayor o igual q 15000 por lo q se da por pago el mes de Marzo y se notifica que no hay multa. El sistema intentará pagar entonces el 2do mes (Abril), para ellos tomará todos los valores de los pagos con fecha hasta el 10 de Mayo y le restará lo ya consumido en los meses anteriores (en este caso lo del mes de Marzo, se queda en 0), el monto resultante no es mayor o igual que lo q se debe pagar por el mes de Abril por lo q se toman todos los valores de los pagos en su totalidad descontando lo ya consumido en los meses pagados anteriormente y se comprueba q ese monto sea mayor o igual q la propina + la multa del mes que se quiera pagar (en este Abril), al no proceder se queda en deuda la propina del mes de Abril. Fin.

**Comment by ybenitezf** [comment]
La primera pregunta seria relacionada con el UI. Creo que, aunque este tipo de pagos no esta relacionado con ningún _evento_ en particular, se puede poner dentro de la sección relacionada al evento `Época normal`.

Más concretamente, creo que debería ser uno de los enlaces que aparezcan al lado de cada uno de los estudiantes en `Época normal`.

**Comment by ybenitezf** [comment]
Testing la respuesta por email.

El 25/3/16, Ernesto Avila Domenech notifications@github.com escribió:

> Se define "Propina" a la cantidad de kwanzas que debe abonar cada estudiante
> a la institución mensualmente.
> El tipo de pago "Propina" contiene los mismos campos que los otros tipos de
> pago. (Nombre, Cantidad y Activo)
> Por defecto el Nombre será "Propina", Cantidad = 15000 y estará Activo.
> El pago de la propina no está ligado a un evento determinado, es decir,
> puede ser pagado en cualquier momento.
> Para el registro de los pagos de las propinas se tienen en cuenta los
> siguientes campos:
> **1:** Persona que realiza el pago.
> **2:** Tipo de pago (Propina)
> **3:** Forma de pago (similar  a la de los demás pagos ya implementados)
> **4:** Número de transacción
> **5:** Transacción
> **6:** Cantidad abonada
> **7:** Código de recibo
> **8:** Fecha de recibo
> **9:** Año-Mes Inicio (posee formato YYYY-MM e indica el 1er mes que se
> paga)
> **10:** Año-Mes Fin (posee formato YYYY-MM e indica el último mes que se
> paga)
> 
> Los campos 9 y 10 son campos que contendrá el inicio y fin del periodo que
> se está pagando. Es decir, un estudiante que ahora a inicio del año pague
> 30000 kz, siendo el valor del campo Cantidad=15000, estaría pagando 2 meses.
> Como por defecto el año tiene activo todos los meses desde Marzo hasta
> Diciembre, el estudiante estaría pagando Marzo y Abril, por lo que se
> asignará el valor 2016-03 al campo Año-Mes Inicio y el valor 2016-04 al
> campo Año-Mes Fin, ambos correspondiente al registro del pago realizado.
> Si el estudiante registrara otro pago de propina pero esta ves de 15000 kz,
> los campos Año-Mes Inicio y Año-Mes Fin correspondiente a este otro registro
> de pago, serian iguales = 2016-05. Significando que el estudiante solo pagó
> Mayo
> Suponiendo que el mes 06 del año presente no hayan actividades presenciales
> Profesor-Estudiante, este mes no se tendrá en cuenta para el pago de la
> propina, por lo que si el estudiante realiza otro pago de un mes será
> atribuido al Año-Mes 2016-07.
> Si un estudiante paga el último mes de actividades del año y sobre dinero
> del dinero transferido a la institución, este se tomará como que el
> estudiante o dona a la institución, no contando para ningún proceso en el
> futuro.
> Existen estudiantes, que por el tipo de bolsa que tengan, están exentos de
> pagos de propina.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/336

## 

Yoel Benítez Fonseca
http://redevil.cubava.cu/
$ python -c "import this"

**Comment by eadomenech** [comment]
Testing with aqua

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 25 de marzo de 2016 7:47:26 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

> Testing la respuesta por email.
>

**Comment by eadomenech** [comment]
Cuando comienza un ano academico y el estudiante debe confirmar la matricula, este, antes de confirmar debe pagar las deudas de propina de los meses del ano anterior. 
El estudiante va a confirmar, se le informa q tiene deudas de meses anteriores y debe pagarlas primero. Como va a pagar las deudas si no ha confirmado y no aparece por tanto en epoca normal??.
Me imagino q lo q pensaste gue dejar los eventos de epoca normal abiertos en todos los anos academicos. Es deccir, si tiene deudas habria q ir a 2015 en epoca normal y pagar las propinas de ese ano. Pero no es lo q tenia pensado. Lo q pienso es q si se acaba el 2015 entonces todos los eventos del 2015 se cierran.

**Comment by ybenitezf** [comment]
Para aclararte: que la fecha _final_ de un evento haya pasado no quiere decir que no se puedan realizar operaciones en ese evento. Las fechas lo que nos das es la posibilidad de poner o no determinadas restricciones a las cosas que se pueden hacer.

Que el año académico ya haya pasado no quiere decir que no se pueda acceder a este y más concretamente registrar los pagos atrasados de los estudiantes.

En cuando al proceso que debe seguir un estudiante para pasar de un año a otro sigue siendo un misterio para mi, pero sospecho que el campo `Estado en la UO` [de la parte de matrícula](https://github.com/yotech/agis/wiki/Matr%C3%ADcula-y-Confirmaci%C3%B3n-de-Matr%C3%ADcula) (le hice una página en la wiki) tiene mucho que ver, es decir supongo que la parte de `SIN MATRICULAR CON DEUDA` tenga que ver con los pagos de `Propina` ¿no?. 

A lo que quiero llegar es a ¿como se sabe si un estudiante tiene deudas o no? ¿el número de meses que se debe pagar o los meses en si en que se realizan esos pagos es diferente cada año?

**Comment by eadomenech** [comment]
Ya tengo la idea de como hacer la funcionalidad de los pagos de propina. La 
estoy escribiendo para subirlq cuanto antes. De todas formas te respondo 
tus preguntas.
El estado Matriculado con deudas es para clasificar de cierta forma a los 
estudiantes q se han matriculado pero q tienen deuda de propinas.
En cuanto a la forma de pasar de un ano para otro, en teoria, un estudiante 
no debe confirmar si tiene deudas de propina del ano anterior, pero en la 
practica los jefes autorizan determinados casos. Eso significa q deben 
poder confirmar pero de cierta manera hay q marcaflos con algo para llevar 
el control de q tienen deudas.
Un estudiante tiene deudas si debe al menos un mes de propina. Se debera 
conocer si cada estudiante tiene deuda o no (eso es con los estados en la 
uo) y en caso de tener deuda hay q conocer la cantidad d meses y cuales son.
 En cada ano academico pueden existir algunos meses q no se de clases por 
determinados motivos, en esos meses no se debera pagar propina. Lo normal 
es q se de clases los meses de Marzo a Diciembre.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 28 de marzo de 2016 2:22:28 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Bueno, espero tengas en cuenta lo que te explique de los eventos, es perfectamente posible realizar los pagos en la misma UI del evento época normal del año académico pasado, así no tenemos que reinventar la rueda.

Ahora en cuanto al pago en si. Mira esos 2 campos que pides agregar, así como los describiste van a ser un dolor de cabeza a la hora de hacer consultas, además implica agregar 2 campos más a una tabla que ya tiene registros, en cuanto a esto ultimo te propongo hacerle una extensión a la  tabla de pagos - como si fuera un subtipo:

`pago_propina`(_CAMPOS_NUEVOS_) ------------> `pago` (_campos_que_ya_tenemos_)

Lo que hay que definir bien es que campos vamos a agregar, no creo que eso de año-mes funcione, para eso mejor usamos la fecha completa aunque no importe el día.

**Comment by eadomenech** [comment]
Coincido contigo pero lo que no se quiere es que se identifique los meses que se está pagando directamente. Me explico. La interfaz de pago solo recogerá los datos de pagos que escribí en la historia, de acuerdo al dinero que se abone el sistema informará los meses que se pagarán con ese dinero abonado (esto es en forma de pedido de confirmación) para luego dar por concluido el registro del pago. No seguiré explicando con detalles pues creo que se explica en el issue que estoy escribiendo ahora.
En cuanto a la extensión concuerdo contigo al igual que con la utilización de la fecha completa aunque no utilicemos el día.
En unos minutos subo el issue sobre la propuesta que te estoy haciendo para la funcionalidad pago de propina.

**Comment by ybenitezf** [comment]
¿y porque no editaste este mismo issue en ves de crear uno nuevo? tas de madre.

**Comment by eadomenech** [comment]
Porque este es solo la historia y los otros issue tienen que ver con
las funcionalidades que responden a esta historia.

2016-03-28 15:10 GMT+01:00, Yoel Benítez Fonseca notifications@github.com:

> ¿y porque no editaste este mismo issue en ves de crear uno nuevo? tas de
> madre.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/336#issuecomment-202408157

## 

Saludos,
  Ernesto.
