### ISSUE TITLE
Agregar meses a los Años Académicos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#337]
Cuando se agrega un año académico se le asignarán los meses de Enero hasta Diciembre, estando activos los meses de Marzo a Diciembre. Los administradores podrán poner activo o NO a cada uno de os meses.

Los meses activos significarán los meses que habrá actividad presencial Profesor-Estudiante, por lo que los alumnos deberán pagar la propina correspondiente.

En el menú de cada año académico, además de los eventos aparecerá la opción de configurar el año académico como tal, es ahí donde se configurarán los meses activos del año académico.

![20160326_163148](https://cloud.githubusercontent.com/assets/11457046/14060851/1613f2ce-f371-11e5-8c2e-0227428c498b.jpg)

![20160326_163406](https://cloud.githubusercontent.com/assets/11457046/14060857/20e155de-f371-11e5-804f-83f15fa6e50b.jpg)

**Comment by ybenitezf** [comment]
¿esto es solo por lo de los pagos de propina?

**Comment by eadomenech** [comment]
Por el momento si.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 28 de marzo de 2016 2:24:15 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
¿Se te ha ocurrido algo más en lo que podamos usar lo meses estos que vamos a asociar a los años académicos?

**Comment by eadomenech** [comment]
Por el momento no se me ocurre en q mas utilizarlo.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 4 de abril de 2016 7:18:04 PM Yoel Benítez Fonseca 
notifications@github.com escribio:
