### ISSUE TITLE
¿otros eventos?

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#338]
¿Qué otros eventos tendríamos? De momento tenemos:
- Inscripción: proceso de captación de estudiantes.
- Matricula: para los aceptados en el proceso de inscripción.
- Confirmación de matrícula: para los estudiante continuantes.
- Confirmación después del plazo: para los estudiantes que se han rezagado en el anterior
- Época normal: proceso docente normal.

**Comment by eadomenech** [comment]
Esto es algo q discutiremos luego. Hay cosas q no las tengo claras y debo 
informarme, pero hay otras q debo discutirlas contigo. Te pongo ejemplos.
Las pruebas parciales las tenia pensada como evento. Es decir, las datas de 
inicio y fin estan establecidas por la rectoria, esto seria un evento con 
su data de inicio y data fin, con eso limitariamos la data fin al profesor 
para atribuir la nota (15 dias despues de terminar la epoca de examen). 
Ahora, lo q discutiriamos es como hacer todo ese negocio de una mejor manera.
Otro caso es el evento Graduacion. En este evento se escojeria de los est 
matriculados q sean finalistas los q ya defendieran con exito y se pasaria 
a graduado. Ya esos no tendrian q confirmar mas ningun otro ano  ni 
deberian pagar propina.
Creo no deberiamos meternos en esto todavia. Solo te lo escribo para dar 
respuesta a las preguntas q me haces.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 28 de marzo de 2016 2:33:21 PM Yoel Benítez Fonseca 
notifications@github.com escribio:
