### ISSUE TITLE
Registra pago de propina

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#339]
El pago de la _propina_ podrá hacerse en durante el evento `época normal` del año actual o de los años académicos precedentes.

El registro del pago de _propina_ se hará desde el registro de estudiantes en el evento `época normal`.

![propina1](https://cloud.githubusercontent.com/assets/11457046/14079883/17701f7e-f4f9-11e5-8080-2a762df5d9ae.png)

Encima del formulario para introducir el pago se debe mostrar el informe de los meses pagados por el estudiante.

![confirmar pago de propina](https://cloud.githubusercontent.com/assets/11457046/14080475/5321a412-f4fd-11e5-8bda-4923b69336df.png)

Debajo aparecerá un formulario para registrar el pago de _propina_.

![pago propina](https://cloud.githubusercontent.com/assets/11457046/14080494/6ed5c63e-f4fd-11e5-9941-244ebcbd8810.png)

Un vez se introduzca un pago el el informe de los meses pagados debe actualizarse y el formulario reiniciarse para permitir otros pagos.

El dinero que reste del pago realizado no se tendra en cuenta. Si un estudiante hace un pago de 16000 kz, se le notificara que ha sido pago un mes y se almacenera el valor de 15000 kz como entrada a la cuenta de la escuela.

Se tendra en cuenta que luego de pasar cada mes se adicionara un 10% de multa. Ejemplo, el estudiante comienza a dar aulas en marzo, lo que debera pagar la propina del mes de marzo antes del 11 de abril. A partir del 11 de abril tendra que pagar los 15000 de propina + 1500 de multa por demorar ese tiempo. En caso de que llegue el 11 de mayo y no haya pago nada entonces debera a la escuela 15000 del mes de marzo + 15000 del mes de abril + 3000  de multa por tener 2 meses de atraso de la propina correspondiente al mes de marzo + 1500 de multa por tener atraso 1 mes del mes de abril.
Ojo, para no trabajar doble creo q es necesario crear un campo al pago propina "% multa" que por defecto sera 10, eso significa que cada mes q el estudiante se atrase debera adicionarse a la deuda un 10% de la propina correspondiente a ese mes.

**Comment by ybenitezf** [comment]
Revisa de nuevo lo que escribiste !!!

**Comment by eadomenech** [comment]
Q ves mal q yo no veo?

**Comment by ybenitezf** [comment]
Mira a ver si estas de acuerdo con los cambios que le hice.

**Comment by eadomenech** [comment]
Socio borraste lo otro que había escrito. Fue con toda intención o un accidente???
Así como lo escribiste está aceptable. Solo faltan algunos detalles. Por ejemplo, la intención es que cuando se coloque la cantidad de dinero que se está pagando y se da clic en el botón Guardar, se señalen los meses que quedarían pago si se confirma ese pago. Además se mostraría la cantidad que se abonaría a la UO en caso de que el dinero exceda del pago de esos meses. Luego de ver los meses que quedarían pago, se daría en otro botón "Registrar pago" para dar por terminado el registro del pago de propina.
Lo otro es que en un mismo registro de pago puede pagarse con varios pagos, algo parecido a lo que hicimos en confirmación después del plazo.
Ejemplo: Un estudiante tiene pago Marzo y va a registrar un pago para Propina de 40000 kz, siendo el valor para cada mes 15000 kz. En ese caso, aparecería marcado el mes de Marzo como información de que ese mes ya ha sido pago. Luego de llenar los campos correspondiente al pago y dar en el botón Guardar se informaría que con ese pago quedaría pagos los meses Abril y Mayo y se donaría a la institución un monto de 10000 kz. Ahí el estudiante podría ir al banco y realizar otro deposito de 5000 kz. Al poder registrar otra transacción en el mismo formulario, el sistema informaría que quedarían pago los meses de Abril, Mayo y Junio y se donaría a la UO un monto de 0 kz. Luego de eso se pasaría a dar clic en el botón "Registrar pago" y es aquí donde se procesaría el registro de pago.

**Comment by ybenitezf** [comment]
## 

Yoel Benítez Fonseca
http://redevil.cubava.cu/
$ python -c "import this"
El mar 28, 2016 1:50 PM, "Ernesto Avila Domenech" notifications@github.com
escribió:

> Socio borraste lo otro que había escrito. Fue con toda intención o un
> accidente???

No había mucho más.. solo quite lo ambiguo o que no entendía, te dije que
lo revisaras y dijiste no hacía falta arreglar nada. Estas de madre.

> Así como lo escribiste está aceptable. Solo faltan algunos detalles. Por
> ejemplo, la intención es que cuando se coloque la cantidad de dinero que se
> está pagando y se da clic en el botón Guardar, se señalen los meses que
> quedarían pago si se confirma ese pago. Además se mostraría la cantidad que
> se abonaría a la UO en caso de que el dinero exceda del pago de esos meses.
> Luego de ver los meses que quedarían pago, se daría en otro botón
> "Registrar pago" para dar por terminado el registro del pago de propina.

Que forma de complicarse la vida.. vere que hago.

> Lo otro es que en un mismo registro de pago puede pagarse con varios
> pagos, algo parecido a lo que hicimos en confirmación después del plazo.

Eso me temia.

> Ejemplo: Un estudiante tiene pago Marzo y va a registrar un pago para
> Propina de 40000 kz, siendo el valor para cada mes 15000 kz. En ese caso,
> aparecería marcado el mes de Marzo como información de que ese mes ya ha
> sido pago. Luego de llenar los campos correspondiente al pago y dar en el
> botón Guardar se informaría que con ese pago quedaría pagos los meses Abril
> y Mayo y se donaría a la institución un monto de 10000 kz. Ahí el
> estudiante podría ir al banco y realizar otro deposito de 5000 kz. Al poder
> registrar otra transacción en el mismo formulario, el sistema informaría
> que quedarían pago los meses de Abril, Mayo y Junio y se donaría a la UO un
> monto de 0 kz. Luego de eso se pasaría a dar clic en el botón "Registrar
> pago" y es aquí donde se procesaría el registro de pago.

:-(

**Comment by ybenitezf** [comment]
¿Donde se establecerá el valor a pagar para cada mes? ¿en el tipo de pago?

Entonces los meces que haya que pagar tentativamente se pondrán en la configuración del año académico ahora te pregunto ¿como afectan los cambios de esos meses a los pagos y a la información que dependen de estos? Supón que se haya definido Abril como un mes a pagar y después en Mayo alguien se dio cuenta que no se realizó ningún encuentro en ese mes (aunque se efectuaron pagos para Abril) y quita Abril de la configuración del año, por poner un ejemplo.

**Comment by ybenitezf** [comment]
Aquí hay preguntas por contestar, además supongo que se page un poco más de un mes y no suficiente para 2, es decir que queda una cierta cantidad de $ para la UO, ¿en que forma guardo ese $, es decir que sería una especie de pago, de que tipo?

**Comment by eadomenech** [comment]
Eso mismo lo estuve viendo hoy y tambien me entere de algo q no sabia. 
Manana lo subo detalladamente explicado. La cosa es q cuando pasa un x 
tiempo se le agrega un interes, es decir, si llega el 10 de mayo y el 
estudiante no ha pago abril, entonces el estudiante debera pagar los 15000 
de abril mas un 10% por lo q tendria q pagar 16500. Eso lo estoy redactando 
haciendo un levantamiento en la escuela.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 18 de abril de 2016 4:24:18 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Yo no comienzo a meterle mano a eso hasta que no este completa la historia...

**Comment by eadomenech** [comment]
OK. Mañana estará completa.

2016-04-18 17:07 GMT+01:00, Yoel Benítez Fonseca notifications@github.com:

> Yo no comienzo a meterle mano a eso hasta que no este completa la
> historia...
> 
> ---
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/339#issuecomment-211448359

## 

Saludos,
  Ernesto.

**Comment by eadomenech** [comment]
Actualice la descricion. Pregunta lo q quieras.

**Comment by ybenitezf** [comment]
Por lo que veo, a parte de lo meses en los que hay que pagar, es necesario adicionar un campo para especificar el % de multa por retrasos y otro campo en que se pueda especificar a partir de que día del mes se comienza a aplicar esa multa. ¿correcto?

**Comment by eadomenech** [comment]
Correcto.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 20 de abril de 2016 1:57:12 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Pregunta:

¿el requisito mínimo para hacer un pago de propina es que al menos alcance para pagar 1 mes? ¿no? ¿quiero decir si el muchacho va con el $ para medio mes no se lo reciben verdad?

**Comment by ybenitezf** [comment]
Pregunta:

¿el requisito mínimo para hacer un pago de propina es que al menos alcance para pagar 1 mes? ¿no? ¿quiero decir si el muchacho va con el $ para medio mes no se lo reciben verdad?
