### ISSUE TITLE
En la gestión de Personas el campo Natural no debe ser un texto

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#34]
En la gestión de Personas el campo Natural debe ser igual que el del municipio de residencia. En los reportes que hay que entregar viene este campo. Los municipios tienen un código de 6 dígitos y este código es el que va en el reporte. Por defecto estarán los municipios de Angola de cada una de las provincias (esto lo haré yo). 
En caso de que la persona sea de un municipio que no pertenezca a Angola lo pondremos como "Otro" y tendrá el código 999999.  Por el momento no gestionaremos todos los países, provincias y municipios.

**Comment by ybenitezf** [comment]
me sigue pareciendo mejor dejarlo como un edit, hasta ver que se hace depues... además si en reporte hace falta poner el natural y este va a ser = el municipio donde recide es mejor entonces incluir directamente en el reporte el municipio donde vive.

**Comment by eadomenech** [comment]
No. El campo natural va ser como el municipio d residencia pero además va
tener otro ítem llamado "Extranjero" Ese Extranjero tendrá como código
00000.

**Comment by ybenitezf** [comment]
joder loco, que complicasión por no querer meter un puto edit.... y todavía
no entiendo, que hago con natural? lo cogemos como el municipio donde vive
? a ver si eres angolano el campo narutal debería ser normalmente el
municipio donde naces y no el de donde estas viviendo ¿en ese caso? en
cuanto a los extrangeros tendría que agregar otra cosa a la lista de
posibles valores ?

El 22 de abril de 2015, 12:58, Ernesto Avila Domenech <
notifications@github.com> escribió:

> No. El campo natural va ser como el municipio d residencia pero además va
> tener otro ítem llamado "Extranjero" Ese Extranjero tendrá como código
> 00000.
> El 21/04/2015 14:24, "Yoel Benítez Fonseca" notifications@github.com
> escribió:
> 
> > me sigue pareciendo mejor dejarlo como un edit, hasta ver que se hace
> > depues... además si en reporte hace falta poner el natural y este va a
> > ser
> > = el municipio donde recide es mejor entonces incluir directamente en el
> > reporte el municipio donde vive.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/yotech/agis/issues/34#issuecomment-94792856.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yotech/agis/issues/34#issuecomment-95263790.

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by eadomenech** [comment]
Closed
