### ISSUE TITLE
Error al realizar pago de Propina 

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#346]
<type 'exceptions.ValueError'> Currency formatting is not possible using the 'C' locale.

 if digits == 127:
raise ValueError("Currency formatting is not possible using "

**Comment by ybenitezf** [comment]
¿Donde estas probando que te dio el error ese? Quiero decir en que maquina y de que manera lo estas haciendo... a ver este error tiene que ver con un sistema mal configurado donde no se ha establecido el idioma.

También sería buena idea que me pongas la salida completa del error.

**Comment by ybenitezf** [comment]
Solo para que quede registro de esto:

El problema es que apache por defecto no activa las configuración del lenguage para Python, por eso es necesario cambiar la configuración del sitio en apache y establecer el lenguaje:

`WSGIDaemonProcess web2py user=www-data group=www-data lang='en_US.UTF-8' locale='en_US.UTF-8'`
