### ISSUE TITLE
Asignar Estado Matriculado con Deudas

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#348]
Todo estudiante matriculado que tenga como mínimo un mes de atraso en el pago de la propina se considerará Matricula con Deuda y se le actualizará el estado.

**Comment by ybenitezf** [comment]
Esta es la pregunta que yo te hice hace algún tiempo, de que manera será esto ? ¿de forma automática o tendrá alguien que cambiarlo? si es de forma automática, habrá que hacer algunas cosas en el servidor.

**Comment by eadomenech** [comment]
Automatica. Me diras q hay q hacer en el server.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 22 de abril de 2016 8:03:13 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Básicamente configurar un cron para que se ejecute cada cierto tiempo... no te preocupes te pasare las instrucciones.

**Comment by eadomenech** [comment]
Se debe tener en cuenta que los estudiantes que estudian en el régimen Regular no pagan propina.
