### ISSUE TITLE
Añadir rol Cobrador de Matrícula

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#352]
Se deberá añadir el rol para la funcionalidad Propina.

**Comment by ybenitezf** [comment]
¿Y como se va a llamar el rol? ¿cobrador de propinas? ¿cobrador de matricula? estas de leña me tienes contento..

**Comment by ybenitezf** [comment]
pero ni te preocupes por eso que hay que re-implementar toda la historia.

**Comment by eadomenech** [comment]
Cobrador de Propina

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 28 de abril de 2016 9:46:29 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by eadomenech** [comment]
Entonces crees q es mejor no empezar a cobrar propina por el sistema?

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 28 de abril de 2016 9:49:31 PM Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
Lo que te digo es que si no lo estabas usando todavía entonce no
comiences hasta que nos e arregle todo eso, porque sino los pagos no
van a coincidir.

2016-04-28 16:58 GMT-04:00, Ernesto Avila Domenech notifications@github.com:

> Entonces crees q es mejor no empezar a cobrar propina por el sistema?
> 
> Enviado con Aquamail para Android
> http://www.aqua-mail.com
> 
> El 28 de abril de 2016 9:49:31 PM Yoel Benítez Fonseca
> notifications@github.com escribio:
> 
> > pero ni te preocupes por eso que hay que re-implementar toda la historia.
> > 
> > ---
> > 
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/yotech/agis/issues/352#issuecomment-215556438
> 
> ---
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/352#issuecomment-215560373

## 

Yoel Benítez Fonseca
http://redevil.cubava.cu/
$ python -c "import this"
