### ISSUE TITLE
Permitir varos pagos para un registro de propina

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#353]
A la hora de registrar pagos hechos para cumplir con la propina, es necesario q el sistema permita aceptar varios pagos y luego la suma de esas cantidades es lo que se tomaria como pago y se notificaria cuantos meses se pagan con ese monto.
Está pasando de que hay estudiantes q pagan 15000 al banco sin tener en cuenta la multa y cuando se va a registrar en el sistema como no llega a 16500 el sistema toma a esos 15000 como donación. Es no debe ser asi.
Lo q se hace en ese caso es decirle al est q haga otro pago de 1500 y entonces el sistema tendrá q aceptar un registro pero con 2 trasacciones, la suma de las 2 serian los 16500 y se daria por pago el mes q se queria pagar.

**Comment by ybenitezf** [comment]
Ah y tu no revisaste eso, y no te diste cuenta, man toda la lógica de lo que hice reside en un solo pago con el que se pagan varias propinas o al menos una no al contrario ... y tu lo revisaste. Dan ganas de dejarlo así mismo y no hacer nada.

**Comment by eadomenech** [comment]
A ver Yoe, analiza lo q te propongo. Te propongo hacer esta funcionalidad 
de la siguiente manera. Se podran hacer tantos pagos como el estudiante 
quiera. Cada registro de pago tendra solo un pago como esta hecho ahora 
mismo. Ahora, el sistema serq capaz de sumar todos los pagos d cada est y q 
sean de este tipo (epoca normal 2016) y teniendo esta cantidad total sera 
capaz de informar hasta q mes se tiene pago la propina. Esto ultimo se hara 
lo mas detallado posible para dar informacion exacta a los estudiantes.
Voy a poner un ejemplo. Existe un estudiante E q hizo los pagos P1, P2, P3 
y P4, de cantidades 15000 , 3000 , 15000 y 3000 respectivamente, en las 
fechas 2016-04-11, 2016-04-14 , 2016-04-20 y 2016-04-28 respectivamente.
Suponiendo q el valor de la propina sea 15000 y la multa sea del 10%, el 
sistema reaccionaria de la siguiente forma.
Los 4 pagos se registrarian de forma separada y de la misma forma en que 
esta hasta ahora, solo q no se relacionara con un mes determinado, 
sencillamente se registran como pagos de propina en la epoca normal del ano 
academico 2016.
Al ir a registrar el pago P1, se informara a la derecha de q el estudiante 
debe todos los meses del ano academico, se mostrara como especie de una 
tabla de cant_meses_activos X  3, donde las filas son los nombres de los 
meses donde se paga propina y las 3 columnas son "Propina", "Multa" y 
Estado("Com Dividas" o "Pago"). En este momento aparecera 0 en todo y con 
el Estado "Com Dividas" en todos los meses.
Al terminar de registrar el pago P1 aparecera el valor 15000 en la 
interseccion de la fila Marzo con la columna "Propina" y 0 en todas las 
demas celdas y se mantendra como Estado "Com divida" en todos los meses.
Al registrar el pago P2 aparecera el valor 1500 en la interseccion de la 
fila Marzo con la columna Multa y pasara el Estado de la fila Marzo a 
"Pago", tambien aparecera 1500 en la interseccion de la fila Abril con la 
columna Propina y lo otro se mantendra igual.
Al registrarse el pago P3 aparecera ennla interseccion de la fila Abril con 
la columna Propina el valor de 15000 y el Estado correspondiente a la fila 
Abril pasara a "Pago". Tambien aparecera el valor 1500 en la interseccion 
Mayo con la columna Propina. Todo lo demas seguira igual.
Al registrar el pago P4 aparecera en la intersecciin de Mayo con Propina el 
valor de 4500 y todo lo demas estara igual.
Es decir, los pagos se registran de forma independiente. El sistema conoce 
la cantidad total abonada. Se van pagando las propinas segun se pueda, 
teniendo en cuenta la fechas en q se hicieron los pagos para determinar se 
hay multa o no. Se actualiza el estado para darlo como informacion.
Esto es solo una propuesta. Aqui hay q tener en cuenta q necesitaremos un 
listado donde esten todos los estudiantes, si tienen deudas o no de 
propina, cantidad de meses q tienen deuda,  cantidad de dinero q han pago 
en total y la cantidad de dinero q les restaria pagar para pagar las 
propinas de los restantes mese q le quedan x pagar.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 28 de abril de 2016 9:45:30 PM Yoel Benítez Fonseca 
notifications@github.com escribio:
