### ISSUE TITLE
Configurar en el sistema el número de expediente de los candidatos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#36]
Cada candidato tiene un número de expediente en cada uno de los años que se candidata. Este número posee 4 dígitos y corresponde al orden de inserción de los candidatos a los exámenes de acceso.

**Comment by ybenitezf** [comment]
¿y como se sabrá en que orden los candidatos son insertados en los examenes de acceso? ¿no habiamos quedado en que era "el orden en que los candidatos son registrados en el sistema"? ¿y pq tiene que cambiar con los años?

**Comment by eadomenech** [comment]
El orden se da cuando se convierte en candidato inscripto (es decir cuando paga). En ese momento se le asigna el número de expediente. Por supuesto este número es auto-incremental y se reinicia cuando se cambia de año académico.

**Comment by ybenitezf** [comment]
esto del número de expediente del canditado no me queda claro, ¿se lo vamos a asignar cuando cuando se convierta en inscrito, eso ya lo aclaramos, ahora de que forma vamos a pasarlos de con deuda a inscritos ?  merefiero de forma funcional, es decir, como crees que se deba hacer eso en el sistema.

**Comment by eadomenech** [comment]
Una ves que pague, se convierte en estudiante candidato inscripto. Se le asigna el número de expediente y se cambio a estado "candidato inscripto".
