### ISSUE TITLE
Registrar pagamento de Inscripción

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#39]
Para realizar un pagamento se procede de la siguiente manera:
- **Se escogerá el tipo de pagamento que se desea realizar** (*): Solo aparecerán los tipos de pagametos que tengan como nombre igual a un tipo de evento activo. Por ejemplo: Saldrá el tipo de pagamento "Inscripción" si existe un evento de tipo "Inscripción" en activo y se está dentro de las fechas de inicio y fin de este último.
- **Estudiante** (*): Saldrá una lista de estudiantes que cumplan las condiciones para realizar el tipo de pagamento anteriormente seleccionado; en dicha lista aparecerán los campos "Documento de identidad", "Nombre", "Primer apellido" y "Segundo apellido". La lista será un "grid" y se permitirá realizar búsquedas y consultas utilizando las potencialidades del componente. Además, cada estudiante tendrá en la parte derecha un vínculo llamado "Registrar pago".

Un ejemplo sería: Si se selecciona el tipo de pagamento "Inscripción" solo aparecerán en la lista los estudiantes con estado "Inscripto con deuda" y que hayan realizado inscripción en el año en que se está. Luego de localizar al estudiante a registrar el pago, mediante búsquedas o consultas, se dará clic en el vínculo "Registrar pago" que tendrá el estudiante a la derecha.

Una vez en Registrar pago, se introducirán los siguientes campos:   
- **Cantidad abonada** (*): Cantidad abonada por el candidato, según el comprobante de pago.
- **Forma de pago** (*): Se debe escoger la forma de pago que realizó el candidato. Por el momento pueden ser 2, mediante un pago directo en el banco o mediante un terminal de lectura magnética para tarjetas de créditos. 
- **Número de transacción** (*) : En caso de haberse pagado directamente en un banco, el comprobante de pago, dado por el banco a la persona que abonó, posee el número de la transacción. En caso de haberse pagado mediante un terminal de lectura magnética para tarjetas de créditos perteneciente a la UO, se tomaría como número de transacción la hora y fecha de realización de la misma; esta hora y fecha está en el comprobante (papel) otorgado por el terminal. 
- **Número de recibo** (*): La UO posee una serie de hojas que se entregan como prueba de recibo. La UO se queda con una copia y se le entrega una a la persona que abona. Estos comprobantes de recibo poseen una numeración.

En caso de realizar el pago de forma satisfactoria, siendo el tipo de pagamento = "Inscripción", el estudiante pasará al estado "Inscripto" y se le asignará a dicho estudiante un número; este número es el número de inscripción. Estos números son incrementales y corresponde con el orden en que hicieron el pagamento.

De la información anterior todo lo marcado con (*) es de carácter obligatoria.
A esta funcionalidad se podrá acceder desde Contabilidad->Registrar Pagamento

**Comment by ybenitezf** [comment]
¿en que parte acordamos poner esto en el menú?

**Comment by eadomenech** [comment]
En contabilidad

**Comment by ybenitezf** [comment]
me asombra el lujo de detalles, ¿en contabilidad->pagos->pago de inscripción ?

El 30/6/15, Ernesto Avila Domenech notifications@github.com escribió:

> En contabilidad
> 
> Yoel Benítez Fonseca notifications@github.com escribió:
> 
> > ¿enqueparteacordamosponerestoenelmenú?ReplytothisemaildirectlyorviewitonGitHub.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/39#issuecomment-117248129

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
Si es gestión de pago de inscripción supongo yo sea diferente de otros pagos, dime como seria el proceder, especificamente para este caso

**Comment by ybenitezf** [comment]
veo un poco floja esta parte: 
- **Se escogerá el tipo de pagamento que se desea realizar** (*): Solo aparecerán los tipos de pagametos que tengan como nombre igual a un tipo de evento activo. Por ejemplo: Saldrá el tipo de pagamento "Inscripción" si existe un evento de tipo "Inscripción" en activo y se está dentro de las fechas de inicio y fin de este último.

**Comment by ybenitezf** [comment]
Ya me di cuenta de donde esta el problema, este issue debería llamarse **registrar pago de candidatura** o **registrar pago de inscripción** - es el único tipo de pago que tenemos de momento - de esta forma el primer paso:
- **Se escogerá el tipo de pagamento que se desea realizar** (*): Solo aparecerán los tipos de pagametos que tengan como nombre igual a un tipo de evento activo. Por ejemplo: Saldrá el tipo de pagamento "Inscripción" si existe un evento de tipo "Inscripción" en activo y se está dentro de las fechas de inicio y fin de este último.

No es necesario porque va implícito - es decir ya se esta suponiendo que es para en evento de tipo "Inscripción" y por lo tanto el pago deberá ser de este tipo. Entonces el resto quedaría:
- **Estudiante** (*): Saldrá una lista de estudiantes que cumplan las condiciones para realizar el tipo de pagamento anteriormente seleccionado; en dicha lista aparecerán los campos "Documento de identidad", "Nombre", "Primer apellido" y "Segundo apellido". La lista será un "grid" y se permitirá realizar búsquedas y consultas utilizando las potencialidades del componente. Además, cada estudiante tendrá en la parte derecha un vínculo llamado "Registrar pago".

...

**Comment by eadomenech** [comment]
Lo que dices de que solo tendremos por el momento "Inscripción" es cierto. Y así será para poder avanzar. Pero de la forma que lo describí cumplimos eso y damos cabida a los próximos tipos de pagamentos. Es cierto que la idea de machear los tipos de eventos con los pagos debo madurarla un poquitico más, pero eso no cambia lo que en este issue te describo. Te propongo que lo hagas exactamente como te lo describo aquí. Le cambié el nombre a "Registrar pagamento" porque no tendremos varios "Registrar pagamentos X". Solo tendremos uno. Una vez que se elija el tipo de pagamento se cambiarán las opciones del pagamento como tal. Por el momento, solo tenemos la del tipo "Inscripción" y ya te la detallo en este issue. 
También es cierto que es la funcionalidad en el sistema la que deba llamarse "Registrar pago" y no el issue como tal, ya que en este issue solo harás lo de inscripción, ya existirán otros issue con otros nombre "Registrar pago X". Por eso motivo vuelvo a cambiar el nombre del issue. Ahora, la forma de desarrollarlo se mantiene exactamente como la describí.

**Comment by ybenitezf** [comment]
Olvide el número de expediente del candidato

**Comment by eadomenech** [comment]
<type 'exceptions.AttributeError'> 'module' object has no attribute
'obtener_selector_estado'

2015-07-07 17:15 GMT+01:00, Yoel Benítez Fonseca notifications@github.com:

> Closed #39 via 94d454a0074479d01e37d97280a248a08807b8c3.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/39#event-349862177

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
claro que el modulo tiene ese atributo, seguro tenias el sistema abierto. Debes o cerrar web2py completo o abrir el modulo db/candidatura.py en el editor de web2py y guardarlo con el mismo para que te lo compile.
