### ISSUE TITLE
Corrección del campo Natural en la gestión de las personas

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#40]
El campo natural no es el municipio como teniamos entendido antes. Es el nombre de la comuna. Si te fijas en los reportes, el código que debemos poner ahí es de 6 dígitos y es hasta la comuna. Propongo hacer algo similar a lo que hiciste en lo de la residencia. Primero poner municipio donde nació y luego escoger la comuna de acuerdo al municipio que eligió.

**Comment by ybenitezf** [comment]
Te recuerdo que el campo `Natural` no existe, supongo te refieres a `place_of_birth`. Me he fijado en una cosa, esto de señalar un lugar por medio de `provincia - municipio - comuna` aparece en varias partes, por ejemplo para `Persona`, otro ejemplo sería `middle_school`, otro es en `organic_unit` ... etc. me parece que se repito un poco, que tal si en ves de en cada modelo incluir las 3 cosas separamos eso una tabla que se llama por ejemplo `Location` que tendría los campos `provincia, municipio, comuna` y tal ves tambien `dirección` y que en cada parte cuando sea necesario se escoja de las registradas la que sea necesaria?

**Comment by eadomenech** [comment]
No creo. Es mejor tenerlo así dividido. En el caso del lugar de nacimiento hacerlo similar al de residencia, primero se escoge el municipio y luego la comuna.
