### ISSUE TITLE
Gestionar conceptos de pago de pagos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#41]
Para la gestión de los conceptos de pago se tienen que introducir los siguientes datos:
- **Nombre** (*): Nombre que identifica al concepto de pago. Será único, es decir, no existirán 2 tipos de pagos con el mismo nombre. Ejemplo: Inscripción.
- **Periosidad** (*): Existirán varios tipos de periosidad como "Única", "Mensual", etc. Por el momento solo utilizaremos "Única" que es la periosidad de la Inscripción. Un tipo de pagamento es "Única" cuando solo se hace una vez.
- **Cantidad estipulada** (*): Cantidad estipulada a pagar.
- **Estado** (*): El "Estado" puede ser "Activo" o "No activo". Esto lo utilizaremos cuando gestionemos los eventos. Es decir, cuando se diga la Inscripción es de X fecha a Y fecha, automáticamente el tipo de pago Inscripción se pone "Activo" durante esta fecha y solo durante ella.

De la información anterior todo lo marcado con (*) es de carácter obligatoria.
A esta funcionalidad se podrá acceder desde el sistema en Contabilidad->Configuración general->Tipos de Pagos

**Comment by ybenitezf** [comment]
¿una cosa que no entiendo es porque en esto del concepto de pago se incluye la cantidad?
