### ISSUE TITLE
Gestionar Asignaturas

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#43]
Para la gestión de las asignaturas se tienen que introducir los siguientes datos:
- **Nombre** (*): Nombre de la asignatura.
- **Abreviatura** (*): Abreviatura.

De la información anterior todo lo marcado con (*) es de carácter obligatoria.
A esta funcionalidad se podrá acceder desde el sistema en Configuración->Institución->Oraganización Educacional->Asignaturas

**Comment by ybenitezf** [comment]
¿estas seguro de que las asignaturas no llevan un codigo?

**Comment by ybenitezf** [comment]
oye, esto de las asignaturas, no estan ligadas a una carrera ni nada de eso ? te pregunto pq no veo como despues se podra consulta que asignaturas pertenecen a que carrera y cosas como esas.

**Comment by eadomenech** [comment]
Eso se hace en el plano curricular Ahí es donde se machea Carrera con 
Asignatura

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 28 de junio de 2015 20:21:00 Yoel Benítez Fonseca 
notifications@github.com escribio:
