### ISSUE TITLE
Gestionar Planes Curriculares

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#45]
Para la gestión de los planes curriculares se tienen que introducir los siguientes datos:
- **Carrera** (*): Se escogerá una carrera de las existentes en la UO.
- **Nivel académico** (*): Se escogerá un nivel académico de los existentes en la UO.
- **Asignatura** (*): Se escogerá una asignatura de las impartidas en la UO.
- **Estado** (*): "Activo" o "No activo". Por defecto "No Activo".

De la información anterior todo lo marcado con (*) es de carácter obligatoria.
A esta funcionalidad se podrá acceder desde el sistema en Configuración->Institución->Oraganización Educacional->Planes Curriculares

**Comment by ybenitezf** [comment]
supongo que "plan curricular" es lo mismo que teniamos como plan academico !?

**Comment by eadomenech** [comment]
Al acceder a la Gestión de Planos Curriculares aparecerá la lista de los Planos Curriculares existentes. Aparecerán los campos Nombre, Carrera a la que pertenece y Estado. A la derecha de cada uno de ellos aparecerán los botones para su edición o eliminación y aún más a la derecha un vículo llamado "Gestionar" (parecido a los de Provincia-Municipio) que gestionaría todas las asignaturas por nivel académico que posee ese Plan Curricular.

Se podrán adicionar PC de la siguiente manera. Para la adición de los planes curriculares se tienen que introducir los siguientes datos:
- **Nombre** (*): Nombre del Plan Curricular.
- **Carrera** (*): Se escogerá una carrera de las existentes en la UO.
- **Estado** (*): "Activo" o "No activo". Por defecto "No Activo".
  Además se almacenará en la bd la fecha de creación del Plan curricular:
- **Fecha** (*): Fecha de creación.

Una ves adicionado un Plan, se volverá a la lista de Planos Curriculares existentes (actualizada). 

Al entrar en un "Gestionar" de un Plan Curricular específico, aparecerá una lista de las asignaturas que posee ese Plan por cada uno de los niveles académicos. A esa lista se le podrán adicionar elementos. Para ello se necesitarán los datos siguientes:
- **Nivel académico** (*): Se escogerá un nivel académico de los existentes en la UO.
- **Asignatura** (*): Se escogerá una asignatura de las impartidas en la UO.

En la lista anterior también aparecerá a la derecha el botón de eliminar.

Nota: Aquí faltan algunos campos por adicionar, pero son utilizados cuando tengamos estudiantes ya. Para el proceso de candidatura, que es el que estamos, es suficiente con estos que escribí aquí. Luego, cuando tengamos estudiantes, solo tendremos que comprobar el nivel académico y en caso que sea de 1ro a 5to, aparecerán los otros campos.   

De la información anterior todo lo marcado con (*) es de carácter obligatorio.
A esta funcionalidad se podrá acceder desde el sistema en Configuración->Institución->Oraganización Educacional->Planes Curriculares

**Comment by ybenitezf** [comment]
Falta una cosa aquí, como ves se pueden tener más de una unidad orgánica, así que cuando dices:  
- **Carrera** (*): Se escogerá una carrera de las existentes en la UO.

No se si te refieres a todas las carreras de todas las UO o si tendremos que incluir en el plan también a que UO va a pertenecer este plan o sencillamente muestro todas las carreras de todas las UO y que queden amarrados por esa asociación.?

**Comment by eadomenech** [comment]
En un futuro habrá que escoger una UO. Puede darse el caso que hayan
dos UO con una determinada carrera e común y cada uno de ellos tenga
planes distintos. Pero como ahora solo nos importa que funcione para
la UO donde estoy eso queda para después. Es lo que te propongo.
Concentrarnos para que funcione en la UO.

El 3/7/15, Yoel Benítez Fonseca notifications@github.com escribió:

> Falta una cosa aquí, como ves se pueden tener más de una unidad orgánica,
> así que cuando dices:
> - **Carrera** (*): Se escogerá una carrera de las existentes en la UO.
> 
> No se si te refieres a todas las carreras de todas las UO o si tendremos que
> incluir en el plan también a que UO va a pertenecer este plan o
> sencillamente muestro todas las carreras de todas las UO y que queden
> amarrados por esa asociación.?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/45#issuecomment-118381029

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
¿en la UO? no me aclara nada. Te digo lo que voy a hacer, que por defecto coja la unidad orgánica asociada a la escuela por defecto y por ende esas mismas carreras, todo eso por detrás ya cuando llegue el momento entonces que seleccione la unidades orgánicas y las carreras que correspondan.

**Comment by eadomenech** [comment]
Perfecto

El 3/7/15, Yoel Benítez Fonseca notifications@github.com escribió:

> ¿en la UO? no me aclara nada. Te digo lo que voy a hacer, que por defecto
> coja la unidad orgánica asociada a la escuela por defecto y por ende esas
> mismas carreras, todo eso por detrás ya cuando llegue el momento entonces
> que seleccione la unidades orgánicas y las carreras que correspondan.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/45#issuecomment-118387339

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
No hacia falta mi preocupación en cuanto a lo del vinculo plan - UO, debido a que las carreras que se pueden asociar a un plan están ya vinculadas a una UO, por ende cuando se asocia el plan a una carrera este esta asociado por consiguiente a una UO.
