### ISSUE TITLE
Gestionar Departamento

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#47]
Para la gestión de los departamentos se tienen que introducir los siguientes datos:
- **Nombre** (*): Nombre del departamento (DEI)
- **UO** (*): Se escogerá una unidad orgánica de las existentes

De la información anterior todo lo marcado con (*) es de carácter obligatoria.
A esta funcionalidad se podrá acceder desde el sistema en Configuración->Institución->Departamentos

**Comment by eadomenech** [comment]
Closed

**Comment by ybenitezf** [comment]
Migrarlo la nueva forma de gestión
