### ISSUE TITLE
Gestionar Docente

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#48]
Para la gestión de los docentes se tienen que introducir los siguientes datos:
- **Persona** (*): Un docente es una persona y por lo tanto posee todos los campos correspondiente de una persona.
- **Vínculo** (*): Puede ser "Efectivo", "Colaborador" u "Otros"
- **Categoría docente** (*): Puede ser "Profesor Instructor", "Profesor Asistente", "Profesor Auxiliar", "Profesor Asociado", "Profesor titular" u "Otros"
- **Grado** (*): Puede ser "Bacharelato", "Licenciatuara", "Mestrado" o "Doutoramento"
- **Fecha de entrada a la UO** (*): Fecha de entrada a la UO.
- **Departamento** (*): Se escogerá un departamento de los existente en el sistema.
- **Estado** (*): "Activo" o "No activo". Por defecto "Activo".

De la información anterior todo lo marcado con (*) es de carácter obligatoria.
A esta funcionalidad se podrá acceder desde el sistema en Recursos Humanos->Docentes->Gestión de docentes

**Comment by ybenitezf** [comment]
migrarlo a la nueva forma de gestión

**Comment by ybenitezf** [comment]
voy a cambiar Recursos Humanos->Docentes->Gestión de docentes por Recursos Humanos->Profesorado

1ro pq ya existe un "docentes" en el menu
2do pq es mejor hacer la diferencia, docentes significa muchas cosas, mientras que profesor solo una.
