### ISSUE TITLE
Gestionar Unidades Orgánicas (UO)

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#5]
El sistema debe poder adicionar, modificar y eliminar las UO. Las UO pertenecen a alguno de los IES. Poseen un nivel de agregación con su respectiva codificación, Sede Central (1) y Unidad orgánica (0). Poseen una clasificación de la Unidad Orgánica con su respectiva codificación, Institutos Superior (20), Institutos Superior Técnico (21), Institutos Superior Politécnicos (22), Escolas Superior (30), Escolas Superior Técnicas (31), Escolas Superior Politécnicas (32), Academias (40), Faculdades (50), Departamentos (60) y Centros de Investigação Científica (70). Las UO poseen un código de registro que está compuesto por 14 caracteres (los primeros 8 es el código del IES al que pertenece, luego 1 caracter correspondiente al nivel de agregación, luego 2 caracteres correspondientes a la clasificación y finalmente otros 3 que representan un número sequencial/consecutivo; el criterio utilizado para conformar este campo es el orden de registro de la unidad orgânica en el minesterio. Además las UO poseen un código adicional que es asignado por el IES al que pertenece, este código posee 2 caracteres, por ejemplo 01.  Las UO también poseen un nombre, por ejemplo, la que pertenezco se llama Escola Politécnica da Lunda Sul. Además están ubicadas en una provincia determina y tienen una dirección. Nota: todos esos datos la primera ves que se ejecute la aplicación - aunque el usuario tenga la posibilidad de gestionar esos datos despues - lo que estoy pensando es que como es raro que se cambie de UO en el centro de educación donde se esta usando el sistema esa parte de seleccionar UO se puede poner como parte tambien de la configuración, por ejemplo fijar en db.py o en otra parte una constante con el ID de la unidad organica con la que se esta trabajando en esa instalación.

**Comment by ybenitezf** [comment]
Loco, ponle labels a cada issue que publiques, por ejemplo en este caso sería la etiqueta "enhancement" porque es algo nuevo, si fuera sobre un error le pones "bug"

**Comment by ybenitezf** [comment]
Me preocupa esta parte de la preconfiguración, si lo pongo como una constante entonces si después queremos ponernos con otro cliente habria que estar cambiando código, ¿Por qué no lo dejamos así por ahora y vemos más adelante como se puede reolver eso? El lio es que de todas formas los datos de todas las cosas van a estar ligados a la UO correcta de una forma ú otra.

**Comment by eadomenech** [comment]
Las UO se gestionarán de forma similiar a los IES. No se fijará en una preconfinguración la UO en la que se trabajará.

**Comment by ybenitezf** [comment]
"Además las UO poseen un código adicional que es asignado por el IES al que pertenece" no pasa a formar parte del código de la UO, es decir 14 digitos sin estos últimos 2

**Comment by eadomenech** [comment]
No. Eso es solo un código que es utilizado para ponerle el número a
los estudiantes. Me parece que es algo muy de mi universidad y no a
nivel nacional.

El 23/3/15, Yoel Benítez Fonseca notifications@github.com escribió:

> "Además las UO poseen un código adicional que es asignado por el IES al que
> pertenece" no pasa a formar parte del código de la UO, es decir 14 digitos
> sin estos últimos 2
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/5#issuecomment-85053560

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
Tenía la impresión de que el código ese que se genera para los estudiantes era algo de nievel nacional.

**Comment by ybenitezf** [comment]
Completo, loco veme lo de la cuenta que estoy loco por tenerla PC para que veas que adelanton le damos a esto.
