### ISSUE TITLE
Asignar asignatura

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#50]
Para asignar asignatura y grupo a un docente se tienen que introducir los siguientes datos:
- **Docente** (*): Se escogerá un docente de los existentes en el sistema.
- **Año académico** (*): Se escogerá un año académico de los existente en el sistema.
- **Asignatura** (*): Se escogerá una asignatura de las existentes en el sistema.
- **Evento** (*): Se escogerá un evento de los existentes.
- **Estado** (*): "Activo" o "No activo". Por defecto "Activo".

De la información anterior todo lo marcado con (*) es de carácter obligatoria.
A esta funcionalidad se podrá acceder desde el sistema en Recursos Humanos->Docentes->Asignar asignatura

**Comment by ybenitezf** [comment]
aquí dices que es para asignar una asignatura y grupo al docente, ¿se te 
olvido poner el grupo en la lista de datos?

El 07/05/15 a las 11:18, Ernesto Avila Domenech escibió:
