### ISSUE TITLE
Otorgar nota de examen de acceso

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#51]
Los profesores registrados en el sistema podrán tener asignadas algunas asignaturas de las existentes y activas en el sistema. Los profesores, luego de calificar, podrán otorgar la nota correspondiente a cada estudiante que haya realizado alguna de las asignaturas asignadas al profesor. Un profesor que no tenga asignada la asignatura X no podrá emitir ninguna nota de dicha asignatura.
El profesor podrá emitir una nota en el rango de 0 a 20 puntos y solo podrá emitirla una vez.
Un profesor que tenga el rol de ("Jefe de la asignatura") podrá realizar modificaciones a las notas emitidas por los demás profesores de la asignatura en cuestión. Dicho rol lo podrán tener varios profesores. Para que un profesor sea Jefe de un asignatura determinada, debe necesariamente tenerla asignada.
En el proceso de calificación, los profesores calificadores no podrán ver el nombre del estudiante para evitar cualquier irregularidad. Para esto, los estudiantes escriben el nombre solo es una parte del examen, que luego es rasgada. A ambas partes se le asigna una codificación para luego saber la nota obtenida por cada estudiante. 

Para el otorgamiento de nota:
- **1**: Se permitirá otorgar nota si se está entre la fecha de inicio y fin del evento "Inscripción" del Año académico en el que se está haciendo la candidatura.

**Comment by ybenitezf** [comment]
Lo quite del sprint 5 porque depende de cosas que no están hechas todavía

**Comment by eadomenech** [comment]
Los profesores registrados en el sistema podrán tener asignadas algunas asignaturas de las existentes y activas en el sistema. Los profesores, luego de calificar, podrán otorgar la nota correspondiente a cada estudiante que haya realizado alguna de las asignaturas asignadas al profesor. Un profesor que no tenga asignada la asignatura X no podrá emitir ninguna nota de dicha asignatura.
El profesor podrá emitir una nota en el rango de 0 a 20 puntos y solo podrá emitirla una vez. 
Un profesor determinado ("Jefe de la asignatura") podrá realizar modificaciones a alguna nota emitida por un profesor de la asignatura. 
Para que un profesor sea Jefe de un asignatura determinada, debe necesariamente tenerla asignada.

**Comment by ybenitezf** [comment]
¿cual de las dos descripciones es valida? la primera tiene mucho más información que la según, pero las 2 tienen algunos puntos ambiguos.

**Comment by eadomenech** [comment]
La primera.

El 29/7/15, Yoel Benítez Fonseca notifications@github.com escribió:

> ¿cual de las dos descripciones es valida? la primera tiene mucho más
> información que la según, pero las 2 tienen algunos puntos ambiguos.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/51#issuecomment-126001275

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
oeee esto sigue siendo una mierda de historia mal redactada, me pesa has comenzar a leerla, estoy seguro que puedes hacerlo mejor. recuerda que en estas cosas estoy siempre esperando por ti.

**Comment by eadomenech** [comment]
Voy a intentarlo de nuevo.
 Una vez que los estudiantes han realizado los exámenes, no hay que esperar necesariamente que se terminen todos, los profesores se encargarán de calificar y insertar al sistema la nota. Para cada examen solo se permitirá calificar a los profesores que estén asignado a la asignatura correspondiente con ese examen. 
Los estudiantes obligatoriamente deben utilizar una hoja que la escuela les da, dicha hoja tiene en la esquina superior derecha los espacios correspondientes para que el estudiante escriba sus datos como el nombre. Luego que los estudiantes entreguen sus pruebas, los profesores que están cuidando dicho examen les entregan las pruebas en un sobre a un determinado funcionario de la escuela. Este último se encarga de entregar las pruebas a un determinado equipo de personas que rasgan la esquina superior derecha de cada una de las hojas utilizadas en los exámenes, además le asignan un número único a ambas partes (hoja sin la esquina rasgada y esquina rasgada correspondiente a la hoja) para luego de ser calificada saber a qué persona corresponde dicho examen. 
Todas las hojas rasgadas (hojas sin la esquina superior derecha) de los exámenes se le entregan a los equipos de calificación (personas que tienen la asignatura asignadas) para que comiencen a calificar. Cada profesor luego de calificar asignará la nota al correspondiente estudiante. La nota estará en el rango de 0 a 20. Es evidente que los profesores que asignan notas no buscarán por nombre, sino por un número o código que posea la hoja rasgada. Es por eso que la persona que rasgas las hojas, debe poner o ver el número o código correspondiente a ese estudiante para esa asignatura. Digo poner o ver pues podemos elegir el método para realizar esta actividad. El objetivo es que los profesores no sepan en ningún momento a qué estudiante están calificando y otorgándole la nota. Lo que propongo es que el sistema otorgue un número único a cada estudiante para cada examen y que la persona que rasga la hoja busque al estudiante en el sistema y le escriba el número en la hoja rasgada. Está claro que solo estas personas son las que podrán ver el número correspondiente a cada estudiante y que además no podrán calificar.

**Comment by eadomenech** [comment]
Otro intento.

Los profesores, que tengan asignado una determinada asignatura, podrán otorgar nota del examen correspondiente a la misma para cada estudiante candidato que lo realice. Dicha nota estará en el rango de 0 a 20.

Los profesores solo podrán otorgar una ves la nota de un examen a un estudiante; no se permitirá modificar ninguna nota.

Existirá un privilegio, “Jefe de asignatura”, el cual posibilitará a los profesores que lo posean, modificar cualquier nota correspondiente a dicha asignatura.

Debe quedar registrada la asignación y modificación de notas. Para ello será necesario almacenar profesor, examen, estudiante y data de la asignación o modificación. Se debe diferenciar si la acción es una asignación o modificación para realizar futuros análisis. 

Existirá un grupo de personas llamadas “organizadores de exámenes de acceso”, las cuales quitarán de las hojas de los exámenes todos aquellos datos que identifiquen al estudiante (nombre) y escribirán en el resto, un código que identifique a cada estudiante candidato. Dichos organizadores serán los únicos que tendrán privilegio para ver el código que identifica a cada estudiante.

Los profesores que otorgan notas, harán la búsqueda del estudiante a otorgar nota por el código que aparece en la hoja del examen. Es decir, solo se limitarán a decir “el estudiante con código X tiene la nota Y en el examen Z”.

**Comment by ybenitezf** [comment]
Pienso que para esto:

> Existirá un grupo de personas llamadas “organizadores de exámenes de acceso”, las cuales quitarán de las hojas de los exámenes todos aquellos datos que identifiquen al estudiante (nombre) y escribirán en el resto, un código que identifique a cada estudiante candidato. Dichos organizadores serán los únicos que tendrán privilegio para ver el código que identifica a cada estudiante.

Se podría manejar de la siguiente forma:
1. En algún momento - para permitir la migración de datos de una versión a otra, voy a tener que asignar a cada persona un **uuid** [https://es.wikipedia.org/wiki/Identificador_%C3%BAnico_universal] - este número es un poco largo.
2. Se puede hacer que los **organizadores de exámenes de acceso** puedan imprimir el listado de estudiantes con sus códigos (`uuid`)  y puedan entonces recortar los código para pegarlos al examen, de esa forma aunque el **uuid** es largo ellos no tendrán chance de equivocarse, solo tienen que coger el examen que entrega el estudiante, buscarlo en el listado ya impreso, coger la tirrilla correspondiente al código del estudiante y pegarla al examen.
3. Esta forma me asegura a mi la unicidad de cada código y como de todas formas cada persona en el sistema tendrá uno de estos puedo usarlos como llaves para buscar a la persona a quien corresponde.
4. Otra ventaja es que no son como los números de identidad, números de inscripción y otros datos que pueden deducirse a partir de los datos personales del estudiante.
