### ISSUE TITLE
Gestinar candidatos inscritos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#52]
Para la gestión de los candidatos inscritos se procederá de la siguiente forma:
- **1** : No se permitirá la adición directa de un candidato inscrito. Estos solo vendrán de los candidatos con deudas que realicen el pago correspondiente.
- **2** : Se listarán todos los candidatos inscritos. En este listado aparecerá el número de expediente, nombre completo, nombre de la carrera que opta en 1ra opción y nombre de la carrera que opta en 2da opción.

A esta funcionalidad se podrá acceder desde el sistema en Educational->Candidates

**Comment by ybenitezf** [comment]
actualizame esto para que concuerde con los cambios nuevos.

**Comment by eadomenech** [comment]
Este issue no procede por el momento.
