### ISSUE TITLE
Listar y exportar a excel la ubicación de los candidatos inscritos por cada asignatura a examinar

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#53]
- **1** : Se listarán los candidatos inscritos con los datos: número de expediente, nombre completo, asigatura a examinar y sala de aula donde examinará la asignatura antes mencionada.
- **2** : Se exportará a excel y pdf dicho listado o la consulta realizada a dicho listado. Es decir, En caso de que un estudiante se tenga que presentar a 3 asignaturas, deberá aparecer 3 veces en el listado original, pues la asignatura a examinar cambia, pudiendo o no cambiar también la sala de aula que examinará dicha asignatura. Si se desea tener solo el listado de los estudiantes que examinarán una determinada asignatura en una determinada sala de aula, se hace la consulta y luego se exporta.  

A esta funcionalidad se podrá acceder desde el sistema en Educational->Candidates

**Comment by ybenitezf** [comment]
necesita más aclaración, no seas vago.

**Comment by ybenitezf** [comment]
igual que el #51 no necesita de cosas que no están descritas por eso le quite del Sprint 5

**Comment by eadomenech** [comment]
- **1** : Una vez que se esté en la lista descrita en el issue #67 se realizarán las acciones que a continuación se describen.
- **2** : Se exportará a excel dicho listado o la consulta realizada a dicho listado. Los campos a exportar serán Nº de Inscripción, Nombre completo, Nº de identidad y Sala de aula. 
- **3** : El excel tendrá encima el logotipo, debajo el nombre del IES, debajo el nombre de la UO y aún más debajo el nombre de la asignatura. 

Nota: Lo del logotipo no es tan importante ahora. En caso de llevarte un tiempo considerable no hacer lo del logotipo.
