### ISSUE TITLE
Corregir la Gestión de Plazas

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#56]
En la gestión de las plazas es conveniente hacer lo siguiente:
- **1:** Si se introdujo al sistema la cantidad de plazas a otorgar en una determinada carrera, en un determinado año académico y en un regimen determinado, entonces a la hora de volver a introducir alguna plaza no se debe mostrar la opción de este regimen para esta carrera en este año académico.
- **2:** En caso de que una carrera, en un determinado año académico, ya haya agotado todos los regimenes posibles, no se mostrará dicha carrera a la hora de insertar una nueva plaza.

**Comment by ybenitezf** [comment]
No entendí ni papa, lo que si me doy cuenta es de lo siguiente:
- las plazas a otorgar deben ser para el año académico actual, es decir, 
  no hace falta que se de la posibilidad de escoger el año académico ya 
  que debería ser para el año académico en curso, por ejemplo si estamos 
  en el curso académico 2015 entonces solo se deben poder definir plazas 
  para ese propio año académico - para que complicarse la vida con cosas 
  que todavía no van a suceder o ya han sucedido.

te propongo lo siguiente:
1. cuando el usuario escoja asignar plazas que se muestre el listado de 
   las carreras disponibles en al unidad orgánica.
2. para cada carrera habrá un enlace "definir plazas para nuevos 
   ingreso" o algo por el estilo.
3. cuando se de clic en el enlace anterior aparecerán los regímenes 
   disponibles para esa carrera y el año académico actual, cada uno con un 
   campo de edición al lado para que el usuario edite la cantidad de plazas 
   que va a otorgar.

Todavía no tengo claro que hacer con ese número, supongo que se usará en 
algún momento para decidir si el estudiante-candidato va o no a poder 
acceder a la carrera dependiendo de sus resultados en los exámenes pero 
eso me lo puedes explicar en otro issue o en un correo independiente.

**Comment by eadomenech** [comment]
Veo bien este proceder. Con eso número que dices que no sabes para qué lo utilizaremos, definiremos los estudiantes que serán aceptados. generalmente hay más candidatos que plazas disponibles. Las plazas dependen de muchos factores, pero eso no intereza. Teniendo el número de plazas podremos saber en tiempo real los estudiantes aceptado y los que no, pues se hace un ranking y los k primeros (siendo k el número de plazas) son los aceptados.

**Comment by eadomenech** [comment]
Aquí creo que también debemos poner el número mínimo para que se dé la carrera. Es decir, si se configura como número mínimo 15 entonces, si solo solicitaron esta carrera 14 estudiantes, la carrera no se abre y estos estudiantes estarían optando por las carreras que pusieron en 2da opción, en otro caso queda como no admitido.

**Comment by ybenitezf** [comment]
loco, no me acaba de cuadrar todo eso de forma automática, siempre he
visto todo ese proceso como algo delicado, el tema de decidir que
carrera se abre o no creo que debería ser del sistema, pero bueno, tu
sabrás.

El 7/7/15, Ernesto Avila Domenech notifications@github.com escribió:

> Aquí creo que también debemos poner el número mínimo para que se dé la
> carrera. Es decir, si se configura como número mínimo 15 entonces, si solo
> solicitaron esta carrera 14 estudiantes, la carrera no se abre y estos
> estudiantes estarían optando por las carreras que pusieron en 2da opción, en
> otro caso queda como no admitido.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/56#issuecomment-119262045

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
necesito que revises toda esta conversación y escribas de nuevo este issue #56 teniendo en cuenta todo lo que hemos discutido aquí.

**Comment by eadomenech** [comment]
En la gestión de las plazas es conveniente tener en cuenta lo siguiente:
- **1:** Cuando el usuario escoja "Plazas a asignar" se debe mostrar primeramente en un listado  las carreras disponibles en la UO.
- **2:** Para cada carrera habrá un enlace "Definir plazas para nuevos ingresos" a la derecha.  
- **3:** Cuando se de clic en el enlace "Definir plazas para nuevos ingresos" aparecerán los regímenes disponibles para esa carrera y el "año académico a configurar", cada uno con 3 campos de edición al lado para que el usuario edite según corresponda.  
- **4:** Se define "año académico a configurar" al año académico correspondiente al evento de tipo Inscripción que esté activo. En caso de no haber ningún evento de este tipo activo no se podrá definir las plazas a otorgar.  
- **5:** Los 3 campos que se editarán corresponderán a los datos "Plazas necesarias a cubrir", "Plazas máximas a otorgar" y "Media mínima". Las "Plazas necesarias a cubrir" será el número que indicará si se abre o no la carrera, en caso de no existir como mínimo esta cantidad de candidatos que solicitan esta carrera entonces no se abriría, por defecto tendrá como valor 0. "Plazas máximas a otorgar" será el número máximo de plazas a otorgar, por defecto tendrá un valor igual al de "Plazas necesarias a cubrir", es decir, comenzará en o igual y cada vez que se edite el campo "Plazas necesarias a cubrir" se comprobará que "Plazas necesarias a cubrir" sea menor que el de  "Plazas máximas a otorgar", en caso de ser verdadero se mantendría su valor, en caso contrario tomaría el mismo valor que  "Plazas necesarias a cubrir". La "Media mínima" representa la media mínima que deben tener los candidatos, en los exámenes de acceso, para optar por esta carrera.

**Comment by ybenitezf** [comment]
Aquí tengo un pequeño problema:
- **3:** Cuando se de clic en el enlace "Definir plazas para nuevos ingresos" aparecerán los regímenes disponibles para esa carrera y el "año académico a configurar", cada uno con 3 campos de edición al lado para que el usuario edite según corresponda.  

Pero las carreras no tienen relación directa con año académico o régimen.

**Comment by ybenitezf** [comment]
Man que va no entiendo lo que quieres hacer, puedes hacer un sketch de eso aunque sea en papel y le tires una foto despues con el movil ?

**Comment by ybenitezf** [comment]
sobre todo de los pasos 3,4 y 5

**Comment by eadomenech** [comment]
![yoel](https://cloud.githubusercontent.com/assets/11457046/8591079/da2e14e0-261d-11e5-8eaf-e63b84681ee6.png)

**Comment by eadomenech** [comment]
4: Se define "año académico a configurar" al año académico correspondiente al evento de tipo Inscripción que esté activo. En caso de no haber ningún evento de este tipo activo no se podrá definir las plazas a otorgar.

Explicación más detallada:
La funcionalidad "Definir plazas" solo estará disponible en caso de existir un evento activo de tipo Inscripción, y que se esté dentro de la fecha de inicio y fin del mismo. 
El campo "año académico a configurar" se refiere al año académico correspondiente al evento de tipo Inscripción que esté activo. Evidentemente no podrán existir dos o más eventos de tipo Inscripción activos a la misma vez.

**Comment by eadomenech** [comment]
5: Los 3 campos que se editarán corresponderán a los datos "Plazas necesarias a cubrir", "Plazas máximas a otorgar" y "Media mínima".
 Las "Plazas necesarias a cubrir" será el número que indicará si se abre o no la carrera, en caso de no existir como mínimo esta cantidad de candidatos que solicitan esta carrera entonces no se abriría, por defecto tendrá como valor 0.
Las "Plazas máximas a otorgar" será el número máximo de plazas a otorgar, por defecto tendrá un valor igual al de "Plazas necesarias a cubrir", es decir, comenzará en 0 igual y cada vez que se edite el campo "Plazas necesarias a cubrir" se comprobará que "Plazas necesarias a cubrir" sea menor que el de "Plazas máximas a otorgar", en caso de ser verdadero se mantendría su valor, en caso contrario tomaría el mismo valor que "Plazas necesarias a cubrir".
La "Media mínima" representa la media mínima que deben tener los candidatos, en los exámenes de acceso, para optar por esta carrera. Los candidatos hacen 2 o 3 pruebas de acceso. Se calcula el promedio de esas evaluaciones y es lo que se le llama media. Con esa media es que se hace el ranking para optar por las plazas.

No se como detallar más esto. De todas formas si sigues sin entender me dices para describirlo de otra manera.

**Comment by ybenitezf** [comment]
OK, ya tengo una idea, de todas formas no contestaste mi progunta pero voy a asumir lo siguiente:
1. cuando se selecciona una carrera se mostraran por cada _año académico_ definido en el sistema los regímenes que existan para la unidad orgánica a la que pertenece la carrera - eso es lo que te preguntaba, la carrera en si no tiene asociación con el régimen en ninguna de las relaciones que hemos definido - y por cada uno de estos regímenes los editar para los 3 campos esos que me dices.
2. lo de   "Plazas necesarias a cubrir", "Plazas máximas a otorgar" y "Media mínima" lo entendí a la primera.

**Comment by eadomenech** [comment]
No Creo q estas confundiendo año académico con nivel académico No es lo 
mismo Cuando hablo de año académico es lo que es allá curso académico Y 
como bien puse anteriormente lo tomará del evento tipo inscripción q haya 
activo si es q lo hay Eventos de este tipo sólo habrá uno x año académico 
Así q a la hora de definir las plazas aparecerá como en la foto q subí
En cuanto a los regimes no hace falta especificar los regímenes q tiene 
cada carrera Con dejar el máximo en 0 es suficiente

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 9 de julio de 2015 13:55:45 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
no, no estoy confundido, si se que es el año académico.

**Comment by ybenitezf** [comment]
chequea los cambios que subí, falta la validación de **Plazas necesarias a cubrir** y **Plazas máximas a otorgar**

**Comment by eadomenech** [comment]
Ok. Lo veo bien así. De todas formas voy a probarlo con más detalle
dentro de un rato. También voy a subirte los otros issue que hice hoy.

El 9/7/15, Yoel Benítez Fonseca notifications@github.com escribió:

> chequea los cambios que subí, falta la validación de **Plazas necesarias a
> cubrir** y **Plazas máximas a otorgar**
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/56#issuecomment-120079924

## 

Saludos,
  Ernesto.

**Comment by eadomenech** [comment]
Las plazas máximas no pueden ser menores que las necesarias. En la descripción lo explico en el punto 5.

**Comment by ybenitezf** [comment]
hijo tu leiste bien esa oración: las maximas ( si son maximas ) claro
que pueden ser más que las necesarias, lo contrario sería lo que esta
mal.

El 10/7/15, Ernesto Avila Domenech notifications@github.com escribió:

> Las plazas máximas no pueden ser mayores que las necesarias. En la
> descripción lo explico en el punto 5.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/56#issuecomment-120489586

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by eadomenech** [comment]
Ya la leí y no se donde está el error. Dime donde está?

**Comment by eadomenech** [comment]
Ya veo que el problema se corrigió, la única duda que tengo es la siguiente:

Cuando doy en uno de los botones Guardar para guardar los número, me hace un efecto la pantalla que no me gusta, me refiero a la forma en que actualiza ese componente. No se si a ti te pasa lo mismo. Incluso hace como que va a poner un mensaje de esos de notificación, pero al final no lo pone.
