### ISSUE TITLE
Matrícula y Confirmación de matrícula

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#57]
Los procesos de Matrícula y Confirmación de matrícula son procesos que se realizan de forma separadas pudiéndose solapar entre ellos. Ambos pertenecen a una Unidad Orgánica y están enmarcados en un tiempo determinado, es decir, poseen Data de inicio y data fin. Además, pueden estar activo o no. 
**Proceso de Confirmación de Matrícula**
La Confirmación de Matrícula es el proceso donde los estudiantes continuantes confirman sus datos personales, laborales y de las institución. Los especialistas con permiso para realizar la confirmación de matrícula se guían por unos archivos .xls brindados por la institución para determinar la situación académica del mismo y en correspondencia de esto colocar el nivel académico que será asignado al estudiante. 
Deben realizar la confirmación de matrícula los estudiantes ya existentes en la UO que no se hayan graduado.
Para confirmar matrícula cada estudiante debe realizar el pago estipulado a la Confirmación de Matrícula.
**Proceso de Matrícula**
La Matrícula es el proceso en el cual los estudiantes admitidos en el proceso de inscripción hacen la matrícula en la UO. Para ello, los especialista con permiso de realizar matrícula entrarán al sistema los datos del candidato admitido que está matriculándose. Es importante destacar que se deben utilizar los datos del candidato admitido que el sistema posee, pues en el proceso de candidatura fueron entrados en el sistema. 
Una vez iniciada la matrícula se cerrará automáticamente (si se encuentra activo) el proceso de inscripción correspondiente al año académico.
Para matricular cada estudiante debe realizar el pago estipulado a la Matrícula.

Tanto en el proceso de Matrícula como en la Confirmación de Matrícula deben quedar almacenado los siguientes datos de los estudiantes:

_Personales_:
- **Nombre y Apellidos** (*)(Persona): El nombre completo, guardar nombre y cada apellido por separado debido a que es posible que sea necesario solo usar parte de este en los reportes.
- **Fecha de nacimiento** (*)(Persona): Mostrar un control que permita escoger la fecha de nacimiento.
- **Edad** (*)(Persona): Esto es un campo requerido pero es redundante. Lo podremos obtener de la fecha de nacimiento. (NEW)
- **Natural** (*)(Persona): Si nació en Angola se debe seleccionar el municipio donde nació de los que están registrados en el sistema.
- **País de origen** (*)(Persona): Se debe escoger un país de los existentes en el sistema. (New)
- **País de residencia** (*)(Persona): Se debe escoger un país de los existentes en el sistema. (New)  
- **Género** (*)(Persona) : "Feminino" o "Masculino",  usar internamente los códigos `2` y `1` respectivamente y permitir que el usuario escoja uno de los dos.
- **Estado civil** (*)(Persona): Los posibles valores `Casado`(1),`Soltero`(2),`Divorciado`(3) y `Otro`(4), permitir escoger uno de los anteriores aunque internamente solo se guarde su codificación.
- **No. de Identidad** (*)(Persona): El número del documento de identidad. Como se manejan varios tipos de documentos de identidad no se pueden poner restricciones en cuanto al formato y longitud del mismo, pero es requerido. Dos personas no podrán tener un mismo No. de Identidad.
- **Tipo de documento de identidad (DI)** (*)(Persona): Escoger dentro de los que se han registrado en el sistema. Por defecto mostrar como primera opción `Billete de Identidade` que es el más común.
- **Nombre de la madre** (*)(Persona)
- **Nombre del padre** (*)(Persona)
- **Estado militar** (*)(Persona): `Civil`, `Militar` o `Policía`, escoger uno de estos, el más común es `Civil`.
- **Situación militar** (*)(Persona): "Receseamento Militar?" Puedo tomar los valores "Sim" o "Não". Cada uno de estos valores posee la codificación 1 y 2 respectivamente. (New)

_Laborales_:
- **Condición** (*)(Estudiante): escoger entre trabajador o no trabajador, es posible que sea mejor plantearlo en forma de pregunta: ¿es trabajador?
- **Profesión**:(Estudiante) en caso de que sea trabajador especificar la profesión.
- **Nombre del trabajo**:(Estudiante) Nombre del trabajo al que pertenece.
- **Provincia donde su ubica el trabajo**:(Estudiante) Provincia donde se ubica el centro de trabajo. 
- **Tipo de Institución Laboral**: (Estudiante) (1 dígito) 1 si es pública y 2 si es privada. (New)
- **Salida con título**: (Estudiante)¿tiene salida con título? En caso positivo escoger entre Bacharelato, Licenciatura o Licenciatura bietápica. Cada una de estas 3 categorías posee un código; los mismos son 1, 2 y 3 respectivamente. (New)

_Datos de contacto_:
- **Provincia** (*)(Persona): Seleccionar la provincia de residencia de las que están registrados en el sistema.
- **Municipio** (*)(Persona): Seleccionar el municipio de residencia de los que están registrados en el sistema y pertenezcan a la provincia antes seleccionada.
- **Comuna** (*)(Persona): Escoger de las que se encuentran registradas para el municipio antes seleccionado.
- **Dirección** (*)(Persona):
- **Teléfono** (Persona): Número de teléfono.
- **Teléfono alternativo** (Persona): Número de teléfono.
- **e-mail** (Persona): Dirección de correo electrónico.

_Procedencia_:
- **Habilitación** (Estudiante): nivel alcanzado en el nivel anterior, por ejemplo: 11no, 9no, etc. El valor más común es 12.
- **Escuela de procedencia** (*)(Estudiante): Escoger de las escuelas de enseñanza media registradas en el sistema.
- **Tipo de enseñanza media de procedencia** (*)(Estudiante): Escoger el tipo de enseñanza media de procedencia de donde viene el candidato.
- **Carrera de procedencia** (*)(Estudiante): Nombre de la carrera de la que procede, restringir a 20 caracteres.
- **Año de conclusión** (*)(Estudiante): Año en que termino carrera de procedencia.
- **Media final de la Enseñanza Media** (*)(Estudiante): Nota promedio en la enseñanza media. (New)

_Institución_:
- **Unidad Orgánica** (Estudiante): La unidad orgánica a la que pertenece, dar la posibilidad de escoger de las que estén registradas en la base de datos, cuando se presente el formulario mostrar por defecto la primera que se encuentre en la base de datos.
- **Forma de acceso** (*)(Estudiante): Se debe escoger entre "EXAME DE INGRESSO", "GRADUADO UNIVERSITARIO", "OUTRA" y "CONCURSO ACADEMICO". Cada una de las anteriores categorías posee la codificación 01, 02, 03 y 04 respectivamente. (New)
- **Necesita educación especial** (*)(Estudiante): en el caso de de que se marque la necesidad de educación especial se deben seleccionar además las discapacidades del candidato.
- **Documentos** (Estudiante): `Certificado original` (1), `Cópia de documento` (2), `Documento de trabajo` (3), `Documento Militar` (4), `Internato` (5), escoger 0 o más de estos.
- **Carrera matriculada** (*)(Estudiante): En caso de que sea un candidato Admitido sería la carrera que se le asignó. En caso de ser un estudiante continúante sería la carrera que ya matriculó en años anteriores. (New)
- **Modalidad de enseñanza** (*)(Estudiante): Código de la modalidad de de enseñanza, pueden ser "Ensino Presencial", "Semi-presencial" o "A Distancia". Los mismos poseen como código 1,2 y 3 respectivamente. Por defecto estará "Ensino Presencial". (New)
- **Nivel académico** (*)( Matricula o Confirmación de matricula ): Puede ser uno de los niveles activos en el sistema. Este campo no podrá ser modificado por la persona que matricula, es un dato informativo. Por el momento se establecerá el nivel académico "1º", que es el que matricularán los candidatos admitidos. (New)
- **Situación académica**(*)(Matricula): Se seleccionará una de las opciones siguientes: "1ª Matrìcula-Novo", "Aprovado em toda-ano anterior", "Aprovado com Cadeiras em atraso", "Repetentes", "Transferencia", "Reprovado", "Licença por Doença", "Continuante bacharelato", "Estagio" y  "Preparação de tessis". Estas opciones poseen el código 1,2,3,4,5,7,9,10,11 y 12 respectivamente. (New)
- **Estado en la UO**(*)(Estudiante) De acuerdo a los pagos y acciones correspondientes a los procesos de Matrícula y Confirmación de matrícula que haya realizado cada estudiante, se le dará una clasificación. Las mismas pueden ser SIN MATRICULAR CON DEUDA, cuando el estudiante no se ha matriculado o no ha confirmado matrícula y posee deudas, como por ejemplo que no ha pago lo establecido para matricular; SIN MATRICULAR, el estudiante no tiene deuda (por el momento pagó lo establecido para la matrícula o la confirmación) pero no se ha reportado para confirmar sus datos en el sistema y dejar concluida la matrícula o confirmación de matrícula; MATRICULADO CON DEUDAS, el estudiante ha realizado la matrícula o confirmación con éxito pero posee deudas (este aspecto por el momento no lo trabajaremos, lo utilizaremos cuando implementemos el tipo de emolumento "Propina" que es el pago que debe realizar cada estudiante en cada mes del año académico); MATRICULADO, el estudiante ha matriculado o confirmado matrícula con éxito y no tiene deuda alguna.
- **Internado** (*)(Estudiante): Indicar si el estudiante está internado en una residencia estudiantil. "Internato?". Puede tomar los valores "Sim" o "Não". Estos valores poseen el código 1 y 2 respectivamente. Por defecto estará "Não". (New)
- **Año en que realizó la primera matrícula en el IES que se está a matricular** (*)(Estudiante): (Instituto de Educación Superior). (New)
- **Año en que realizó la primera matrícula en la ES**(*)(Estudiante): (Educación Superior). (New)
- **Bolsa de estudio**: Puede ser "Aproveitamento academico-referencia", "Careccia de recurso do agregado familiar", "Comportamento Exemplar do estudante", "Idade regilamente frequentar o superior", "Bolsa externa", "Bolsa de Credito Interno", "Bolsero de Institucion (funcionario)" o "Sim bolsa". Estas opciones poseen la codificación A, B, C, D, E, G, H y N respectivamente. Por defecto estará en "Sim bolsa". (New)
- **Número de expediente** (*)(Estudiante): Es el número asignado cuando se inscribió. (Ver en el sistema pues debe ser solo de 4 dígitos y no de 5 como está ahora). En este tengo mis dudas. Lo que propongo es mantener el valor tanto en la tabla Estudiante como en Candidatura, o incluir en la tabla Estudiante un campo que tenga el id de la candidatura, de esa manera se sabrá el Número de expediente.  
- **Régimen**(*): En caso de ser la primera matrícula debe colocarse el régimen por el cual optó en la matrícula. En caso de ser continúante se debe mantener el régimen que ya en algún momento se había insertado. 
- **Media de las notas de los exámenes de acceso** (*)(Estudiante): Media obtenida en los exámenes de acceso. Este campo no será modificable. Es un campo que es redundante para los que realizaron los exámenes de acceso en el sistema pero no se puede obviar pues al existir estudiantes de traslado (no se poseen sus notas en los exámenes de acceso) es necesario. (New)
- **Data de las actualizaciones**(Estudiante): (10 dígitos) Fecha en que realizar anulación de matrícula (baja) o transferencia (alta). (New)
- **Causa de las actualizaciones**(Estudiante): (10 dígitos) Motivo de interrupción de estudio (baixa) o transferencia (alta). (New)
- **Número mecanográfico**(Estudiante): Es un número que identificará al estudiante en la universidad. Está compuesto por 12 dígitos. Los dos primeros corresponde al código de registro de la unidad orgánica, asignado por el IES. Los siguientes 2 corresponden al código que el IES le otorga a cada una de sus carreras. Los siguientes 2 corresponden a los 2 últimos dígitos del año en que el estudiante matriculó en el IES. El dígito siguiente estará de acuerdo al sexo del estudiante (1 si es de sexo masculino, 2 si es sexo femenino). Los últimos 5 dígitos serán números consecutivos de los estudiantes pertenecientes a una UO, Carrera y año específico. El sexo no influirá en estos números consecutivos.
- **Turma**(Estudiante): (10 dígitos) Es el grupo que se le asigna al estudiante, por ejemplo Turma A. (New)  

Nota: Si aparece (Persona) es porque creo debe ir en la tabla Persona y si aparece (Estudiante) es porque creo debe ir en la tabla Estudiante.

**Comment by eadomenech** [comment]
Ya actualicé la historia de la matrícula. Mañana continúo con las funcionalidades como tal. Pero creo que con esto ya puedes hacer alguna que otra cosa.

**Comment by eadomenech** [comment]
He pasado todo lo relacionado al proceso de matrícula para otro sprint (Millestone Sprint 11)

**Comment by ybenitezf** [comment]
Por lo que entiendo de esto que describes aquí ¿tu piensas que deben introducirse los datos en cada confirmación de matricula? es decir todos los datos del estudiante ?

**Comment by eadomenech** [comment]
No. Pero sí se hace una actualización. Por ejemplo, la dirección y
teléfono del estudiante puede cambiar y en la confirmación se
actualizan estos campos entonces.
A eso añádele además lo siguiente:
Recuerda que tenemos una base de datos en mysql con muchos datos de
todos los estudiantes continuantes y de esa base de datos tendremos
que exportar esos datos para iserirlos en nuestra base de datos, de
tal forma que cuando se vaya a realizar la confirmación ya los
estudiantes aparezcan pero evidentemente habrá que completar algunos
campos que el siga viejo no recoge y además hay que actualizar algunos
que el siga viejo recogía de forma erronea, como por ejemplo lugar de
nacimiento puesto que el siga viejo no tenía las comunas y realmente
en este campo lo que pide el minesterio es la comuna.

El 16/12/15, Yoel Benítez Fonseca notifications@github.com escribió:

> Por lo que entiendo de esto que describes aquí ¿tu piensas que deben
> introducirse los datos en cada confirmación de matricula?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/57#issuecomment-165116642

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
Creo que la en la confirmación de la matricula no se deberían tratar esos datos, mira en cualquier momento se pueden editar los datos de una estudiante, eso es una cosa, y otra muy diferente es la confirmación de la matricula (que no significa confirmar todos los datos del estudiante), no se si me entiendes.

En cuanto a los de importar los datos de los estudiantes antiguos, es un problema completamente diferente que habrá que tocarlo de otra manera, no mezcles las cosas, yo creo que a la hora de confirmar la matricula se debe agregar o pedir los datos que faltan no todos los que ya se tiene, ya que la opción de cambiar cualquiera de los datos anteriores ya existían de ante mano.

**Comment by eadomenech** [comment]
Es cierto que los datos pueden ser modificados en cualquier momento,
pero el tiempo establecido y que tienen por obligación los estudiantes
para actualizar sus datos es el de la confirmación de matrícula. No es
solo el sistema, la universidad tiene establecida una planilla de
confirmación de matrícula con todos esos datos y que los estudiantes
de forma obligatoria tienen que llenar.

El 16/12/15, Yoel Benítez Fonseca notifications@github.com escribió:

> Creo que la en la confirmación de la matricula no se deberían tratar esos
> datos, mira en cualquier momento se pueden editar los datos de una
> estudiante, eso es una cosa, y otra muy diferente es la confirmación de la
> matricula (que no significa confirmar todos los datos del estudiante), no se
> si me entiendes.
> 
> En cuanto a los de importar los datos de los estudiantes antiguos, es un
> problema completamente diferente que habrá que tocarlo de otra manera, no
> mezcles las cosas, yo creo que a la hora de confirmar la matricula se debe
> agregar o pedir los datos que faltan no todos los que ya se tiene, ya que la
> opción de cambiar cualquiera de los datos anteriores ya existían de ante
> mano.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/57#issuecomment-165125813

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
¿que quieres decir? ¿que los estudiantes tendrán que rellenar los datos? esta que la escuela pueda tener esos establecido así, los estudiantes rellenar ese formulario en papel y de ahí regresa a nosotros donde será un operador el que los rectifique los datos si es necesario, y con esto volvemos a los mismo:

Explicame paso a paso como si ya estuviera implementado el sistema como crees que sería la interacción con el sistema.

**Comment by eadomenech** [comment]
Explico.
En cada uno de estos procesos se habilitan de 5 a 6 aulas con 3
computadoras en cada sala. La escuela contrata especialista que
trabajan en esos ordenadores. Los estudiantes llenan en papel una
plantilla que recoge todos o la mayoria de los datos necesarios. El
estudiante va a donde está uno de los especialista y entrega tanto la
planilla como el carnet de identidad y el especialista mediante el
sistema comprueba que todos los datos que están en el sistema se
corresponden con la planilla y carnet de identidad. Además el
especialista le comunica al estudiante la carrera, régimen, nivel
académico y grupo en que estará. Aquí hay sus cosas, como el siga
viejo no lo hace y este tampoco, existen unos excel donde aparecen las
notas de cada uno de los estudiantes durante el tiempo que lleva en la
universidad, por ese excel y teniendo en cuenta la cantidad de
asignaturas que tiene el estudiante desaprobadas se decide si el
estudiante repetirá el nivel académico y si pasa al siguiente. Debes
saber que es en este momento cuando unos cuantos estudiantes se
enteran que están suspendidos y entonces piden un tiempo para hablar
con el profesor y paga y todo lo demás que te puedas imaginar. La
concreta es que que el especialista no lo confirma al siguiente nivel
académico si el estudiante posee un número X de asignaturas
desaprobadas.
Lo otro es que un estudiante por razones X puede cambiar de régimen y
esto debe ser actualizado en el sistema y por tanto cambiarlo de
grupo.

El 16/12/15, Yoel Benítez Fonseca notifications@github.com escribió:

> ¿que quieres decir? ¿que los estudiantes tendrán que rellenar los datos?
> esta que la escuela pueda tener esos establecido así, los estudiantes
> rellenar ese formulario en papel y de ahí regresa a nosotros donde será un
> operador el que los rectifique los datos si es necesario, y con esto
> volvemos a los mismo:
> 
> Explicame paso a paso como si ya estuviera implementado el sistema como
> crees que sería la interacción con el sistema.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/57#issuecomment-165128379

## 

Saludos,
  Ernesto.

**Comment by ybenitezf** [comment]
aquí en los datos laborales no incluiste la provincia de trabajo, en la parte de iniciar una candidatura si esta ? ¿es que se te olvido o que no hace falta el dato?

**Comment by eadomenech** [comment]
Se me olvido. Recuerda q eso surgio luego. Eso va tambien.

**Comment by ybenitezf** [comment]
¿ya terminamos con esto?
