### ISSUE TITLE
Error al cambiar la provincia a crear un candidato

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#59]
Cuando se va añadir un candidato y se cambia la provincia donde reside, de forma automática se ponen los municipios que pertenecen a esta provincia, PERO las comunas no se actualizan de forma automática al cambiar la provincia.

**Comment by ybenitezf** [comment]
Si, me di cuenta de ese problemilla, pero no es tal, de todas formas el
segúndo paso ahí siempre es escoger el municipio y en cuanto este cambie se
actualizan las comunas, no se porque el JS no me corre como debe, en eso
perdí muchisimo tiempo hasta que me di cuenta que no hay que ser tan
esquisito. De momento te propongo dejarlo así.

2015-06-25 3:24 GMT-04:00 Ernesto Avila Domenech notifications@github.com:

> Assigned #59 https://github.com/yotech/agis/issues/59 to @ybenitezf
> https://github.com/ybenitezf.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yotech/agis/issues/59#event-339744543.

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
Jefe, creo que este issue vale la pena cerrarlo, te explico:
1. No encuentro forma de arreglarlo, JS simplemente no me hace caso.
2. La mayoría de la veces cuando se vayan a introducir los datos de una persona, siempre se escoge provincia, municipio y comuna en ese mismo orden y en el momento que se cambie el municipio ahí mismo se actualizan las comunas.

Mira  a ver que crees, yo lo cerraría ya que no es un "stopping issue" y no afecta ni en funcionamiento ni en rendimiento.

**Comment by ybenitezf** [comment]
Tengo una idea para resolver esto, pero requiere tiempo y meterme en cosas que me complicarían un poco la vida... vamos de dejarlo por aquí mientras.

**Comment by eadomenech** [comment]
OK esto no es algo que me preocupe tanto. Déjalo para después.
