### ISSUE TITLE
Gestionar Carreras

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#6]
El sistema debe poder adicionar, modificar y eliminar las carreras a impartir en la UO. Las carreras tienen un nombre y pertenecen a un área del conocimiento según el ministerio y su código (1 caracter) correspondiente. También poseen un área del conocimiento según el Plan Nacional de Formación de Quadro y su código (2 caraceres) correspondiente, un grupo de sectores de la UNESCO y su código (3 caracteres) correspondiente, un código de registro conformado por 9 caracteres (1:código de área del conocimeineto según ministerio; 2:código del área del conocimiento según PNFQ; 3:código del sector de la UNESCO y 3:números consecutivos y secuenciales) y un código asignado por el IES al que pertenece la UO que impartirá el curso.

**Comment by eadomenech** [comment]
Te envié un correo donde su adjunto trae las carreras q se imparten en Angola  con sus datos respectivos.

**Comment by ybenitezf** [comment]
¿son todas las carreras? ¿qué hago con eso? ¿lo pongo ya como parte de la incialización?

**Comment by ybenitezf** [comment]
completado

**Comment by eadomenech** [comment]
Le falta el nombre del último campo a la hora de adicionar una carrera

**Comment by ybenitezf** [comment]
Saque del XSL que me viaste por correo el listado de las carreras y cree un archivo CSV que se importa en la tabla de las carreras la primera ves que se ejecuta la aplicación.

**Comment by ybenitezf** [comment]
Es parte del mismo error de la traducción, cuando vayas a probar las
cosas nuevas pon el navegador en Ingles, después que termines las
pruebas entonces pasa a PT y has la traducción

El 24/3/15, Ernesto Avila Domenech notifications@github.com escribió:

> Le falta el nombre del último campo a la hora de adicionar una carrera
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/6#issuecomment-85557767

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701
