### ISSUE TITLE
Incorreto código de la UO

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#60]
Según los datos que posee la UO es el código que ella posee. En estos momentos ese código se está generando erroneamente.

**Comment by ybenitezf** [comment]
más datos please

**Comment by eadomenech** [comment]
Las UO poseen un código de registro que está compuesto por 14 caracteres (los primeros 8 es el código del IES al que pertenece, luego 1 carácter correspondiente al nivel de agregación, luego 2 caracteres correspondientes a la clasificación y finalmente otros 3 que representan un número sequencial/consecutivo. 

**Nivel de agregación (1 caracter)**
- Sede Central (1)
- Unidad orgánica (0)

**Clasificación de la Unidad Orgánica (2 caracteres)**
- Institutos Superior (20)
- Institutos Superior Técnico (21)
- Institutos Superior Politécnicos (22)
- Escolas Superior (30)
- Escolas Superior Técnicas (31)
- Escolas Superior Politécnicas (32)
- Academias (40)
- Faculdades (50)
- Departamentos (60)
- Centros de Investigação Científica (70)

**Número secuencias (3 caracteres)**

En cuanto a los 8 primeros caracteres, que es donde creo hay problema, te pongo un ejemplo.
Si la Universidade Kimpa Vita fuese la octava IES a ser registrada en el Ministerio entonces su código seria 07101008 siendo 07 el código de la respectiva Región Académica, 10 o código de clasificación de la IES que en este caso es una Universidad, 1 la naturaleza de la IES en este caso pública y 008 el número secuencial indicando que fue la octava IES a ser registada en el Ministerior.

En el caso de nuestra app, al cambiar el IES a la 4ta Región Académica que es a la que pertenece mi escuela, el número debe comenzar con 04 y no con 07 como está. Así es posible que pase con los otros caracteres, que al modificar el IES no se actualiza el código y luego ese código se utiliza en el código de las UO.

**Comment by ybenitezf** [comment]
me estas hablando del IES o de la UO, me perdiste ahi...unidad organica es lo que me parece debo revisar ¿no?

**Comment by eadomenech** [comment]
Yo creo que no. Que lo que tienes que ver es el IES. Pues modifico el IES y se queda el mismo código. Te lo puse en UO porque fue ahí cuando me di cuenta. Pero el error creo que viene de arriba, del IES. De todas formas no veo mal que veas los dos por si cometes el mismo error en UO.

**Comment by ybenitezf** [comment]
ya, ya vi donde es el problema, el campo código de la unidad orgánica se calcula una sola ves cuando se insertan los datos y no se actualiza nunca, es decir lo que hay que haces es mandar a re-calcular el código cuando los datos de la escuela a la que pertenece la UO cambien.

Ahora no recuerdo, pero me parece que de los datos de una unidad orgánica no depende el código de nadie más verdad ?

**Comment by eadomenech** [comment]
el código de la UO depende del código del Instituto de Educacion Superior (IES), los 8 primeros caracteres de la UO son los del IES al que pertenece.
