### ISSUE TITLE
Error al crear una nueva UO

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#61]
Eliminé la que viene por defecto y creé una nueva. Todo corrió bien pero cuando sale la lista de las UO, aparecen los campos Nivel de agregación y Clasificación en blanco. Lo que me extraña es que cuando doy editar esa UO esos campos si aparecen como cuando agregué la UO, es decir que de algún modo lo está guardando. Busqué en la base de datosy esos campos aparecen vacios también. 

Otra cosa:
En caso de editar la UO que vien por defecto o eliminarla y crear una nueva, da error la selección de los régimes existentes en esa UO. 
El problema está en la línea 164:
    unidad_organica_id = escuela.obtener_sede_central().id

**Comment by ybenitezf** [comment]
por supuesto que tiene que dar error al asignar regimenes si no existe una unidad organica a la que asignarlos

**Comment by eadomenech** [comment]
No me tomes tampoco por burro. Lee bien lo que te pongo. Siempre te puse "Al eliminar la que viene por defecto y crear una nueva" o "Modificar el campo Nivel de agregación" en la que está por defecto. En ambos casos da error.

**Comment by ybenitezf** [comment]
a ver si aclaramos esto de una ves ¿no es obligatorio que exista una sede central para la escuela? por que todo eso fue implementando con esa idea. Por eso al no tener ninguna unidad organica marcada como sede central  da error
