### ISSUE TITLE
Problema al asignar las plazas de estudiantes

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#62]
Cuando se van a asignar las plazas disponible, ocurre que si el usuario intenta asignar para un mismo año académico, en una misma carrera y en un mismo régimen, entonces el sistema le permite hacerlo y no debe hacerlo. Es decir, será única la asignación para un mismo (año académico, carrera, régimen). Aquí sugiero hacerlo como lo hacías en otra parte. Si se asigna para el año 2015, en la carrera de Informática y régimen Regular, la cantidad X, entonces o se podrá asignar otra cantidad para ese mismo año, carrera y régimen. Si ese número varía entonces lo que se debe hacer es modificar esa tupla.

**Comment by eadomenech** [comment]
Asignando

**Comment by ybenitezf** [comment]
es lo mismo que el issue #56, lo voy a cerrar.
