### ISSUE TITLE
Error en la Gestión de Planes Curriculares

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#64]
Una vez que se han agotado las disciplina el sistema adiciona y no debería hacerlo. El sistema solo necesita un nivel de acceso y realmente debe nevesitar de una disciplina también. En caso de no haber disciplinas disponibles se debe informar al dar clic en el + y no se debe acceder al formulario de adicción de la disciplina al plan curricular.

**Comment by ybenitezf** [comment]
¿qué es una disciplina? supongo te refieres a las asignaturas ¿no?

2015-07-09 3:53 GMT-04:00, Ernesto Avila Domenech notifications@github.com:

> Assigned #64 to @ybenitezf.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/64#event-351596930

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by eadomenech** [comment]
Si Es asignatura

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 9 de julio de 2015 13:48:36 Yoel Benítez Fonseca 
notifications@github.com escribio:
