### ISSUE TITLE
Asignar sala a los exámenes de acceso I

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#66]
Para asignar la(s) sala(s) a los exámenes de acceso, es conveniente tener en cuenta lo siguiente:
- **1:** Se accederá desde el menú principal en Docentes->Candidatos->Exámenes de acceso.
- **2:** Al dar clic en lo antes descrito aparecerá la lista de todos los exámenes de acceso a realizar. Se define examen de acceso a la entidad (ref_ano_academico, fecha, periodo, ref_asignatura), siendo ref_ano_academico igual al año académico del evento Inscripción en activo y estando ref_asignatura  en la INTERSECCIÓN de los conjuntos "asignaturas que pertenezcan al nivel académico Acesso", "asignaturas que pertenezcan a los planes curriculares activos" y "asignaturas necesarias a examinar por al menos un estudiante de los inscriptos en el año académico igual al del evento Inscripción en activo". Explico a continuación con más detalles: Las asignaturas que aparecerán para examinar serán las que se les haya asociado en algún plan curricular, que esté en activo, con el nivel académico "Acesso" y que además sea necesaria a examinar, esto último es lo siguiente; puede pasar que un plan de estudio vaya cerrándose, y otro de la misma carrera esté abriéndose, siendo las asignaturas a examinar para su acceso diferentes. Como a la hora de introducir los datos de los candidatos habrá que ponerle el Plan de Estudio al que optará, entonces se podrá definir qué asignaturas serán necesarias para Admitir o no. 
- **3:**  Los campos de esta lista serán: Nombre de la asignatura, Cantidad de estudiantes a realizarla, Fecha y Periodo. Además tendrá a la derecha de todos estos campos un vínculo llamado "Lista".
- **4:** El campo "Cantidad de estudiantes a realizarla" no será editable e indicará la cantidad de estudiantes que harán examen de dicha asignatura. Es posible que varias carreras tengan que realizar una misma asignatura para seleccionar los estudiantes que la cursarán. Evidentemente este campo será la suma de todos ellos.
- **5:** El campo "Fecha" será editable y significará la fecha en que se realizará el examen.
- **6:** El campo "Periodo" será editable y significará el periodo en que se realizará el examen. Existirán 3 periodos: "Mañana", "Tarde" y "Noche".
- **7:** El vínculo "Lista" es descrito en el issue llamado #67  "Asignar sala a candidato para realizar examen de acceso II".

**Comment by ybenitezf** [comment]
Aquí:
- **2:** Al dar clic en lo antes descrito aparecerá la lista de todos las asignaturas entradas al sistema y que pertenezcan al nivel académico "Acceso". Los campos de esta lista serán: Nombre de la asignatura, Cantidad de estudiantes a realizarla, Fecha y Periodo. Además tendrá a la derecha de todos estos campos un vínculo llamado "Lista". 

No tengo ningún vinculo hasta el momento entre asignatura y nivel académico, supongo habrá que buscar la forma de crearlo.

**Comment by ybenitezf** [comment]
la relación entre asignatura y nivel académico está en el plan curricular

**Comment by ybenitezf** [comment]
¿la lista de todos las asignaturas entradas al sistema y que pertenezcan al nivel académico "Acceso"? para el curso académico nuevo no ? o todas las asignaturas...

**Comment by eadomenech** [comment]
Para el año académico correspondiente con el evento de inscripción activo.

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 15 de julio de 2015 13:39:43 Yoel Benítez Fonseca 
notifications@github.com escribio:
