### ISSUE TITLE
Asignar sala a candidato para realizar examen de acceso II

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#67]
- **1:** Aparecerá la lista de todos los candidatos que realizarán la asignatura, en un "grid".
- **2:** Los campos a mostrar serán: Nº de Inscripción, Nombre completo, Nº de identidad y Sala de aula.
- **3:** Además a la derecha de los campos anteriormente descriptos, habrá un checkbox.
- **4:** En la fila de encima, donde aparecen los nombres de los campos, aparecerá a la derecha un checkbox también, que al marcarlo marcará todos los checkbox de cada candidato.
- **5:** En alguna parte de este formulario, donde sea más conveniente según tu criterio, aparecerá un listbox para seleccionar una de las salas de aula existentes en el sistema.
- **6:** Cuando se escoja una determinada sala y se de en un botón "Aceptar", todos los candidatos que tengan el checkbox activado se ubicarán en esa sala de aula. Además serán actualizados sus respectivos campos "Sala de aula".
- **7:** Por defecto el campo "Sala de aula" será "Sin asignación".

Nota: En caso de no entender al 100% me dices y hago una imagen parecida a la que subí hoy.

**Comment by ybenitezf** [comment]
Aclarando algunas cosas:
1. "Salas de aulas" supongo se refiere a las aulas que se gestionan en "Configuración"->"Institución"->"Infraestructura"->"Gestionar Aula" ¿no?
2. "Candidato" no existe, lo que existen son estudiantes que tienen una o más **candidatura**
3. De lo que explicas aquí supongo qué ¿hay que agregar a la relación **candidatura** un campo nuevo que haga referencia a la relación **aula**?.

**Comment by eadomenech** [comment]
Duda # 1: Si, así mismo como dices.
Duda # 2: Se refiere a "candidato" al estudiante que tenga como estado "Inscripto". Como tengo concebido el sistema es de la siguiente manera. Una vez que se califiquen las pruebas y se lancen las notas, no existirá ningún estudiante con estado "Inscripto", estos pasarán a "Admitidos" o "No admitidos" según sus resultados. Los que no pagaron, que tienen como estado "Inscripto con deuda" quedarán así mismo "Inscriptos con deudas". Al final no tendremos a nadie con estado "Inscripto".
Duda # 3: Me imagino que si. Se le agrega el campo nuevo, perteneciente a la sala, a la relación estudiante-ano académico-asignatura.    

Aquí hago algunos cambios para tratar de explicarte mejor.
- **1:** Aparecerá una lista ("grid") de todos los estudiantes con estado "Inscripto", que realizarán la asignatura y que hayan realizado inscripción en el mismo año que el evento de tipo Inscripción que se encuentre activo. Para saber si realizarán la asignatura se tendrá que tener en cuenta las carreras por la que opta el estudiante y si la asignatura en que se está pertenece al plano curricular de alguna de las dos carreras por la que opta el estudiante. Aquí me doy cuenta que a la hora de inscribir a los estudiantes hay que ponerle al lado de las 2 carreras que opta el estudiante los planos correspondiente a esta para que se seleccione uno. Eso lo pondré en otro issue. 
- **2:** Los campos a mostrar serán: Nº de Inscripción, Nombre completo, Nº de identidad y Sala de aula.
- **3:** Además a la derecha de los campos anteriormente descriptos, habrá un checkbox.
- **4:** En la fila de encima, donde aparecen los nombres de los campos, aparecerá a la derecha un checkbox también, que al marcarlo marcará todos los checkbox de cada candidato. No se si entendiste lo de los checkbox, la idea es que en algunos casos no es necesario marcar todos los checkbox. Hay casos que se conocen que todos caben en una misma sala y por eso se marca solo un checkbox y activa lo de todos los estudiantes.
- **5:** En alguna parte de este formulario, donde sea más conveniente según tu criterio, aparecerá un listbox para seleccionar una de las salas existentes en el sistema y que tenga capacidad para aceptar a la cantidad de estudiantes que se han marcado con el checkbox. Por supuesto que se debe calcular la cantidad de estudiante que se han asignado a dicha sala en igual fecha y periodo e irla comparando con la capacidad que tiene la sala. 
- **6:** Cuando se escoja una determinada sala y se de en un botón "Aceptar", todos los candidatos que tengan el checkbox activado se ubicarán en esa sala de aula. Además serán actualizados sus respectivos campos "Sala de aula".
- **7:** Por defecto el campo "Sala de aula" será "Sin asignación".
