### ISSUE TITLE
Corrección de los Niveles Académicos

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#68]
Por la forma en que estoy concibiendo el funcionamiento del sistema, no tiene cabida gestionar los niveles académicos como están ahora. Por lo que es necesario tener los niveles académicos bien definidos desde el inicio. Luego en el sistema se escogerán cuales de los niveles académicos se emplearán en la UO.
Es decir, hay que hacer con los niveles académicos lo mismo que hacemos con los regímenes.  Con la diferencia que los que estén en el sistema desde el inicio no sean modificables ni se puedan eliminar.

**Comment by ybenitezf** [comment]
como siempre, unas descripciones "super detalladas" de como quieres
que quede la cosa....

2015-07-09 17:11 GMT-04:00, Ernesto Avila Domenech notifications@github.com:

> Assigned #68 to @ybenitezf.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/68#event-352335130

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by eadomenech** [comment]
Los niveles académicos se gestionarán de la siguiente manera:
- **1:** Los niveles académicos definidos en el sistema serán: "Acesso", "1º Ano", "2º Ano", "3º Ano", "4º Ano" y "5º Ano".
- **2:** Aparecerán los niveles académicos ya existentes en la UO en un "grid".
- **3:** Se podrá adicionar mediante el botón "+" del "grid" un nivel académico de los definidos y que no esté ya en la UO.
- **4:** A la derecha, en la lista de los niveles académicos, no se permitirá la modificación. Solo se permitirá eliminarlo de la UO.

**Comment by ybenitezf** [comment]
Voy a hacerles la siguiente asignación de códigos a los niveles:
1. "0" será "Acceso"
2. "1" será "1ro"
   ... y así sucesivamente.

En la gestión de nivel de acceso la UI será como en la imagen adjunta
![niveles](https://cloud.githubusercontent.com/assets/8646381/8679496/fb26abbc-2a28-11e5-8622-de386b155053.png)

**Comment by eadomenech** [comment]
Veo bien eso De hecho te lo iba a proponer Llega hasta el 7 Finalista

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 14 de julio de 2015 18:05:31 Yoel Benítez Fonseca 
notifications@github.com escribio:

**Comment by ybenitezf** [comment]
umm... ok, 7 agregado
