### ISSUE TITLE
Error en la Gestión de Planos Curriculares

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#69]
El campo "Nombre", perteneciente al nombre del plano, debe ser único para cada carrera. Es decir, no pueden existir dos planos con el mismo nombre y que pertenezcan a la misma carrera.

**Comment by ybenitezf** [comment]
Man en eso no estoy de acuerdo contigo, tu mismo casi lo dices, por ejemplo supón que es el "PLAN C", se supone que no es el mismo plan en carreras diferentes aunque se llamen igual, pero bueno, tu mismo, yo le pongo la restricción.
