### ISSUE TITLE
Gestionar Régimes

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#7]
El sistema debe poder adicionar, modificar y eliminar los régimes. Por defecto tendrá 2 régimes (Regular y Post-Laboral). Los régimenes poseen un nombre y una abreviatura.

**Comment by ybenitezf** [comment]
¿La abreviatura del regimen de cuantos caracteres estamos hablando ?

**Comment by eadomenech** [comment]
Una letra
R: Regular
P: Pos-Laboral

**Comment by ybenitezf** [comment]
esto lo acamodo en la sección 'general' o de la escuela ?

**Comment by eadomenech** [comment]
Lo mismo que las carreras. Se gestionan en General y se dice en Escuela cuales regimenes se utilizan en la escuela.

**Comment by ybenitezf** [comment]
ufff que feo, eso lo complica más de lo que esperaba

**Comment by ybenitezf** [comment]
¿los regimenes se asocian a la escuela o a una unidad organica concreta ?

**Comment by eadomenech** [comment]
La escuela es lo mismo q la unidad orgánica. Los régimes se asocian a las UO.
