### ISSUE TITLE
Examen de acceso

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#70]
Todos los aspirantes a ingresar a alguna de las carreras del centro de estudios superiores (IES) debe realizar los exámenes de acceso para las carreras a las cuales candidata (deben ser 2 carreras a lo sumo). 

Antes de que a cualquier candidato se le oriente los exámenes a realizar este debe haber realizado los pagos de inscripción descritos en la historia #39 y su estatus debe aparecer como **Inscrito**.

Se realizará un examen de acceso por cada una de las asignaturas que pertenezcan al _plan de estudios_ o _plan curricular_ activo de las carreras por las cuales se candidata. 

Estos exámenes se realizarán en una o más de las aulas definidas para este propósito por la unidad orgánica. Es posible que por la cantidad de estudiantes a realizar el examen se necesite más de un aula para el mismo debido a que las asignaturas a examinar pueden ser comunes para varias carreras.

La fecha de examen se definirá por la unidad orgánica y se dará a conocer, junto con el lugar (aula) con antelación los estudiantes que deben realizar dicho examen. Además se especificara un período para el examen que podrá ser uno de: "mañana", "tarde" o "noche"

Todo este proceso debe ocurrir dentro del marco de tiempo del _evento de tipo inscripción_ para el año académico actual o siguiente.

**Comment by ybenitezf** [comment]
Cerré los issues #66, #67 y #53, todos están descritos en esta historia. Si es necesario hacer algún cambio o algo de lo escrito es incorrecto, corregirlo arriba y agregar un comentario a esta conversación con los detalles.

**Comment by eadomenech** [comment]
Esto lo veo ok

**Comment by ybenitezf** [comment]
¿Qué lo "ves OK" supongo significa que es así mismo como ocurre?

**Comment by eadomenech** [comment]
Si, así mismo ocurre.

**Comment by ybenitezf** [comment]
actualizada para incluir la descripción del período de los exámenes.

**Comment by ybenitezf** [comment]
La próxima vez que yo te pida que revises algo no seas vago y hazlo a conciencia.

Lo que me mandaste por correo: ---
Cuando un estudiante hace el pago de la inscripción es porque ya se
introdujo al sistema todos sus datos incluyendo las 2 carreras a las
que está optando. Está claro que haciendo una unión U entre los
conjuntos de las asignaturas que pertenecen al nivel “Acceso” de las 2
carreras se tendrán las asignaturas que tendrá que examinar dicho
estudiante.
Supongamos que ya se han asignado aulas a los exámenes. En este caso
lo que se haría es agregar una tupla en la entidad que acabamos de
crear. A este estudiante se le ubica en una sala de las que fueron
asignadas a los exámenes. Luego se va asignando a estudiantes en esta
misma aula que fue asignado el primer estudiante, hasta llegar al
límite de capacidad de dicha aula. En caso de llegar al límite se
ubicaría en otra aula asignada a este examen.
Puede pasar que se agoten las aulas asignadas a los exámenes pero
vamos a ver el peor de los casos que al final es lo mismo. Supongamos
que no se han asignado aulas a ninguno de los exámenes. Cuando el
estudiante candidato paga la inscripción, al no existir aulas no se
hace nada con la entidad que creamos Candidatura-Examen-Aula (CEA)
pero si se informa en un panel informativo que existirá en la página
principal del sistema. En la pantalla principal habrá un panel
informativo para cada evento que se encuentre en activo, en este caso
“Inscripción 2016”. Ahí se informará que existen estudiantes inscritos
que no han sido ubicados por falta de salas de aula, evidentemente
especificando en qué examen es que está ocurriendo esto. Esto puede
ser en forma de gráfico o como quieras, en este momento como más
sencillo te sea, luego lo haremos en forma de gráficos como especie de
pastel para cada examen (un color para el por ciento que no ha sido
ocupado y otro para el que ya ha sido ocupado). Bueno, en este caso
que estamos analizando se informaría que no existen salas de aulas
disponibles y por tanto no se han ubicado algunos estudiantes. En ese
caso el usuario debe ir y asignarle alguna sala al examen que lo
necesita, se haría como mismo lo hacemos ahora, solo que luego de
asignarselo se llamaría a un método que compruebe si existen
estudiantes a los que no se les ha asignado aula correspondiente a
este examen. En caso de que existan entonces se ubican en esta nueva
sala de aula asignada  a este examen. Puede ocurrir que la nueva aula
asignada a este examen no cubra todos los estudiantes que faltan por
ubicar, en ese caso solo se actualizaria el por ciento de estudiantes
ubicados y no ubicados y el usuario tendría que crear otra sala de
aula para este examen.
El listado de los estudiantes por examen y aula estaría en dependencia
de la entidad CEA. Si en esa entidad no aparece el estudiante porque
no existían aulas entonces tampoco saldrá en la lista. Una vez que se
asignen las aulas a los exámenes y se compruebe que existen
estudiantes sin ubicación,  sean ubicados y evidentemente insertados
en esta entidad entonces es que saldrán en el listado.

**Comment by eadomenech** [comment]
Para la asignación de las aulas a los estudiantes se debe tener en cuenta varias acciones. Al producirse una de estas se volverá a realizar la asignación de aulas a cada estudiante para realizar sus respectivos exámenes de acceso:
- **Inscripción de un estudiante** : Al hacer pago de la inscripción que es el último paso de la inscripción.
- **Modificación de las salas de aula** : Al modificar las aulas, ya sea al eliminar una o ponerla inactiva o cambiar el número que representa la capacidad de estudiantes que puede tener a la ves, etc.
- **Modificación de la asignación de aulas a los exámenes** : Al modificar la asignación de aulas a los exámenes, más cuando se elimina un aula de un examen específico o cuando se agrega un aula para un examen.
- **Modificación de las carreras por la que opta un determinado candidato** : Al modificar al menos una de las dos opciones que tienen los candidatos para elegir las posibles carreras a cursar.

Nota: Hay que tener en cuenta que solo se volverá a realizar la asignación si algunas de estas acciones se realizan dentro del periodo del evento en cuestión. Una vez fuera de fecha de este evento se podrá por ejemplo modificar las salas de aula y no se volverá a realizar la asignación automática de las aulas.

**Comment by ybenitezf** [comment]
Estas:
- **Inscripción de un estudiante** : Al hacer pago de la inscripción que es el último paso de la inscripción.
- **Modificación de las carreras por la que opta un determinado candidato** : Al modificar al menos una de las dos opciones que tienen los candidatos para elegir las posibles carreras a cursar.

Son un buen problema, además que añaden una carga innecesaria de computo al sistema, yo todavía pienso que esto no se debería hacer de forma automática, sino explícitamente por el usuario o cuando es realmente evidente necesario, es decir los casos en que se modifiquen la capacidad de un aula implicada en un examen, cuando se modifiquen las aulas asignadas a un examen o cuando se agreguen candidatos a un examen.

Aún así creo que no sería necesario hacer esto así, yo supongo que por muy a lo loco que funcionen las cosas allá, debe haber un momento en que las candidaturas se congelan y nada de lo anterior sufra modificaciones.

**Comment by ybenitezf** [comment]
No, loco, en realidad no hace falta realizar la asignación de las aulas en ninguno de esos casos, te explico: la finalidad de todos esto es obtener el listado de los estudiantes con el aula que le toca para el examen, ese listado no se puede obtener hasta que no se hayan asignado las aulas para el examen y la condición que se necesita para que eso suceda es que exista espacio suficiente en las aulas seleccionadas para el examen, entonces:
1. Solo se permite obtener el listado de los estudiantes por aulas si la suma de las capacidades de las aulas es = o > que la cantidad de estudiantes que van a realizar el examen.
2. Si lo anterior se cumple entonces antes de mostrar el listado se hace la distribución de las aulas si y solo si hay estudiantes que deben realizar el examen y no han sido acomodados en ningún aula todavía.
