### ISSUE TITLE
¿año académico de los examenes de acceso?

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#71]
Loco, en el #70 al final se dice:

> Todo este proceso debe ocurrir dentro del marco de tiempo del evento Candidatura para el año académico que comienza.

Es decir, ¿sí estamos en el año académico 2015, es correcto asumir que el proceso de candidatura ocurrirá en el año 2016? según lo que me has explicado debe ser así, pero te pregunto esto porque tal vez el proceso de los candidatos comience antes de que termine el año académico actual o no, y se ejecute en el mismo año 2016, entonces aquí será mejor dejar que el usuario especifique cual año académico se debe usar, pero solo puede ser uno de los 2 el actual o el que viene.

**Comment by ybenitezf** [comment]
cambie el nombre, creo que debía ser en forma de pregunta.

**Comment by ybenitezf** [comment]
El examen de acceso debe estar ligado a un evento _inscripción_ para el año académico actual o siguiente, cosa que se podría determinar por las fechas de inicio y fin del evento, ¿crees que es correcto suponer esto? tu me explicaste que la candidatura se realiza siempre en los primeros meses del año que comienza o en los últimos de el que termina.

**Comment by ybenitezf** [comment]
En el diagrama de #72 se me aclaró la duda. La relación va dada por el evento al que pertenece el examen.

**Comment by eadomenech** [comment]
lo veo bien así, solo se podrá escoger uno de esos 2 años académicos (el presente o el siguiente). Hasta ahora siempre se ha hecho a partir del 2 de enero pero debemos preveer, en cualquier momento lo hacen a partir de diciembre.

**Comment by ybenitezf** [comment]
Todavía tengo la duda, fijate en el diagrama de #72, veras que por un lado el examen tendrá relación con un evento y por transitividad estará relacionado con un año académico de una unidad orgánica. Pero la candidatura no está relacionada

**Comment by ybenitezf** [comment]
Lo cerré sin querer.

**Comment by ybenitezf** [comment]
aclarado todo
