### ISSUE TITLE
Diagrama ER para "Examen de acceso"

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#72]
Leete la descripción de #70 y dime si a este diagrama le falta algo, aquí se agrega la entidad _examen de acceso_, necesito que analices si es posible tener sencillamente **examen** y entonces agregar un atributo _tipo_ que de el tipo de examen. Esto pensando que en un futuro vamos a tener otros tipos de exámenes.

![examen_er](https://cloud.githubusercontent.com/assets/8646381/8761878/97a59714-2d35-11e5-9029-3284671170d2.png)

**Comment by eadomenech** [comment]
De aquí lo que me preocupa son la relación Carrera-Unidad orgánica. Realmente, si pensamos en que el sistema se pueda utilizar a nivel de ministerio o universidad, esa relación debe ser \* - \* Ahora hay una realidad, lo más frecuente es que si dos UO tienen una misca carrera, los planes curriculares de estas son diferentes. 

Algo similar pasa con UO y los Anos académicos, varias UO pueden tener un mismo Año Academico.

Algo que me preocupa es que los estudiantes no están relacionados con los exámenes (directamente) Y por el diagrama hay que dar unas cuantas vueltas para llegar a ellos. Crees que eso no tendría problema en el futuro?

Otra cosa es lo que me decías en otro lado, sobre la posibilidad de poner una entidad examen y ponerle como tipo para este caso "acceso". Eso lo veo bien porque el proceder será el mismo, me refiero al otrogamiento de notas etc. Lo que estos exámenes no tendrían nada que ver con candidatura, por lo que si optamos por una sola entidad "examen" tendríamos que ver como poner la relación.

**Comment by ybenitezf** [comment]
> De aquí lo que me preocupa son la relación Carrera-Unidad orgánica. Realmente, si pensamos en que el sistema se pueda utilizar a nivel de ministerio o universidad, esa relación debe ser \* - \* Ahora hay una realidad, lo más frecuente es que si dos UO tienen una misca carrera, los planes curriculares de estas son diferentes.

Recuerda qué aquí, según lo tenemos hecho, a una carrera no la define solamente la unidad orgánica a la que pertenece, sino también el **plan curricular**, y precisamente lo que aparece como **carrera** en este diagrama es la relación de _muchos a muchos_ entre las unidades orgánicas y las definiciones de carreras que da el ministerio, que tiene como atributo el/los plan curricular, espero esto te aclare esa parte.

> Algo similar pasa con UO y los Anos académicos, varias UO pueden tener un mismo Año Academico.

En el caso de los años académicos y su relación con las UO, pretendo agregar esa relación que ahora mismo no existe, además porque me permite situar un evento en una unidad orgánica concreta.

> Algo que me preocupa es que los estudiantes no están relacionados con los exámenes (directamente) y por el diagrama hay que dar unas cuantas vueltas para llegar a ellos. Crees que eso no tendría problema en el futuro?

No

> Otra cosa es lo que me decías en otro lado, sobre la posibilidad de poner una entidad examen y ponerle como tipo para este caso "acceso". Eso lo veo bien porque el proceder será el mismo, me refiero al otrogamiento de notas etc. Lo que estos exámenes no tendrían nada que ver con candidatura, por lo que si optamos por una sola entidad "examen" tendríamos que ver como poner la relación.

Contestando a los dos párrafos anteriores con lo mismo, la relación del estudiante con el examen viene dada por los resultados que este obtenga en la asignatura, fijate en el diagrama: **examen** tiene relación solo con **asignatura** - como ocurre en la vida real - y la relación con el estudiante viene dada por las asignaturas que pertenezcan al plan curricular de una carrera para la que este candidata. No te preocupes porque estén muy lejos la una de la otra.

**Comment by ybenitezf** [comment]
Congelado.
