### ISSUE TITLE
diseñar UI para agregar examen(es) de acceso

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#76]
Creo que podíamos resolver con las pantallas que adjunto.
![paso1](https://cloud.githubusercontent.com/assets/8646381/8812812/53840e0a-2fcc-11e5-8793-4812bc4592f6.jpeg)

Esta primera pantalla (paso1) solo en caso de que exista más de una unidad orgánica, en el caso de que exista solo una se iría directo a la segunda pantalla.

![paso2](https://cloud.githubusercontent.com/assets/8646381/8812810/5249695e-2fcc-11e5-9166-f6e664421005.jpeg)

En el paso 2, se seleccionará de los eventos activos para la unidad orgánica - la que se escoja en el paso 1 - del tipo 'inscripción'  a cual se le gestionarán los exámenes.

![img_20150723_085136-01](https://cloud.githubusercontent.com/assets/8646381/8850875/8e0a55cc-3119-11e5-963b-352fc41f292e.jpeg)

En el paso 3, aparecerá la lista de exámenes disponibles - que se han creado - para el evento seleccionado, se podrá editar los parámetros del examen ( aulas y fecha) y **agregar examen**.

**Comment by ybenitezf** [comment]
Actualice el diseño, todavía quedan cosas pendientes.

**Comment by eadomenech** [comment]
El paso 1 OK
El paso 2 no creo que sea necesario pues solo se permitirá tener un solo evento activo de tipo "Inscripción" para cada UO. En caso de no tener ninguno activo se informará y en caso de tener uno se irá directo al paso 3.
En el paso 3 faltaría un campo, sería algo como período ("Mañana", "Tarde" o "Noche") pues pueden planificarse varios exámenes de acceso en una misma aula en un mismo día, solo que sería en períodos distintos.

**Comment by ybenitezf** [comment]
No estoy de acuerdo con respecto al paso 2, te explico: la idea del paso 2 es que se pueda acceder a través de este también a los exámenes de acceso de los eventos pasados, es decir de otros años académicos.

En cuando al paso 3, es verdad, falta el período, lo que pasa es que tampoco esta en la descripción que se da en #70, debiste darte cuenta ahí, ahora lo actualizo todo.

**Comment by ybenitezf** [comment]
Ya actualice el paso 3.

**Comment by eadomenech** [comment]
En cuanto al paso 2: Si lo tienes pensado así entonces sobra lo de "se seleccionarán los eventos activos" pues activo solo habrá a lo sumo uno. Si lo hacemos como tienes pensado entonces con que sea de tipo "Inscripción" basta.

**Comment by eadomenech** [comment]
En el paso 3 dice “Borrar” y “Eliminar”. Cual es la diferencia? Estos elemento no se modificarán?

**Comment by ybenitezf** [comment]
error mio, pero como ya había dibujado eso y le había tirado la foto
no tenía ganas de corregirlo, ahí uno es **borrar** y el otro
**editar**.

El 23/7/15, Ernesto Avila Domenech notifications@github.com escribió:

> En el paso 3 dice “Borrar” y “Eliminar”. Cual es la diferencia? Estos
> elemento no se modificarán?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/76#issuecomment-124211488

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by ybenitezf** [comment]
creo que con este terminamos esta parte, la UI esta completa.
