### ISSUE TITLE
actualizar UI de manejo de años académicos

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#77]

**Comment by ybenitezf** [comment]
Creo que se puede dejar como mismo esta, agregando una columna más para la unidad orgánica, y en la acción de crear, mostrar por defecto la UO que se crea de forma automática para la escuela (sede central)
![pantallazo](https://cloud.githubusercontent.com/assets/8646381/8803891/775888f4-2f97-11e5-9586-9c720c757a41.png)

**Comment by eadomenech** [comment]
No le veo sentido a esto. Para qué mostrar el mismo año académico para cada UO. En lo funcional para el sistema puede que sea conveniente, pero para aquí no le veo utilidad.

**Comment by ybenitezf** [comment]
Mira se podría hacer como mismo hicimos para regímenes y carreras, pero no veo la necesidad de demorarnos más es crear una interfaz que solo se usará una ves al año.

**Comment by ybenitezf** [comment]
Si no tienes más inconvenientes con esto, cierra este issue.
