### ISSUE TITLE
listar candidatura no muestra todos los candidatos

### ISSUE THREAD

**Issue by ybenitezf** [yotech/agis#79]
Al agregar candidaturas para el año que sigue, por ejemplo si nos encontramos en mitad del año académico 2015 y se agrega una candidatura para el año 2016, esta no es mostrada en el listado de las candidaturas.

El problema parece estar en la implementación de `obtener_manejo` en `modules.db.candidatura`, donde se asume siempre el año académico actual a la hora de filtrar las candidaturas:

``` python
if not ano_academico_id:
    ano_academico_id = ( ano_academico.buscar_actual() ).id
query = ( (db.persona.id == db.estudiante.persona_id) & 
    (db.candidatura.estudiante_id == db.estudiante.id) &
    (db.candidatura.ano_academico_id == ano_academico_id)
)
```

**Comment by ybenitezf** [comment]
Creo que agregando un filtro a la interfaz de manejo se puede resolver esto, como en la imagen siguiente:

![candidatura_iss79](https://cloud.githubusercontent.com/assets/8646381/8856015/388788f0-3136-11e5-91fa-f1374be900af.jpg)

**Comment by eadomenech** [comment]
Esto está ok.

**Comment by ybenitezf** [comment]
No era necesario el cambio en la UI, disculpa la molestia con el análisis, el filtro por año académico ya se incluía en el GRID.

Solo era tenerlo en cuenta en el source, ya esta en vías de solución
