### ISSUE TITLE
Error al entrar en Examenes de Acceso

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#81]
Al estar el sistema desde inicio (al hacer clone) e ir directo a Examen de Acceso da error.

<type 'exceptions.AttributeError'> 'Query' object has no attribute 'select'

**Comment by ybenitezf** [comment]
claro loco si no no he terminado con eso, de todas formas el error te lo da precisamente porque no existen ninguno de los datos que son pre-requisitos para que eso funcione.
