### ISSUE TITLE
Exportar a PDF el listado de los estudiantes por examen de acceso 

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#85]
La dar clic en el vínculo "Exportar a PDF", correspondiente a la funcionalidad #84, se exportará en un archivo .pdf los datos siguientes: Número de inscripción, Nombre completo y Nombre del aula donde examinará la asignatura en cuestión.
Antes de Los datos antes mencionados aparecerá de forma centrada el logotipo del IES, debajo de forma centrada también el nombre del IES y luego (debajo) el nombre de la UO.
Un poco más bajo y antes del listado como tal, iría de forma justificada el año académico, el nombre de la asignatura, la fecha de realización del examen y el periodo de examen. 
![listado](https://cloud.githubusercontent.com/assets/11457046/8964333/eed2227e-361c-11e5-91b2-2c9ba0d7fda8.png)

**Comment by ybenitezf** [comment]
¿como se sabes en que aula va cada estudiante? en el sistema la relación es con examen, es decir lo que yo conozco es en que aulas se va a hacer el examen no tengo forma de saber en que aula se va a poner cada estudiante, además no tiene sentido que sea así pq eso siempre puede cambiar de acuerdo a la situación y mejor porque le dejas la libertad a los que organizan el examen de acomodar a los estudiantes de acuerdo a las posibilidades de los locales, esto es valido para #86 también

**Comment by ybenitezf** [comment]
Ya esto debería cerrarse, si estas de acuerdo ciérralo.

**Comment by ybenitezf** [comment]
si estas de acuerdo cierra esto ya
