### ISSUE TITLE
Exportar a EXCEL el listado de los estudiantes por examen de acceso 

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#86]
La dar clic en el vínculo "Exportar a Excel", correspondiente a la funcionalidad #84, se exportará en un archivo .xls los datos siguientes: Número de inscripción, Nombre completo y Nombre del aula donde examinará la asignatura en cuestión.
Antes de Los datos antes mencionados aparecerá de forma centrada el logotipo del IES, debajo de forma centrada también el nombre del IES y luego (debajo) el nombre de la UO.
Un poco más bajo y antes del listado como tal, iría de forma justificada el año académico, el nombre de la asignatura, la fecha de realización del examen y el periodo de examen.

**Comment by ybenitezf** [comment]
Para esto vamos a usar: http://github.com/jmcnamara/XlsxWriter
hay que instalarlo, ver documentación de como en: https://xlsxwriter.readthedocs.org/getting_started.html

**Comment by ybenitezf** [comment]
Ya esto esta completo, creo, en el último commit le hice unas cuantas mejoras, creo que no debería incluir el logo pero si hace falta dimelo, sino cierra este issue.

**Comment by eadomenech** [comment]
Ponle el logo y cimprueba q tenga el ancho ideal para inprimir en A4

**Comment by ybenitezf** [comment]
y que se yo de eso, papo, eso no es tan sencillo, pero bueno, lo
intentaré, lo de la imagen creo que será difícil.

El 13/8/15, Ernesto Avila Domenech notifications@github.com escribió:

> Ponle el logo y cimprueba q tenga el ancho ideal para inprimir en A4
> 
> Yoel Benítez Fonseca notifications@github.com escribió:
> 
> > Yaestoestacompleto,creo,enelúltimocommitlehiceunascuantasmejoras,creoquenodeberíaincluirellogoperosihacefaltadimelo,sinocierraesteissue.ReplytothisemaildirectlyorviewitonGitHub.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yotech/agis/issues/86#issuecomment-130724527

## 

Msc. Yoel Benítez Fonseca
Especialista en TI
Redacción Adelante
Tel.: (53 32)284701

**Comment by eadomenech** [comment]
Ok No pierdas tiempo en eso Ponte para el otorgamiento de nota

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 13 de agosto de 2015 18:03:22 Yoel Benítez Fonseca 
notifications@github.com escribio:

> y que se yo de eso, papo, eso no es tan sencillo, pero bueno, lo
> intentaré, lo de la imagen creo que será difícil.
>

**Comment by ybenitezf** [comment]
ya esto debe estar completo, cierralo
