### ISSUE TITLE
Todos los datos que se expongan en el sistema deben estar capitalizados

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#89]
Todos los datos que sean informativos, deberán estar en letras CAPITALIZADAS. No importa que que hayan introducido en minúsculas.
Lo que propongo es lo siguiente: Cada vez que se adicionará o modificará algo en la bd se capitalice primero y luego de inserte o modifique.

**Comment by ybenitezf** [comment]
¿a que te refieres cuando dices que un dato es informativo?

**Comment by eadomenech** [comment]
Todos los datos q se alnacenan en BD Todos los reportes deben darse cin letras capitaluzadas

**Comment by eadomenech** [comment]
Por supuesto menos los email y cosas asi

**Comment by ybenitezf** [comment]
joder, lo mails también se guardan en la BD, usted vera, no improta, así se hará
