### ISSUE TITLE
Posibilidad de Traducción a la hora de adicionar y modificar un IES

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#9]
Las aclaraciones: "Registration code in Ministry. Should be 3 consecutive digits, for example 001", "No se ha seleccionado ningún archivo" y "seleccione para eliminar" no se le puede hacer la traducción. Me imagino que le falten las etiquetas T{}

**Comment by ybenitezf** [comment]
Fixed: Las etiquetas T estaban, se soluciono al yo agregar el lenguaje PT a mi navegador.
