### ISSUE TITLE
Problemas al adicionar una escuela precedente que no pertenezca a Angola 

### ISSUE THREAD

**Issue by eadomenech** [yotech/agis#90]
Perteneciente al issue #23. Cuando se seleccione el tipo de enseñanza media "Estudos feitos no Extrangeiro" se inhabilitarán los campos Provincia y Municipio en el formulario y se almacenará en dichos campos en la bd "Outro".

El campo "Tipo de Enseñanza Media" debe ir arriba de los campos Provincia y Municipio.

**Comment by ybenitezf** [comment]
Esto costará que le deba prefijar un ID o código fijo a ese _tipo de enseñanza media_ ya que el comportamiento del sistema dependerá en cierto grado del mismo, lo mismo ocurrirá con las provincias, municipios y comunas "Outro", serán necesarias para representar referencias a _no nacionales_.

Y de paso habrá que proteger estos valores para que no se puedan eliminar.
